<?php
 /*
 START LICENSE AND COPYRIGHT
 
 This file is part of Translate5 Editor PHP Serverside and build on Zend Framework
 
 Copyright (c) 2013 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ÄTT) MittagQI.com

 This file may be used under the terms of the GNU General Public License version 3.0
 as published by the Free Software Foundation and appearing in the file gpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU General Public License version 3.0 requirements will be met:
 http://www.gnu.org/copyleft/gpl.html.

 For this file you are allowed to make use of the same FLOSS exceptions to the GNU 
 General Public License version 3.0 as specified by Sencha for Ext Js. 
 Please be aware, that Marc Mittag / MittagQI take no warranty  for any legal issue, 
 that may arise, if you use these FLOSS exceptions and recommend  to stick to GPL 3. 
 For further information regarding this topic please see the attached license.txt
 of this software package.
 
 MittagQI would be open to release translate5 under EPL or LGPL also, if this could be
 brought in accordance with the ExtJs license scheme. You are welcome to support us
 with legal support, if you are interested in this.
 
 
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU General Public License version 3.0 http://www.gnu.org/copyleft/gpl.html
             with FLOSS exceptions (see floss-exception.txt and ux-exception.txt at the root level)
 
 END LICENSE AND COPYRIGHT 
 */
?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
    <head>
    </head>
    <body>
        <h1>HALLO WELT</h1>
        <p>Template /erp/index/index</p>
        <h2>REST-Routes (exemplarische Links)</h2>
        <ul>
            <li>ORDER</li>
            <li><a href="/erp/order">/erp/order</a></li>
            <li><a href="/erp/order/1">/erp/order/1</a></li>
            <li>PURCHASEORDER</li>
            <li><a href="/erp/purchaseorder">/erp/purchaseorder</a></li>
            <li><a href="/erp/purchaseorder/1">/erp/purchaseorder/1</a></li>
            <li>CUSTOMER</li>
            <li><a href="/erp/customer">/erp/customer</a></li>
            <li><a href="/erp/customer/1">/erp/customer/1</a></li>
            <li>COMMENT</li>
            <li><a href="/erp/ordercomment">/erp/ordercomment</a></li>
            <li><a href="/erp/purchaseordercomment">/erp/purchaseordercomment</a></li>
            <li>USER</li>
            <li><a href="/erp/user">/erp/user</a></li>
            <li>EXCEL-DEMO</li>
            <li><a href="/erp/order/excel">/erp/order/excel</a></li>
            </ul>
    </body>
</html>