<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2017 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html
  
 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or 
 plugin-exception.txt in the root folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/**#@+ 
 * @author Marc Mittag
 * @package editor
 * @version 1.0
 * 
 */
/**
 * Klasse zum Zugriff auf die Tabelle mit Namen des Klassennamens (in lower case)
 */
class editor_Models_Db_Qmsubsegments extends Zend_Db_Table_Abstract {
    protected $_name    = 'LEK_qmsubsegments';
    public $_primary = 'id';

    /**
     * duplicates a QM Sub Segment entry identified by $taskGuid, $oldSegmentId, $subSegmentId
     * use $newSegmentId as segmentId for the duplicate, returns the autogenerated new id for the duplicate 
     * @param string $taskGuid
     * @param int $oldSegmentId
     * @param int $subSegmentId
     * @param int $newSegmentId
     * @param string $fieldedited
     * @return integer
     */
    public function cloneSubsegment(string $taskGuid, int $oldSegmentId, int $subSegmentId, int $newSegmentId, string $fieldedited) {
        $sql = sprintf('INSERT INTO %1$s (taskGuid, segmentId, qmtype, severity, comment, fieldedited) 
                       SELECT taskGuid, ?, qmtype, severity, comment, fieldedited
                       FROM %1$s 
                       WHERE segmentId = ? and taskGuid = ? and id = ? and fieldedited = ?', $this->_name);
        $this->getAdapter()->query($sql, array($newSegmentId, $oldSegmentId, $taskGuid, $subSegmentId, $fieldedited));
        return $this->getAdapter()->lastInsertId();
    }
}