<?php
/*
 START LICENSE AND COPYRIGHT
 
 This file is part of translate5
 
 Copyright (c) 2013 - 2022 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt
 included in the packaging of this file.  Please review the following information
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html

 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or
 plugin-exception.txt in the root folder of translate5.

 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
 		     http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt
 
 END LICENSE AND COPYRIGHT
 */

/**
 * 
 * REST Endpoint Controller to serve a Bconfs Filter List for the Bconf-Management in the Preferences
 *
 */
class editor_Plugins_Okapi_BconfFilterController extends ZfExtended_RestController {
    
    protected $entityClass = 'editor_Plugins_Okapi_Models_BconfFilter';

    /** @var editor_Plugins_Okapi_Models_BconfFilter $entity */
    protected $entity;
    /** @var editor_Plugins_Okapi_Models_DefaultFilter $defaultFilter */
    protected $defaultFilter;
    
    /**
     * sends all bconf filters as JSON
     * (non-PHPdoc)
     * @see ZfExtended_RestController::indexAction()
     */
    public function indexDefaultAction(){
        $filters = $this->entity;
        $s = $filters->db->select();
        if($this->getParam('default') == 1){
            $s->union($this->defaultFilter->db->select());
        }
        $this->view->rows = $filters->loadFloadFilterdCustom($s);
        $this->view->total = count($this->view->rows);
    }

    public function init() {
        parent::init(); // TODO: Change the autogenerated stub
        $this->defaultFilter = ZfExtended_Factory::get('editor_Plugins_Okapi_Models_DefaultBconfFilter');
    }
}