<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2021 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html
  
 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or 
 plugin-exception.txt in the root folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/* @var $this Zend_View */
?>

Editor.controller.Localizer.addPluginInit('matchAnalysis', function() {

    Ext.define("Editor.locale.plugins.MatchAnalysis.controller.MatchAnalysis", {
        override: "Editor.plugins.MatchAnalysis.controller.MatchAnalysis",
        strings: {
            finishTask:'<?php echo $this->translate->_("Beenden");?>',
            taskGridIconTooltip:'<?php echo $this->translate->_("Match-Analyse");?>',
            preTranslation:'<?php echo $this->translate->_("Analyse &amp; Vorübersetzungen starten");?>',
            preTranslationTooltip:'<?php echo $this->translate->_("Die Vorübersetzung löst auch eine neue Analyse aus");?>',
            analysis:'<?php echo $this->translate->_("Analyse Starten");?>',
            startAnalysisMsg:'<?php echo $this->translate->_("Match-Analyse und Vorübersetzungen werden ausgeführt.");?>',
            finishAnalysisMsg:'<?php echo $this->translate->_("Die Match-Analyse und die Vorübersetzung sind abgeschlossen.");?>',
            internalFuzzy:'<?php echo $this->translate->_("Zähle interne Fuzzy");?>',
            pretranslateMatchRate:'<?php echo $this->translate->_("Vorübersetzungs Match-Rate");?>',
            pretranslateMatchRateTooltip:'<?php echo $this->translate->_("Vorübersetzung mit TM-Match, die größer oder gleich dem ausgewählten Wert ist");?>',
            pretranslateTmAndTerm:'<?php echo $this->translate->_("Vorübersetzen (TM &amp; Terme)");?>',
            pretranslateTmAndTermTooltip:'<?php echo $this->translate->_("Treffer aus der Terminologie werden bevorzugt vorübersetzt.");?>',
            pretranslateMt:'<?php echo $this->translate->_("Vorübersetzen (MT)");?>',
            pretranslateMtTooltip:'<?php echo $this->translate->_("Treffer aus dem TM werden bevorzugt vorübersetzt");?>',
            analysisLoadingMsg:'<?php echo $this->translate->_("Analyse läuft");?>'
        }
    });

    Ext.define("Editor.locale.plugins.MatchAnalysis.view.AnalysisPanel", {
        override: "Editor.plugins.MatchAnalysis.view.AnalysisPanel",
        strings: {
            noMatch:'<?php echo $this->translate->_("Keine Treffer");?>',
            matchCount:'<?php echo $this->translate->_("Gesamtzahl der Wörter");?>',
            tabTitle:'<?php echo $this->translate->_("Analyse");?>',
            exportAnalysis:'<?php echo $this->translate->_("Export als Excel");?>',
            exportAnalysisXML:'<?php echo $this->translate->_("Export Trados-like XML");?>',
            noAnalysis:'<?php echo $this->translate->_("Es wurde bisher keine Analyse erstellt. Starten Sie eine Analyse im Tab “Sprachressourcen zuweisen“");?>',
            languageResources:'<?php echo $this->translate->_("Sprachressourcen");?>',
            analysisDate:'<?php echo $this->translate->_("Datum der Analyse");?>',
            languageResourceName:'<?php echo $this->translate->_("Name");?>',
            repetitions:'<?php echo $this->translate->_("Wiederholungen:");?>',
            totalSum:'<?php echo $this->translate->_("Summe:");?>',
            internalFuzzy:'<?php echo $this->translate->_("Interne Fuzzy verwendet");?>',
            matchRate:'<?php echo $this->translate->_("Match-Rate");?>',
            edit100PercentMatchDisabledMessage:'<?php echo $this->translate->_("Gesperrte 100%-Matches sind nicht Teil der Analyse.");?>'
        }
    });

    Ext.define("Editor.locale.plugins.MatchAnalysis.view.LanguageResources", {
        override: "Editor.plugins.MatchAnalysis.view.LanguageResources",
        strings: {
            wizardTitle:'<?php echo $this->translate->_("Sprachressourcen zuweisen");?>'
        }
    });
});