<?php
/*
 START LICENSE AND COPYRIGHT

  This file is part of translate5

  Copyright (c) 2013 - 2022 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

  Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

  This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
  as published by the Free Software Foundation and appearing in the file agpl3-license.txt
  included in the packaging of this file.  Please review the following information
  to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
  http://www.gnu.org/licenses/agpl.html

  There is a plugin exception available for use with this release of translate5 for
  translate5: Please see http://www.translate5.net/plugin-exception.txt or
  plugin-exception.txt in the root folder of translate5.

  @copyright  Marc Mittag, MittagQI - Quality Informatics
  @author     MittagQI - Quality Informatics
  @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
             http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

 END LICENSE AND COPYRIGHT
 */

/* @var $this Zend_View */
?>

Editor.controller.Localizer.addPluginInit('matchAnalysis', function() {

    Ext.define("Editor.locale.plugins.MatchAnalysis.controller.MatchAnalysis", {
        override: "Editor.plugins.MatchAnalysis.controller.MatchAnalysis",
        strings: {
            finishTask:'<?php echo $this->translate->_('Finish'); ?>',
            taskGridIconTooltip:'<?php echo $this->translate->_('Match analysis'); ?>',
            preTranslation:'<?php echo $this->translate->_('Start analysis &amp; pre-translation'); ?>',
            preTranslationTooltip:'<?php echo $this->translate->_('A pre-translation also triggers a new analysis'); ?>',
            analysis:'<?php echo $this->translate->_('Start analysis'); ?>',
            analysisHint:'<?php echo $this->translate->_('Includes a QA and terminology check'); ?>',
            analysisNeedRerun:'<?php echo $this->translate->_('Analysis should be re-run for penalties to be saved and take effect'); ?>',
            startAnalysisMsg:'<?php echo $this->translate->_('Match analysis and pre-translations in progress.'); ?>',
            finishAnalysisMsg:'<?php echo $this->translate->_('The Match analysis and pre-translation have been completed.'); ?>',
            internalFuzzy:'<?php echo $this->translate->_('With internal fuzzy matches'); ?>',
            pretranslateMatchRate:'<?php echo $this->translate->_('TM pre-translation match rate'); ?>',
            pretranslateMatchRateTooltip:'<?php echo $this->translate->_('Use TM matches at or above the selected threshold for pre-translation'); ?>',
            pretranslateTmAndTerm:'<?php echo $this->translate->_('Pre-translate (TM &amp; terminology)'); ?>',
            pretranslateTmAndTermTooltip:'<?php echo $this->translate->_('Terminology matches are prioritized in pre-translation'); ?>',
            pretranslateMt:'<?php echo $this->translate->_('Pre-translate (MT)'); ?>',
            pretranslateMtTooltip:'<?php echo $this->translate->_('If this option is activated, the segments not pre-translated with the TM will be pre-translated with the MT.'); ?>',
            analysisLoadingMsg:'<?php echo $this->translate->_('Analysis in progress'); ?>'
        }
    });

    Ext.define("Editor.locale.plugins.MatchAnalysis.view.AnalysisPanel", {
        override: "Editor.plugins.MatchAnalysis.view.AnalysisPanel",
        strings: {
            tabTitle:'<?php echo $this->translate->_('Analysis'); ?>',
        }
    });

    Ext.define("Editor.locale.plugins.MatchAnalysis.view.AnalysisGrid", {
        override: "Editor.plugins.MatchAnalysis.view.AnalysisGrid",
        strings: {
            noMatch:'<?php echo $this->translate->_('No matches'); ?>',
            matchCount:'<?php echo $this->translate->_('Sum'); ?>',
            exportAnalysis:'<?php echo $this->translate->_('Export as Excel'); ?>',
            exportAnalysisXML:'<?php echo $this->translate->_('Export in Trados-style XML'); ?>',
            noAnalysis:'<?php echo $this->translate->_('No analysis has been created yet. Please start an analysis in the “Language resources” tab'); ?>',
            languageResources:'<?php echo $this->translate->_('Language resources'); ?>',
            analysisDate:'<?php echo $this->translate->_('Date of the analysis'); ?>',
            languageResourceName:'<?php echo $this->translate->_('Name'); ?>',
            repetitions:'<?php echo $this->translate->_('Repetitions:'); ?>',
            totalSum:'<?php echo $this->translate->_('Sum:'); ?>',
            internalFuzzy:'<?php echo $this->translate->_('Internal fuzzy matches used'); ?>',
            matchRate:'<?php echo $this->translate->_('Match rate'); ?>',
            edit100PercentMatchDisabledMessage:'<?php echo $this->translate->_('Locked 100% matches are not part of the analysis.'); ?>',
            wordBased:'<?php echo $this->translate->_('word-based'); ?>',
            characterBased:'<?php echo $this->translate->_('character-based'); ?>',
            basedOn:'<?php echo $this->translate->_('Based on'); ?>',
            fromImportedFile:'<?php echo $this->translate->_('From imported file'); ?>',
            hasErrors:'<?php echo $this->translate->_('During the analysis, {0} error(s) occurred while communicating with the language resources. <br />As a result, the analysis may be incomplete. Please check the task events and system log, and re-run the analysis if necessary.'); ?>'
        }
    });

    Ext.define("Editor.locale.plugins.MatchAnalysis.view.LanguageResources", {
        override: "Editor.plugins.MatchAnalysis.view.LanguageResources",
        strings: {
            wizardTitle:'<?php echo $this->translate->_('Associate language resources'); ?>'
        }
    });

    Editor.data.l10n.MatchAnalysis = {
        analysisWindow:{
            title: '<?php echo $this->translate->_('Match analysis'); ?>',
            summary: '<?php echo $this->translate->_('Sum'); ?>',
            amount: '<?php echo $this->translate->_('Amount'); ?>',
            finalAmount: '<?php echo $this->translate->_('Final amount'); ?>',
            notDefined: '<?php echo $this->translate->_('No pricing set for this language pair'); ?>',
        },
        pricing: {
            preset: {
                combo: '<?php echo $this->translate->_('Pricing preset'); ?>',
                create: '<?php echo $this->translate->_('Create new preset'); ?>',
                clone: '<?php echo $this->translate->_('Clone'); ?>',
                rename: '<?php echo $this->translate->_('Rename'); ?>',
                refresh: '<?php echo $this->translate->_('Refresh'); ?>',
                search: '<?php echo $this->translate->_('Search'); ?>',
                title: '<?php echo $this->translate->_('Match ranges &amp; pricing'); ?>',
                name: '<?php echo $this->translate->_('Preset name'); ?>',
                unitType: {
                    text: '<?php echo $this->translate->_('Type'); ?>',
                    character: '<?php echo $this->translate->_('character-based'); ?>',
                    word: '<?php echo $this->translate->_('word-based'); ?>'
                },
                desc: '<?php echo $this->translate->_('Description'); ?>',
                priceAdjustment: '<?php echo $this->translate->_('Adjust price by'); ?>',
                isDefault: {
                    text: '<?php echo $this->translate->_('Default'); ?>',
                    tooltip: '<?php echo $this->translate->_('Pricing preset selected by default on project creation if not overwritten on client-level'); ?>'
                },
                isCustomerDefault: {
                    text: '<?php echo $this->translate->_('Client default'); ?>',
                    tooltip: '<?php echo $this->translate->_('Pricing preset selected by default on project creation for this client'); ?>'
                },
                isTqeDefault: {
                    text: '<?php echo $this->translate->_('TQE default');?>',
                    tooltip: '<?php echo $this->translate->_('Template selected by default for TQE analysis - unless overridden at the customer level');?>'
                },
                isCustomerTqeDefault: {
                    text: '<?php echo $this->translate->_('Customer TQE');?>',
                    tooltip: '<?php echo $this->translate->_('Template selected by default for this customer‘s TQE analysis');?>'
                },
                prices: {
                    text: '<?php echo $this->translate->_('Prices'); ?>',
                    tooltip: '<?php echo $this->translate->_('Configure match ranges &amp; prices'); ?>'
                },
                actions: {
                    text: '<?php echo $this->translate->_('Actions'); ?>',
                    clone: '<?php echo $this->translate->_('Clone'); ?>',
                    delete: '<?php echo $this->translate->_('Delete'); ?>',
                }
            },
            prices: {
                title: '<?php echo $this->translate->_('Match ranges &amp; prices in preset'); ?>',
                create: '<?php echo $this->translate->_('Create prices for new language pair'); ?>',
                search: '<?php echo $this->translate->_('Search for price or language'); ?>',
                refresh: '<?php echo $this->translate->_('Refresh'); ?>',
                sourceLangs: '<?php echo $this->translate->_('Select source languages'); ?>',
                targetLangs: '<?php echo $this->translate->_('Select target language'); ?>',
                cloneFor: '<?php echo $this->translate->_('Clone prices for'); ?>',
                createFor: '<?php echo $this->translate->_('Create prices for'); ?>',
                sourceLang: '<?php echo $this->translate->_('Source language'); ?>',
                targetLang: '<?php echo $this->translate->_('Target language'); ?>',
                currency: '<?php echo $this->translate->_('Currency'); ?>',
                noMatch: '<?php echo $this->translate->_('No matches'); ?>',
                actions: {
                    header: '<?php echo $this->translate->_('Actions'); ?>',
                    edit: '<?php echo $this->translate->_('Edit'); ?>',
                    clone: '<?php echo $this->translate->_('Clone'); ?>',
                    delete: '<?php echo $this->translate->_('Delete'); ?>'
                }
            },
            range: {
                create: '<?php echo $this->translate->_('Create new range'); ?>',
                delete: '<?php echo $this->translate->_('Delete range'); ?>',
                selectToDelete: '<?php echo $this->translate->_('Select ranges to be deleted'); ?>',
                hint: '<?php echo $this->translate->_('Click on the column headings to edit the match ranges'); ?>',
                edit: '<?php echo $this->translate->_('Edit range'); ?>',
                less: '<?php echo $this->translate->_('Start value must be lesser or equal to end value!'); ?>',
                greater: '<?php echo $this->translate->_('End value must be bigger or equal to start value!'); ?>',
                overlaps: '<?php echo $this->translate->_('This value overlaps the range'); ?>',
                from: '<?php echo $this->translate->_('From'); ?>',
                till: '<?php echo $this->translate->_('To'); ?>'
            }
        }
    };
});