<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5

 Copyright (c) 2013 - 2021 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt
 included in the packaging of this file.  Please review the following information
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html

 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or
 plugin-exception.txt in the root folder of translate5.

 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
             http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/* @var ZfExtended_View $this */

$this->render('general.phtml');

$this->subject = sprintf($this->translate->_('Deadline reminder for the task “%s”'), $this->task->getTaskName());

$headers = [];
$headers[] = $this->header;
$headers[] = $this->templateApply('please remember to complete your assignment for the project below. The deadline is approaching.<br/><br/>Please log in here with your personal access data for processing:<br/><br/>{portalLink}<br/><br/>Double-click on the task to enter edit mode.You can also interrupt the processing of your task at any time and resume it at a later time.<br/><br/>You can also interrupt the processing of your task at any time and resume it at a later time.<br/>', $this->data);

if (isset($this->taskUserAssoc) &&
    ! empty($this->taskUserAssoc['deadlineDate']) &&
    $this->task->getConfig()->runtimeOptions->workflow->autoCloseJobs
) {
    $headers[] = sprintf(
        $this->translate->_('This job will be closed automatically on %s when the task deadline is reached.'),
        $this->taskUserAssoc['deadlineDate']
    );
}
$this->header = implode('', $headers);

$taskFragment = $this->templateApply('<br/><br/><b>Project details:</b><br/><br/><b>Project name:</b> {task.taskName}<br/><b>Source language:</b> {sourceLanguageTranslated} <br/><b>Target language:</b> {targetLanguageTranslated} <br/><b>Due by:</b> {deadlineDate}<br/><br/>', $this->taskData);

$footerText = $this->templateApply('<br/><br/>If you have any questions about translation or translate5, we are happy to help – just get in touch with us.<br/><br/>Kind regards,<br/><br/>{companyName}<br/><br/>', $this->taskData);

$this->textbody = "To be able to see the mail layout, you need to use app which supports html.";

echo $this->templateApply('{header}
{taskFragment}
{footer}{footerTable}', [
    'header' => $this->header,
    'taskFragment' => $taskFragment,
    'footer' => $footerText,
    'footerTable' => $this->footerTable,
]);
