version: '3.4'

##
## ADD THE LICENSE DISCLAIMER HERE
##
   
services:

    messagebuslocal:
        image: ${CONTAINER_REGISTRY_BASE}/frontendmessagebus
        ports:
            - '127.0.0.1:4756:9056'
            - '127.0.0.1:4757:9057'
        environment:
            MESSAGE_SERVER_ADDRESS: 0.0.0.0
            MESSAGE_SERVER_PORT: 9057
            SOCKET_SERVER_HOST: localhost
            SOCKET_SERVER_PORT: 9056

    t5memorylocal: # default port 4040
        image: ${CONTAINER_REGISTRY_BASE}/t5memory
        #entrypoint:
        #    /root/t5memory
        #    --port=4040
        #    --logtostderr=true
        #    --v=0
        #    --timeout=12000
        ports:
            - '127.0.0.1:4740:4040'


    termtaggerlocal_1: # default port 9001
        image: ${CONTAINER_REGISTRY_BASE}/opentmstermtagger
        ports:
            - '127.0.0.1:4701:9001'

    termtaggerlocal_2: # default port 9001
        image: ${CONTAINER_REGISTRY_BASE}/opentmstermtagger
        ports:
            - '127.0.0.1:4702:9001'

    languagetoollocal_1: # default port 8010
        image: ${CONTAINER_REGISTRY_BASE}/languagetool
        environment:
            langtool_languageModel: /ngrams
            Java_Xmx: 1024m #max heap space, at least 1024 for tests
        ports:
            - '127.0.0.1:4710:8010'
        volumes:
            - languagetool-ngrams:/ngrams
            - languagetool-dict:/dictionaries
            
    ## OKAPI for proper dev, we need to add several versions
    okapilocal: # default port 8080
        image: ${CONTAINER_REGISTRY_BASE}/okapi-longhorn
        ports:
            - '127.0.0.1:4780:8080'

    php-test:
        image: translate5/translate5-git
        build:
            context: ./translate5-git/
        entrypoint: bash /var/www/run-tests.sh # same as -from-git.sh + run tests
        # entrypoint: apache2-foreground DO NOT USE ME - since apache is then not running as developer if needed!
        volumes:
            - translate5-data:/var/www/translate5:cached
        environment:
            # set UID/GID directly in already bootstrapped installation - take care of installation.ini and DB Config!
            # set the optional variables for run-translate5-from-git.sh
            - LOCAL_UID=${LOCAL_UID}
            - LOCAL_GID=${LOCAL_GID}
            - GIT_BRANCH=${GIT_BRANCH}
            - GIT_TOKEN=${GIT_TOKEN}
            - GIT_USER=${GIT_USER}
            - APP_HOST=t5test-docker.localdev
            - T5_INSTALL_DB_HOSTNAME=db
            - T5_INSTALL_DB_USERNAME=translate5
            - T5_INSTALL_DB_PASSWORD=translate5
            - T5_INSTALL_DB_DATABASE=translate5runtests
    db:
        image: mariadb
        restart: always
        command:
            --default-authentication-plugin=mysql_native_password
            --sql_mode=ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_unicode_ci
            --innodb_ft_min_token_size=1
            --innodb_ft_enable_stopword=0
            --disable-log-bin
            --innodb_buffer_pool_size=2147483648
        environment:
            TZ: Europe/Berlin
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW-r00t}
            MYSQL_USER: ${MYSQL_USERNAME-translate5}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD-translate5}
            MYSQL_DATABASE: ${MYSQL_DATABASE-translate5}
        volumes:
            - translate5-db:/var/lib/mysql

volumes:
    translate5-db:
    translate5-data:
    languagetool-ngrams:
    languagetool-dict:

