<?php

use MittagQI\Translate5\Task\Overview\SegmentDataHeader;

function escapeComment(?string $comment): string
{
    if ($comment === null) {
        return '';
    }

    // Escape the content of the "content" span
    $comment = preg_replace_callback(
        '/(<span class="content">)(.*?)(<\/span>)/',
        static fn ($matches) => $matches[1] . htmlspecialchars($matches[2], ENT_QUOTES, 'UTF-8') . $matches[3],
        $comment
    );

    // Escape the content of the "author" span
    return preg_replace_callback(
        '/(<span class="author">)(.*?)(<\/span>)/',
        static fn ($matches) => $matches[1] . htmlspecialchars($matches[2], ENT_QUOTES, 'UTF-8') . $matches[3],
        $comment
    );
}

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php foreach ($this->stylesheets as $stylesheet): ?>
    <link rel="stylesheet" type="text/css"  href="<?= $stylesheet ?>" />
    <?php endforeach; ?>
    <title>Translation Task</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }

        .header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 20px;
        }

        .header img {
            height: 50px;
        }

        .task-info {
            text-align: center;
            flex-grow: 1;
        }

        .task-link {
            font-size: larger;
            text-decoration: none;
            color: #007bff;
        }

        .task-link:hover {
            text-decoration: underline;
        }

        .container {
            margin-top: 3rem;
        }

        .table {
            width: 100%;
            margin-bottom: 1rem;
            color: #212529;
            border-collapse: collapse;
        }

        .table-bordered {
            border: 1px solid #dee2e6;
        }

        .table-striped tbody tr:nth-of-type(odd) {
            background-color: rgba(0, 0, 0, 0.05);
        }

        .thead-light th {
            color: #495057;
            background-color: #e9ecef;
            border-color: #dee2e6;
        }

        .table th,
        .table td {
            padding: .75rem;
            vertical-align: top;
            border-top: 1px solid #dee2e6;
            border-left: 1px solid #dee2e6;
        }

        .table th:last-child,
        .table td:last-child {
            border-right: 1px solid #dee2e6;
        }

        tr:hover {
            background-color: #f1f1f1;
        }
        ins {
            background-color: #d4edda;
            text-decoration: none;
            border-bottom: 1px dotted #155724;
        }
        del {
            background-color: #f8d7da;
            text-decoration: line-through;
            border-bottom: 1px dotted #721c24;
        }
        ins[data-message], del[data-message], span[data-message] {
            position: relative;
        }
        span[data-message]:hover:after,
        ins[data-message]:hover:after,
        del[data-message]:hover:after {
            content: attr(data-message);
            position: absolute;
            background-color: rgba(51, 51, 51, 0.7);
            color: #fff;
            padding: 5px;
            border-radius: 3px;
            white-space: nowrap;
            z-index: 1000;
            left: 0;
            top: -100%; /* Adjust tooltip positioning */
            transform: translateY(-5px); /* Move tooltip above the element */
            word-wrap: break-word;
        }
        span[data-message]:hover:before,
        ins[data-message]:hover:before,
        del[data-message]:hover:before {
            content: '';
            position: absolute;
            top: 100%;
            left: 0;
            border-width: 5px;
            border-style: solid;
            border-color: rgba(51, 51, 51, 0.7) transparent transparent transparent;
            z-index: 1000;
        }
        span[data-message]:hover:after,
        ins[data-message]:hover:after,
        del[data-message]:hover:after {
            top: auto;
            bottom: 100%;
        }

        .comment {
            border: 1px solid #ddd;
            background-color: #f9f9f9;
            padding: 10px;
            margin-bottom: 10px;
            border-radius: 5px;
        }

        .comment:last-child {
            margin-bottom: 0;
        }

        .content {
            display: block;
            margin-bottom: 5px;
            color: #333;
        }

        .author, .modified {
            display: inline-block;
            font-size: 13px;
            color: #555;
        }

        .modified {
            margin-left: 20px;
            font-size: 12px;
            color: #888;
        }

        .comment:hover {
            background-color: #f1f1f1;
            border-color: #ccc;
        }
    </style>
</head>
<body>

<div id="head-panel" class="header" style="min-height: 125px">
    <div class="task-info">
        <a href="<?= $this->taskUrl ?>" target="_blank" class="task-link"><?= htmlspecialchars($this->taskName) ?></a>
    </div>
</div>

<div class="container">
    <div class="table-responsive">
        <table class="table table-bordered table-striped">
            <thead class="thead-light">
            <tr>
            <?php foreach ($this->segmentDataTable->header->getFields() as $field): ?>
                <?php
                if (in_array($field->id, [SegmentDataHeader::FIELD_MANUAL_QS, SegmentDataHeader::FIELD_STATUS])) {
                    continue;
                }
                ?>
                <th><?= $field->label ?></th>
            <?php endforeach; ?>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->segmentDataTable->getRows() as $row): ?>
                <tr>
                <?php foreach ($this->segmentDataTable->header->getFields() as $field): ?>
                    <?php
                    if (in_array($field->id, [SegmentDataHeader::FIELD_MANUAL_QS, SegmentDataHeader::FIELD_STATUS])) {
                        continue;
                    }
                    ?>
                    <?php if ($field->id === SegmentDataHeader::FIELD_MANUAL_QS): ?>
                        <td><?= implode('<br />', $row[$field]) ?></td>
                    <?php
                        continue;
                        endif;
                    ?>
                    <?php if ($field->id === SegmentDataHeader::FIELD_COMMENTS): ?>
                        <td><?= escapeComment($row[$field]) ?></td>
                    <?php
                        continue;
                        endif;
                    ?>
                    <td><?= $row[$field] ?></td>
                <?php endforeach; ?>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

</body>
</html>
