<?php

use MittagQI\Translate5\Task\Overview\SegmentDataHeader;

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script type="text/javascript">
        window.exportService = window.exportService || {
            defaultFilters: {
                onlyHasComments: <?= json_encode($this->onlyHasComments) ?>,
                translatedStatus: <?= json_encode($this->defaultProcessingState) ?>
            },
            localizedStrings: {
                filtersLabels: {
                    onlyHasComments: "<?= $this->translate('Nur Segmente mit Kommentar anzeigen') ?>",
                    segmentProcessingStatus: "<?= $this->translate('Segment Prozessstatus') ?>",
                    matchRate: "<?= $this->translate('Matchrate') ?>",
                    alle: "<?= $this->translate('Alle') ?>",
                }
            }
        };
    </script>
    <?= $this->headStyle(); ?>
    <?= $this->headScript(); ?>
    <?php
    foreach ($this->stylesheets as $stylesheet): ?>
        <link rel="stylesheet" type="text/css" href="<?= $stylesheet ?>"/>
    <?php
    endforeach; ?>
    <title>Translation Task</title>
</head>
<body>

<div id="head-panel" class="header" style="min-height: 125px">
    <div class="task-info">
        <a href="<?= $this->taskUrl ?>" target="_blank" class="task-link"><?= htmlspecialchars($this->taskName) ?></a>
    </div>
</div>

<div class="container">
    <div class="table-responsive">
        <table id="data-table" class="table table-bordered table-striped">
            <thead class="thead-light">
            <tr>
                <?php
                foreach ($this->segmentDataTable->header->getFields() as $field): ?>
                    <?php
                    if (in_array($field->id, [SegmentDataHeader::FIELD_MANUAL_QS, SegmentDataHeader::FIELD_STATUS])) {
                        continue;
                    }
                    ?>
                    <th class="thead-field_name--<?= $field->id ?>"><?= $field->label ?></th>
                <?php
                endforeach; ?>
            </tr>
            </thead>
            <tbody>
<?php
            foreach ($this->segmentDataTable->getRows() as $row) {
                echo '<tr>';
                foreach ($this->segmentDataTable->header->getFields() as $field) {
                    if (in_array($field->id, [SegmentDataHeader::FIELD_MANUAL_QS, SegmentDataHeader::FIELD_STATUS])) {
                        continue;
                    }
                    if ($field->id === SegmentDataHeader::FIELD_MANUAL_QS) {
                        echo '<td>' . implode('<br />', $row[$field]) . '</td>';

                        continue;
                    }
                    if ($field->id === SegmentDataHeader::FIELD_COMMENTS) {
                        echo '<td>' . $this->taskCommentsEscape($row[$field]) . '</td>';

                        continue;
                    }
                    echo '<td>' . $row[$field] . '</td>';
                }
                echo '</tr>' . "\n";
            }
?>
            </tbody>
        </table>
    </div>
</div>

</body>
</html>
