<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5

 Copyright (c) 2013 - 2021 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt
 included in the packaging of this file.  Please review the following information
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html

 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or
 plugin-exception.txt in the root folder of translate5.

 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

// return json in case the request is not for the transalte5 UI
if(!isset($_REQUEST['t5ui'])){
    echo json_encode([
        'error' => $this->error ?? 'Unknown error',
    ], JSON_THROW_ON_ERROR);
    exit;
}

$translate = ZfExtended_Zendoverwrites_Translate::getInstance();
?>


<style>
    body {
        background-color: #f2f2f2;
        font-family: Arial, sans-serif;
    }

    .container {
        max-width: 600px;
        margin: 0 auto;
        padding: 40px;
        background-color: #fff;
        border-radius: 10px;
        box-shadow: 0 2px 5px rgba(0,0,0,0.1);
    }

    h1 {
        font-size: 32px;
        font-weight: bold;
        margin-top: 0;
        margin-bottom: 20px;
    }

    p {
        font-size: 18px;
        margin-top: 0;
        margin-bottom: 40px;
    }

    .error {
        color: red;
        font-weight: bold;
        padding: 20px;
        background-color: #f2dede;
        border-radius: 5px;
        border: 1px solid #ebccd1;
    }

    .header {
        display: flex;
        align-items: center;
        justify-content: space-between;
        margin-bottom: 40px;
    }

    .logo img {
        height: 60px;
    }
</style>


<div class="container">
    <div class="header">
        <div class="logo">
            <img src="/images/translate5.png" alt="Company Logo">
        </div>
    </div>
    <h1><?php echo $translate->_('Es ist ein Fehler aufgetreten!'); ?></h1>
    <p class="error"><?php echo $this->error; ?></p>
    <small><?php echo $translate->_('Weitere Informationen finden Sie im Ergebnisprotokoll.'); ?></small>
</div>