<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2021 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html
  
 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or 
 plugin-exception.txt in the root folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

$this->translate = ZfExtended_Zendoverwrites_Translate::getInstance();
if(empty($this->termGroups)) {
    echo '<p style="margin-bottom:5px;">'.$this->translate->_('Keine Terminologie vorhanden!').'</p>';
    return;
}
$termDivParams = function($class, $rtl) {
    $params =[$class];
    if($rtl) {
        $params[] = 'direction-rtl"';
        $params[] = 'dir="rtl';
    }
    return implode(' ', $params);
};

$attributes = $this->attributeGroups;
$renderAttributes = static function (int $termId, int $termEntryId, string $language) use ($attributes) {

    $renderHtml = '<div class="tooltiptext">';
    $html = [];

    foreach ($attributes['entry'] as $attribute){
        if((int)$attribute['termEntryId'] === $termEntryId){
            $html[] = '<li>'.$attribute['elementName'].' : '.$attribute['value'].'</li>';
        }
    }
    if(count($html) > 0){
        $renderHtml .= '<h3>Entry</h3>';
        $renderHtml .= '<ul>'.implode($html).'</ul>';
    }

    $html = [];

    foreach ($attributes['language'] as $attribute){
        if($attribute['language'] === $language){
            $html[] = '<li>'.$attribute['elementName'].' : '.$attribute['value'].'</li>';
        }
    }
    if(count($html) > 0) {
        $renderHtml .= '<h3>en</h3><img src="/modules/editor/images/flags/'.$language.'.png">';
        $renderHtml .= '<ul>' . implode($html) . '</ul>';
    }


    $html = [];

    foreach ($attributes['term'] as $attribute){
        if((int)$attribute['termId'] === $termId){
            $html[] = '<li>'.$attribute['elementName'].' : '.$attribute['value'].'</li>';
        }
    }

    if(count($html) > 0) {
        $renderHtml .= '<h3>Term</h3>';
        $renderHtml .= '<ul>' . implode($html) . '</ul>';
    }

    $renderHtml .= '</div>';

    return $renderHtml;

};

?>
<style type="text/css">
    .tooltip {
        display: inline-block;
    }

    .tooltip .tooltiptext {
        visibility: hidden;
        width: auto;
        background-color: black;
        color: #fff;
        text-align: left;
        border-radius: 6px;
        padding: 5px;

        position: absolute;
        z-index: 9999999999 !important;
    }

    .tooltip:hover .tooltiptext {
        visibility: visible;
    }
</style>
<div class="term-box">
<?php
    $i = 0;
    $termStatus = [
        'permitted' => $this->translate->_('erlaubte Benennung'),
        'forbidden' => $this->translate->_('verbotene Benennung'),
        'preferred' => $this->translate->_('Vorzugsbenennung'),
        'unknown' => $this->translate->_('Unbekannter Term Status'),
    ];
    foreach($this->termGroups as $termGroup) {
        $target = array();
        $source = array();
        $isSourceRtl = false;
        $isTargetRtl = false;


        foreach($termGroup as $term) {
            settype($term->rtl, 'boolean');
            $guiStatus = $term->status;
            if(empty($this->termStatMap[$guiStatus]) || empty($termStatus[$this->termStatMap[$guiStatus]])) {
                $guiStatus = 'unknown';
            }
            else {
                $guiStatus = $this->termStatMap[$guiStatus];
            }
            $title = $termStatus[$guiStatus].' ('.$term->status.')';
            $src = $this->publicModulePath.'/images/termStatus/'.$guiStatus.'.png';
            $itemStr = sprintf('<img src="%1$s" alt="%2$s" title="%2$s"/>', $src, $title);
            $class = array('term', $term->status);
            if($term->used){
                $class[] = 'used';
            }
            if($term->transFound){
                $class[] = 'transfound';
            }
            $definition = htmlspecialchars($term->definition);

            if($this->linkPortal) {
                //TODO would be better in the termportal plugin somehow, but currently there is no way to invoke here in the PHTML via plugin
                //for the syntax of the search array see TermPortal.view.termportal.TermportalController::encode64
                $search = [
                    $term->term,
                    $term->languageId,
                    '', //empty client-id filter
                    $term->collectionId,
                ];
                $url = APPLICATION_RUNDIR.'/editor/termportal#termportal/search/'.base64_encode(json_encode($search));
                $termText = '<a href="'.$url.'" target="termportalandinstanttranslate">'.$term->term.'</a>';
            }
            else {
                $termText = $term->term;
            }

            $itemStr .= sprintf('<span class="%3$s" title="%2$s">%1$s</span>', $termText, $definition, implode(' ', $class));

            //if(!empty($term->definition)){
                $src = $this->publicModulePath.'/images/termStatus/information-small-white.png';
                $itemStr .= '<div class="tooltip">';
                $itemStr .= sprintf(' <img class="tooltip" src="%1$s" alt="%2$s" title="%2$s"/>', $src, $definition);
                $itemStr .= $renderAttributes($term->id,$term->termEntryId,$term->language);
                $itemStr .= '</div>';
                
            //}
            if($term->isSource) {
                $source[] = $itemStr;
                $isSourceRtl = $term->rtl || $isSourceRtl;
            }
            else {
                $target[] = $itemStr;
                $isTargetRtl = $term->rtl || $isTargetRtl;
            }
        }
?>

        <div class="term-group <?php echo ($i++ % 2 == 0)?'even':'odd'; ?>">
            <div class="<?php echo $termDivParams('source-terms', $isSourceRtl);?>">
                <?php echo implode("<br />\n", $source); ?>
            </div>
            <div class="<?php echo $termDivParams('target-terms', $isTargetRtl);?>">
                <?php echo implode("<br />\n", $target); ?>
            </div>
        </div>
<?php
    }
?>
</div>