<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2021 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html
  
 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or 
 plugin-exception.txt in the root folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

//FIXME add manifest here if we implement better caching
//FIXME set lang to the lang of the users GUI

$config = Zend_Registry::get('config');
/* @var $config Zend_Config */

?><!DOCTYPE HTML>
<html lang="en-US">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="msapplication-config" content="none"/>
    <link rel="shortcut icon" href="<?php echo $this->pathToIMAGES; ?>/favicon.ico" type="image/x-icon"/>
    <title><?php echo $this->translate->_('translate5'); ?></title>
    <script>
    Editor = {};
    <?php
    echo $this->Php2JsVars();
    ?>;
    for (const directRedirectsKey in Editor.data.directRedirects) {
        if (location.hash.match(new RegExp('^#'+directRedirectsKey))) {
            location = Editor.data.directRedirects[directRedirectsKey];
            break;
        }
    }
    Editor.TRANSTILDE = '~@#!WS~';
    </script>
    <?php
        if($this->enableJsLogger) {
            echo $this->render('index/jslogger.phtml');
        }
        echo $this->render('index/app-js-'.$this->buildType.'.phtml');
        echo $this->headLink();
    ?>
</head>
<body class="loading">
    <div class="loading">
        <?php echo $this->translate->_('translate5 wird geladen:');?>
        <div id="loading-indicator-text"></div>
    	<div id="head-panel"></div>
        <?php if($config->runtimeOptions->startup->showConsortiumLogos > 0 && $this->getScriptPath('fragments/header-consortium-logos.phtml')) : ?>
            <div class="containerConsortium">
                <a href="https://www.translate5.net" target="_blank">
                    <?= $this->render('fragments/header-consortium-logos.phtml') ?>
                </a>
                <style>
                    .containerConsortium a {text-decoration: none;}
                    .float-container {border: none; padding: 20px 0 0 0; margin-left: -35px;}
                    .powered-text-container {margin-bottom: 0;}
                    .float-child {width: 100%;}
                </style>
            </div>
        <?php endif; ?>
    </div>
</body>
</html>
