<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2021 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html
  
 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or 
 plugin-exception.txt in the root folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/**
 * This is the default inclusion of therootcause logger in translate5.
 * To customize it, place a modified copy of this file in the client-specific folder:
 * APPLICATION_ROOT/client-specific/views/editor/scripts/index/
 * If the logger should be disabled completly just set in your config:
 *  
 *      runtimeOptions.debug.enableJsLogger = 0
 */
?>
    <script src="https://app.therootcause.io/rootcause-full-extjs.js" crossorigin="anonymous"></script>
    <script>
        (function() {
            // We use the jslogger on the global scope,
            // for usage see Editor.controller.JsLogger.
            jslogger = window.RC && new RC.Logger({
                applicationId : "1b60154d0a976fff59848a5e5607ac015df89161",
                captureScreenshot : true,
                recordUserActions : true,
                recordSessionVideo : false, // start and stop the video manually for each segment
                showIconWhileRecording: false, // can only be shown for the whole session, not during manually started recording only
                logConsoleOutput : true,
                logAjaxRequests : true,
                treatFailedAjaxAsError : false,
                logResourceLoadFailures : true,
                autoStart : true,
                showNotificationOnError : true,
                showFeedbackButton : false,
                data: {
                    controllers: Editor.data.app.controllers
                },
                user: {
                    name: Editor.data.app.user.login,
                    email: Editor.data.app.user.email,
                    userGuid: Editor.data.app.user.userGuid
                },
                showErrorDialog : {
                    titleText: 'Submit translate5 crash report'
                },
                maxNbrOfReportedErrors : 1,
                version : "<?php echo $this->appVersion; ?>",
                frameworkVersion : "ExtJS <?php echo $this->extJsVersion; ?>"
            });
        })();
    </script>