<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2021 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html
  
 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or 
 plugin-exception.txt in the root folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

?>
<form method="post">
	<h2>Input plain String</h2>
	<textarea name="input"><?php echo htmlspecialchars($this->input); ?></textarea>
	<h3>matchrate - reduce to get more fuzzy results</h3>
	<input type="text" name="matchrate" value="<?php echo htmlspecialchars($this->matchrate); ?>" />
	<button type="submit">GO</button>
	<?php if(!empty($this->input)) { ?>
	<h2>de.xliff</h2>
	<textarea name="deOut" rows="5"><?php echo htmlspecialchars($this->deOut); ?></textarea>
	<?php
	   if($this->exactMatch) {
    	    echo '<h2>en.xliff - found already in translations</h2>';
    	}
    	else {
    	    echo '<h2>en.xliff with multiple fuzzy matches</h2>';
    	}
    	if($this->noMatch) {
    	    echo '<p>No match found - reduce matchrate or translate manually</p>';
    	}
    	foreach($this->enOut as $enOut) {
    	    ?>
    	    <p>Matchrate: <?php echo $enOut['matchrate'];?></p>
    		<textarea name="enOut" rows="5"><?php echo htmlspecialchars($enOut['text']); ?></textarea>
    	    <?php 
    	}
    }
	?>
</form>