<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2021 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html
  
 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or 
 plugin-exception.txt in the root folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/
?>
<pre style="margin-left: 20px;">
<?php
foreach($this->validationResults as $module => $oneResult) {
    /* @var ZfExtended_Models_SystemRequirement_Result $oneResult */

    if($oneResult->hasError()) {
        $shortResult = '<span style="color:red;font-weight: bold;">problematic</span>';
    }
    elseif($oneResult->hasWarning()) {
        $shortResult = '<span style="color:yellow;font-weight: bold;">not optimal</span>';
    }
    else {
        $shortResult = '<span style="color:green;font-weight: bold;">all ok</span>';
    }
    echo(str_pad($oneResult->name, 30, ' ', STR_PAD_RIGHT).': '.$shortResult."\n");
    if($oneResult->hasError()) {
        echo "  ERROR(s): \n    ";
        echo join("\n    ", $oneResult->error);
        echo "\n\n";
    }
    if($oneResult->hasWarning()) {
        echo "  WARNING(s): \n    ";
        echo join("\n    ", $oneResult->warning);
        echo "\n\n";
    }
    if($oneResult->hasInfo()) {
        echo "  INFO(s): \n    ";
        echo join("\n    ", $oneResult->info);
        echo "\n\n";
    }
    // in case of errors or warnings we give hints how to fix that
    if($oneResult->hasBadSummary() && ($oneResult->hasWarning() || $oneResult->hasError())) {
        echo "  HINT(s): \n    ";
        echo join("\n    ", $oneResult->badSummary);
        echo "\n";
    }
}

?>
</pre>
