<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5

 Copyright (c) 2013 - 2021 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt
 included in the packaging of this file.  Please review the following information
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html

 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or
 plugin-exception.txt in the root folder of translate5.

 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
             http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

?>
<h1><?php echo $this->translate->_('Help'); ?></h1>
<p><?php echo $this->translate->_('In the repetition editor, all segments that repeat compared to the current segment are displayed. These can be segments whose source-language content matches the source-language column of the current segment (classic repetition). They can also be segments whose target-language content matches the target-language column of the current segment.'); ?></p>
<p><?php echo $this->translate->_('The source and target columns indicate with which column the current repetition matches'); ?></p>
<p><?php echo $this->translate->_('The column “Included in current filter” indicates whether the segment is visible (yes) or not (no) in the segment list, depending on the currently set filter.'); ?></p>
<p><?php echo $this->translate->_('“Do not conduct changes” cancels the repetition editor without applying changes to further segments, while “Accept changes” saves the changes for the selected segments, i.e. the segments flagged in the repetition editor.'); ?></p>
<p><?php echo $this->translate->_('You can select or deselect all segments via the checkbox in the column header.'); ?></p>