<?php
 /*
 START LICENSE AND COPYRIGHT
 
 This file is part of Translate5 Editor PHP Serverside and build on Zend Framework
 
 Copyright (c) 2013 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ÄTT) MittagQI.com

 This file may be used under the terms of the GNU General Public License version 3.0
 as published by the Free Software Foundation and appearing in the file gpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU General Public License version 3.0 requirements will be met:
 http://www.gnu.org/copyleft/gpl.html.

 For this file you are allowed to make use of the same FLOSS exceptions to the GNU 
 General Public License version 3.0 as specified by Sencha for Ext Js. 
 Please be aware, that Marc Mittag / MittagQI take no warranty  for any legal issue, 
 that may arise, if you use these FLOSS exceptions and recommend  to stick to GPL 3. 
 For further information regarding this topic please see the attached license.txt
 of this software package.
 
 MittagQI would be open to release translate5 under EPL or LGPL also, if this could be
 brought in accordance with the ExtJs license scheme. You are welcome to support us
 with legal support, if you are interested in this.
 
 
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU General Public License version 3.0 http://www.gnu.org/copyleft/gpl.html
             with FLOSS exceptions (see floss-exception.txt and ux-exception.txt at the root level)
 
 END LICENSE AND COPYRIGHT 
 */
$this->translate = ZfExtended_Zendoverwrites_Translate::getInstance();
?>
<h1><?php echo $this->translate->_('Hilfe'); ?></h1>
<p><?php echo $this->translate->_('Im Wiederholungseditor werden alle sich im Vergleich zum aktuellen Segment wiederholenden Segmente angezeigt. Dies können Segmente sein, deren quellsprachlicher Inhalt der quellsprachlichen Spalte des aktuellen Segments entspricht (klassische Wiederholung). Dies können aber auch Segmente sein, deren ZIELsprachlicher Inhalt der ZIELsprachlichen Spalte des aktuellen Segments entspricht.'); ?></p>
<p><?php echo $this->translate->_('Die Spalten Quell- bzw. Ziel-Treffer zeigen an, welche Spalte der Wiederholung mit dem aktuellen Segment übereinstimmt.'); ?></p>
<p><?php echo $this->translate->_('Die Spalte "In aktueller Filterung enthalten" zeigt an, ob das angezeigte Segment gemäß der aktuellen Filterung in der Segmentübersicht aktuell angezeigt wird (Ja), oder durch die gesetzten Filter ausgeblendet ist (Nein).'); ?></p>
<p><?php echo $this->translate->_('"Keine Änderung durchführen" bricht den Wiederholungseditor ohne Änderung an den weiteren Segmenten ab. "Änderung übernehmen" speichert die Änderungen der ausgewählten Segmente (Haken in der Zeile des Segments im Wiederholungseditor ist gesetzt).'); ?></p>
<p><?php echo $this->translate->_('Über das Häkchen in der Spaltenüberschrift lassen sich alle Segmente selektieren oder deselektieren.'); ?></p>