<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2021 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html
  
 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or 
 plugin-exception.txt in the root folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/* @var $this Zend_View */
?>
  
Editor.controller.Localizer.addPluginInit('globalesePreTranslation', function() {
    
    Ext.define("Editor.locale.plugins.GlobalesePreTranslation.view.GlobaleseAuth", {
        override: "Editor.plugins.GlobalesePreTranslation.view.GlobaleseAuth",
        strings: {
            skipPreTranslation:'<?php echo $this->translate->_("Globalese Vorübersetzung überspringen");?>',
            username:'<?php echo $this->translate->_("Globalese Benutzer");?>',
            wizardTitle:'<?php echo $this->translate->_("Globalese Authentifizierung");?>',
            apiKey:'<?php echo $this->translate->_("API Schlüssel");?>',
        }
    });
    
    Ext.define("Editor.locale.plugins.GlobalesePreTranslation.view.GlobaleseSettings", {
        override: "Editor.plugins.GlobalesePreTranslation.view.GlobaleseSettings",
        strings: {
            wizardTitle:'<?php echo $this->translate->_("Globalese Einstellungen");?>',
            nextButtonText:'<?php echo $this->translate->_("Importieren");?>',
            groupComboLabel:'<?php echo $this->translate->_("Globalese Benutzergruppe");?>',
            engineComboLabel:'<?php echo $this->translate->_("Globalese engine");?>',
            emptyComboText:'<?php echo $this->translate->_("Bitte wählen");?>',
        }
    });
    
    Ext.define("Editor.locale.plugins.GlobalesePreTranslation.view.GlobaleseAuthViewController", {
        override: "Editor.plugins.GlobalesePreTranslation.view.GlobaleseAuthViewController",
        strings: {
            noEnginesFoundMsg:'<?php echo $this->translate->_("Keine Globalese Übersetzungs-Engine verfügbar (für Ihren Globalese Benutzer und Ihre Sprachkombination). Bitte ändern Sie den Benutzer oder überspringen Sie die Vorübersetzung.");?>',
            noGroupsFoundMsg:'<?php echo $this->translate->_("Keine Globalese Benutzergruppe verfügbar (für Ihren Globalese Benutzer und Ihre Sprachkombination). Bitte ändern Sie den Benutzer oder überspringen Sie die Vorübersetzung.");?>',
            authErrorMsg:'<?php echo $this->translate->_("Benutzer oder Passwort sind nicht valide.");?>',
            loadingWindowMessage:'<?php echo $this->translate->_("Laden");?>',
            noEnginesForLanguageComboMsg:'<?php echo $this->translate->_("Für die aktuelle Sprachkombination existiert keine Engine in Globalese. Bitte überspringen Sie den Globalese Schritt für diesen Import.");?>'
        }
    });
});