<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2017 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html
  
 There is a plugin exception available for use with this release of translate5 for
 translate5 plug-ins that are distributed under GNU AFFERO GENERAL PUBLIC LICENSE version 3:
 Please see http://www.translate5.net/plugin-exception.txt or plugin-exception.txt in the root
 folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/* @var $this Zend_View */
?>
  
Editor.controller.Localizer.addPluginInit('globalesePreTranslation', function() {
    
    Ext.define("Editor.locale.plugins.GlobalesePreTranslation.view.GlobaleseAuth", {
        override: "Editor.plugins.GlobalesePreTranslation.view.GlobaleseAuth",
        strings: {
            skipPreTranslation:'<?php echo $this->translate->_("#UT#Skip Globalese pre-translation");?>',
            username:'<?php echo $this->translate->_("#UT#Username");?>',
            password:'<?php echo $this->translate->_("#UT#Password");?>',
            wizardTitle:'<?php echo $this->translate->_("#UT#Globalese authentication");?>',
        }
    });
    
    Ext.define("Editor.locale.plugins.GlobalesePreTranslation.view.GlobaleseSetting", {
        override: "Editor.plugins.GlobalesePreTranslation.view.GlobaleseSetting",
        strings: {
            wizardTitle:'<?php echo $this->translate->_("#UT#Globalese settings");?>',
            groupComboLabel:'<?php echo $this->translate->_("#UT#Globalese group");?>',
            engineComboLabel:'<?php echo $this->translate->_("#UT#Globalese engine");?>',
            emptyComboText:'<?php echo $this->translate->_("#UT#-- Please select --");?>',
        }
    });
    
    Ext.define("Editor.locale.plugins.GlobalesePreTranslation.view.GlobaleseAuthViewController", {
        override: "Editor.plugins.GlobalesePreTranslation.view.GlobaleseAuthViewController",
        strings: {
            noEnginesFoundMsg:'<?php echo $this->translate->_("#UT#No Globalese translation engine for the current language combination available for your username. Please change the username or skip Globalese pre-translation.");?>',
            noGroupsFoundMsg:'<?php echo $this->translate->_("#UT#No groups found for curren user.");?>',
            groupsErrorMsg:'<?php echo $this->translate->_("#UT#Globalese username and password combination is not valid.");?>',
            enginesErrorMsg:'<?php echo $this->translate->_("#UT#Error on engines search.");?>',
        }
    });
});