<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2017 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3.0 requirements will be met:
 http://www.gnu.org/licenses/agpl.html
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3
			 http://www.gnu.org/licenses/agpl.html

END LICENSE AND COPYRIGHT
*/

?>
    <div class="main">
    <h1>Download translate5 installation package</h1>
        <p>
            Please read carefully the GNU AFFERO GENERAL PUBLIC LICENSE Version&nbsp;3 (AGPLv3) for translate5
        </p>
        <iframe src="http://www.translate5.net/agpl3-license.txt" width="600px">
            <p>Your browser does not support iframes.</p>
          </iframe>
          <?php
          echo $this->form;
?>          
    </div>
    <div class="clear">&nbsp;</div>