<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2017 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html
  
 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or 
 plugin-exception.txt in the root folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/**#@+
 * @author Marc Mittag
 * @package portal
 * @version 2.0
 *
 */

$this->render('general.phtml');

$params = [        
        'task' => $this->task->getDataObject(),
        'header' => $this->header,
        'footer' => $this->footer,
        'wordCount' => $this->task->getWordCount() > 0 ? $this->task->getWordCount() : '-',
];

//get languages:
$lang = ZfExtended_Factory::get('editor_Models_Languages');
/* @var $lang editor_Models_Languages */

try {
    $lang->load($this->task->getSourceLang());
    $params['sourceLanguageTranslated'] = $this->translate->_($lang->getLangName());
}
catch (Exception $e) {
    $params['sourceLanguageTranslated'] = 'unknown';
}
try {
    $lang->load($this->task->getTargetLang());
    $params['targetLanguageTranslated'] = $this->translate->_($lang->getLangName());
}
catch (Exception $e) {
    $params['targetLanguageTranslated'] = 'unknown';
}

$relais = $this->task->getRelaisLang();
if(!empty($relais)) {
    try {
        $lang->load($this->task->getRelaisLang());
        $params['relaisLanguageTranslated'] = $this->translate->_($lang->getLangName());
    }
    catch (Exception $e) {
        $params['relaisLanguageTranslated'] = 'unknown';
    }
    $params['relaisLanguageFragment'] = $this->translate->_('<b>Relaissprache:</b> {relaisLanguageTranslated}<br />');
}
else {
    $params['relaisLanguageFragment'] = '';
}

$this->subject = $this->translate->_('Translate5 - Aufgabe zugewiesen').' "'.$this->task->getTaskNr().' - '.$this->task->getTaskName().'"';

if(empty($this->proofreaders)) {
    $params['proofreadersFragment'] = '';
}
else {
    //FIXME fill with proofreaders if needed
    $params['proofreadersFragment'] = '';
}

$mailBody = $this->templateApply($this->translate->_('{header}

Im Projektportal {portalLink} wurde Ihnen die Aufgabe <b>{task.taskNr} - {task.taskName}</b> zugewiesen.<br />
<br />
<b>Aufgabe:</b> {task.taskName}<br />
<b>Quellsprache:</b> {sourceLanguageTranslated}<br />
<b>Zielsprache:</b> {targetLanguageTranslated}<br />
{relaisLanguageFragment}<b>Lieferdatum:</b> {task.targetDeliveryDate}<br />
<b>Wortanzahl:</b> {wordCount}<br />
{proofreadersFragment}{footer}'),$params);

$this->textbody = strip_tags($mailBody);
echo $mailBody;

