<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2017 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html
  
 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or 
 plugin-exception.txt in the root folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/* @var $this Zend_View */
?>
  
Editor.controller.Localizer.addPluginInit('Customer', function() {
    
    Ext.define("Editor.locale.plugins.Customer.controller.Customer", {
        override: "Editor.plugins.Customer.controller.Customer",
        strings: {
            customer:'<?php echo $this->translate->_("Kunden");?>',
        }
    });


    Ext.define("Editor.locale.plugins.Customer.view.Customer", {
        override: "Editor.plugins.Customer.view.Customer",
        title:'<?php echo $this->translate->_("Kundenübersicht");?>',
        strings: {
            addCustomer:'<?php echo $this->translate->_("Hinzufügen");?>',
            refreshCustomer:'<?php echo $this->translate->_("Aktualisieren");?>',
            customerName:'<?php echo $this->translate->_("Kundenname");?>',
            customerNumber:'<?php echo $this->translate->_("Kundennummer");?>',
            save:'<?php echo $this->translate->_("Speichern");?>',
            cancel:'<?php echo $this->translate->_("Abbrechen");?>',
            remove:'<?php echo $this->translate->_("Löschen");?>',
            editCustomerTitle:'<?php echo $this->translate->_("Kunde bearbeiten");?>',
            addCustomerTitle:'<?php echo $this->translate->_("Kunde hinzufügen");?>',
            saveCustomerMsg:'<?php echo $this->translate->_("Kunde wird gespeichert...");?>',
            customerSavedMsg:'<?php echo $this->translate->_("Kunde gespeichert!");?>',
            customerDeleteMsg:'<?php echo $this->translate->_("Diesen Kunden löschen?");?>',
            customerDeleteTitle:'<?php echo $this->translate->_("Kunden löschen");?>',
            customerDeletedMsg:'<?php echo $this->translate->_("Kunde gelöscht");?>'
        }
    });

    Ext.define("Editor.locale.plugins.Customer.view.CustomerTagField", {
        override: "Editor.plugins.Customer.view.CustomerTagField",
        fieldLabel:'<?php echo $this->translate->_("Endkunde");?>'
    });
});