<?php
/*
START LICENSE AND COPYRIGHT

 Copyright (c) 2013 - 2017 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file is part of a plug-in for translate5.
 translate5 can be optained via the instructions that are linked at http://www.translate5.net
 For the license of translate5 itself please see http://www.translate5.net/license.txt
 For the license of this plug-in, please see below.
 
 This file is part of a plug-in for translate5 and may be used under the terms of the
 GNU GENERAL PUBLIC LICENSE version 3 as published by the Free Software Foundation and
 appearing in the file gpl3-license.txt included in the packaging of the translate5 plug-in
 to which this file belongs. Please review the following information to ensure the
 GNU GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/gpl.html
   
 There is a plugin exception available for use with this release of translate5 for
 translate5 plug-ins that are distributed under GNU GENERAL PUBLIC LICENSE version 3:
 Please see http://www.translate5.net/plugin-exception.txt or plugin-exception.txt in the
 root folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU GENERAL PUBLIC LICENSE version 3 with plugin-execption
             http://www.gnu.org/licenses/gpl.html
             http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/* @var $this Zend_View */
?>

Editor.controller.Localizer.addPluginInit('okapi', function() {

    /** @class okapi_l18n */
    Ext.define("Editor.locale.plugins.Okapi.view.filter.BConfGrid", {
        override: "Editor.plugins.Okapi.view.filter.BConfGrid",
        title: `<?php echo $this->translate->_('Dateiformatkonvertierung'); ?>`,
        text_cols: {
            name: `<?php echo $this->translate->_('Name'); ?>`,
            extensions: `<?php echo $this->translate->_('Erweiterungen'); ?>`,
            description: `<?php echo $this->translate->_('Beschreibung'); ?>`,
            action: `<?php echo $this->translate->_('Aktionen'); ?>`,
            uploadBconf: `<?php echo $this->translate->_('Bconf hochladen...'); ?>`,
            srx: `<?php echo $this->translate->_('SRX-Datei'); ?>`,
            pipeline: `<?php echo $this->translate->_('Pipeline'); ?>`,
        },
        strings: {
            edit: `'<?php echo $this->translate->_('Bearbeiten'); ?>`,
            remove: `<?php echo $this->translate->_('Löschen'); ?>`,
            copy: `<?php echo $this->translate->_('Kopieren'); ?>`,
            upload: `<?php echo $this->translate->_('Hochladen'); ?>`,
            addBconf: `<?php echo $this->translate->_('Bconf hinzufügen'); ?>`,
            uploadBconf: `<?php echo $this->translate->_('Bconf hochladen...'); ?>`,
            searchText: `<?php echo $this->translate->_('Suchen'); ?>`,
            searchEmptyText: `<?php echo $this->translate->_('Suchen'); ?>`,
            export: `<?php echo $this->translate->_('Exportieren'); ?>`,
            browse: `<?php echo $this->translate->_('Durchsuchen...'); ?>'`,
            bconfRequired: `<?php echo $this->translate->_('wird benötigt'); ?>`
        },

    });
});
