<?php
/*
 START LICENSE AND COPYRIGHT

 This file is part of translate5

 Copyright (c) 2013 - 2022 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt
 included in the packaging of this file.  Please review the following information
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html

 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or
 plugin-exception.txt in the root folder of translate5.

 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
 		     http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

 END LICENSE AND COPYRIGHT
 */

/* @var $this ZfExtended_View */

?>

Editor.controller.Localizer.addPluginInit('okapi', function(){
    Ext.define('Editor.locale.plugins.Okapi.view.BconfGrid', {
        override: 'Editor.plugins.Okapi.view.BconfGrid',
        title: '<?php echo $this->translate->_('Dateiformat- und Segmentierungseinstellungen'); ?>',
        text_cols: {
            name: '<?php echo $this->translate->_('Name'); ?>',
            extensions: '<?php echo $this->translate->_('Geänderte Filter'); ?>',
            extensionsTooltip: '<?php echo $this->translate->_('Dateitypen, für die Filter angepasst wurden'); ?>',
            description: '<?php echo $this->translate->_('Beschreibung'); ?>',
            standard: '<?php echo $this->translate->_('Standard'); ?>',
            standardTooltip: '<?php echo $this->translate->_('Standardmäßig bei der Projekterstellung ausgewähltes Filterset insofern nicht auf Kundenebene überschrieben'); ?>',
            customerStandard: '<?php echo $this->translate->_('Kundenstandard'); ?>',
            customerStandardTooltip: '<?php echo $this->translate->_('Standardmäßig bei der Projekterstellung ausgewähltes Filterset für diesen Kunden'); ?>',
            filters: '<?php echo $this->translate->_('Filter'); ?>',
            filtersTooltip: '<?php echo $this->translate->_('Anpassen von Dateifiltern in diesem Filterset'); ?>',
            action: '<?php echo $this->translate->_('Aktionen'); ?>',
            actionDelete: '<?php echo $this->translate->_('Filterset löschen'); ?>',
            actionClone: '<?php echo $this->translate->_('Filterset klonen'); ?>',
            actionDownload: '<?php echo $this->translate->_('Filterset als bconf-Datei herunterladen'); ?>',
            sourceSrx: '<?php echo $this->translate->_('Source SRX'); ?>',
            sourceSrxTooltip: '<?php echo $this->translate->_('SRX-Datei, die die Segmentierungsregeln für die Quelle enthält'); ?>',
            sourceSrxUpTooltip: '<?php echo $this->translate->_('Quell SRX-Datei hochladen und SRX-Regeln dieses Filtersatzes ersetzen'); ?>',
            sourceSrxDownTooltip: '<?php echo $this->translate->_('Laden Sie die Quell SRX-Datei herunter'); ?>',
            targetSrx: '<?php echo $this->translate->_('Target SRX'); ?>',
            targetSrxTooltip: '<?php echo $this->translate->_('SRX-Datei, die Segmentierungsregeln enthält, die zur weiteren Segmentierung des targets von xliff-Dateien verwendet werden können'); ?>',
            targetSrxUpTooltip: '<?php echo $this->translate->_('Hochladen der target-SRX-Datei'); ?>',
            targetSrxDownTooltip: '<?php echo $this->translate->_('Herunterladen der target-SRX-Datei'); ?>',
            uploadBconf: '<?php echo $this->translate->_('Bconf hochladen'); ?>',
            fileSuffix: '<?php echo $this->translate->_('-Datei'); ?>',
            srx: '<?php echo $this->translate->_('SRX-Datei'); ?>',
            pipeline: '<?php echo $this->translate->_('Pipeline'); ?>'
        },
        strings: {
            title: '<?php echo $this->translate->_('Dateiformat- und Segmentierungseinstellungen'); ?>',
            addBconf: '<?php echo $this->translate->_('Bconf hinzufügen'); ?>',
            bconfRequired: '<?php echo $this->translate->_('wird benötigt'); ?>',
            browse: '<?php echo $this->translate->_('Durchsuchen...'); ?>',
            supprtedFormats: '<?php echo $this->translate->_('Unterstützte Dateiformate'); ?>',
            confirmDeleteMessage: '<?php echo $this->translate->_('Möchten Sie diese Bconf-Datei wirklich löschen?'); ?>',
            confirmDeleteTitle: '<?php echo $this->translate->_('Bconf löschen'); ?>',
            deleteSuccess: '<?php echo $this->translate->_('Bconf-Datei gelöscht'); ?>',
            edit: '<?php echo $this->translate->_('Bearbeiten'); ?>',
            editBconf: '<?php echo $this->translate->_('Bconf-Datei bearbeiten'); ?>',
            fileUploaded: '<?php echo $this->translate->_('{0}-Datei erfolgreich hochgeladen.'); ?>',
            invalidMsg: '<?php echo $this->translate->_('Die hochgeladene Datei ist keine gültige {0}-Datei.'); ?>',
            invalidTitle: '<?php echo $this->translate->_('Ungültige {0}-Datei'); ?>',
            name: '<?php echo $this->translate->_('Name'); ?>',
            nameExists: '<?php echo $this->translate->_('Dieser Name ist schon vergeben'); ?>',
            newBconf: '<?php echo $this->translate->_('Neue Bconf-Datei'); ?>',
            refresh: '<?php echo $this->translate->_('Aktualisieren'); ?>',
            searchEmptyText: '<?php echo $this->translate->_('Suchen'); ?>',
            titleLong: '<?php echo $this->translate->_('Dateiformat- und Segmentierungseinstellungen'); ?>',
            uniqueName: '<?php echo $this->translate->_('Eindeutiger Name'); ?>',
            upload: '<?php echo $this->translate->_('Hochladen'); ?>',
            uploadBconf: '<?php echo $this->translate->_('Bconf hochladen'); ?>',
            supportetFormats: '<?php echo $this->translate->_('Unterstützte Dateiformate'); ?>'
        }
    });
    Ext.define('Editor.locale.plugins.Okapi.view.BconfFilterGrid', {
        override: 'Editor.plugins.Okapi.view.BconfFilterGrid',
        text_cols: {
            name: '<?php echo $this->translate->_('Name'); ?>',
            extensions: '<?php echo $this->translate->_('Dateitypen'); ?>',
            description: '<?php echo $this->translate->_('Beschreibung'); ?>',
            mime: '<?php echo $this->translate->_('MIME-Typ'); ?>',
            identifier: '<?php echo $this->translate->_('Kennung'); ?>',
            actions: '<?php echo $this->translate->_('Aktionen'); ?>'
        },
        strings: {
            title: '<?php echo $this->translate->_('Filter in'); ?>',
            configuration: '<?php echo $this->translate->_('Filter konfigurieren'); ?>',
            showDefaultFilters: '<?php echo $this->translate->_('Standard Filter anzeigen'); ?>',
            hideDefaultFilters: '<?php echo $this->translate->_('Standard Filter verstecken'); ?>',
            editTexts: '<?php echo $this->translate->_('Filternamen, zugehörige Dateierweiterungen, MIME-Typ und Beschreibung bearbeiten'); ?>',
            editTextsRowTip: '<?php echo $this->translate->_('Doppelklicken zum bearbeiten'); ?>',
            clone: '<?php echo $this->translate->_('Filter klonen'); ?>',
            refresh: '<?php echo $this->translate->_('Aktualisieren'); ?>',
            remove: '<?php echo $this->translate->_('Löschen'); ?>',
            emptySearch: '<?php echo $this->translate->_('Filter suchen'); ?>',
            uniqueName: '<?php echo $this->translate->_('Eindeutiger Name'); ?>'
        }
    });
    Ext.define('Editor.locale.plugins.Okapi.view.BconfFilterRowEditing', {
        override: 'Editor.plugins.Okapi.view.BconfFilterRowEditing',
        strings: {
            infosMissing: '<?php echo $this->translate->_('Informationen fehlen'); ?>',
            nameMustBeChanged: '<?php echo $this->translate->_('Der ursprüngliche Name muss verändert werden'); ?>',
            nameMustBeSupplied: '<?php echo $this->translate->_('Es muss ein endeutiger Name angegeben werden'); ?>',
            nameMustNotBeLikeT5: '<?php echo $this->translate->_('Der Name darf nicht den Begriff "translate5" enthalten'); ?>',
            extensionMustBeSupplied: '<?php echo $this->translate->_('Es muss mindestens ein Dateityp angegeben werden'); ?>'
        }
    });
    Ext.define('Editor.locale.plugins.Okapi.view.FprmEditor', {
        override: 'Editor.plugins.Okapi.view.FprmEditor',
        strings: {
            title: '<?php echo $this->translate->_('Bearbeite Filter Typ {0} von Bconf {1}'); ?>',
            help: '<?php echo $this->translate->_('OKAPI Hilfe'); ?>',
            helpTooltip: '<?php echo $this->translate->_('Das Okapi Framework wird auf der Serverseite für Dateikonvertierungen verwendet'); ?>',
            save: '<?php echo $this->translate->_('Speichern'); ?>',
            cancel: '<?php echo $this->translate->_('Abbrechen'); ?>',
            reset: '<?php echo $this->translate->_('Änderungen zurücksetzen'); ?>',
            invalidTitle: '<?php echo $this->translate->_('Bearbeitung fehlerhaft'); ?>',
            invalidField: '<?php echo $this->translate->_('Feld "{0}" vom Typ "{1}" ist nicht valide'); ?>',
            float: '<?php echo $this->translate->_('Gleitkommazahl'); ?>',
            boolean : '<?php echo $this->translate->_('Boolscher Wert'); ?>',
            integer : '<?php echo $this->translate->_('Ganzzahl'); ?>',
            validationFailed: '<?php echo $this->translate->_('Ihre Änderungen sind nicht valide'); ?>',
            changesInvalid: '<?php echo $this->translate->_('Ihre Änderungen sind nicht valide, daher konnte der Filter nicht gespeichert werden'); ?>',
            successfullySaved: '<?php echo $this->translate->_('Filter wurde erfolgreich gespeichert'); ?>'
        }
    });
});