<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2017 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html
  
 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or 
 plugin-exception.txt in the root folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/**#@+
 * @author Marc Mittag
 * @package trantlate5
 * @version 0.7
 *
 */
$session = new Zend_Session_Namespace();

/**
 * Render a single entry of the supporters list.
 * @param string $link
 * @param string $name
 * @param string $image
 * @param integer $width
 * @param integer $height
 * @param boolean $clear
 */
function renderSupporterEntrySite($link, $name, $image, $width, $height, $clear = FALSE) {
    $template = '<a href="%s" class="crowdlink" style="width: %s; %s" target="_blank" title="%s"><img src="'.APPLICATION_RUNDIR.'/images/supporter2018/%s" width="%d" height="%d" alt="%s" /></a>'."\n";
    $name = str_replace('"','&quot;', $name);
    $cssWidth = round(100 * $width / 1150, 5).'%';
    $cssClear = ($clear) ? 'clear: left;' : '';
    
    return sprintf($template, $link, $cssWidth, $cssClear, $name, $image, $width, $height, $name);
};

?>
<article class="post">
    <header>
        <div class="title"><h2>Crowd of companies</h2></div>
        <div class="meta">
                    <time class="published" datetime="2015-08-21">June 01, 2018</time>
                    <a href="http://www.mittagqi.com/en/welcome/about-marc-mittag" target="_blank" class="author"><span class="name">Marc Mittag</span><img src="/images/Marc-Mittag.jpg" alt="Marc Mittag" /></a>
            </div>
    </header>
    <h2>Being flexible &amp; master of your processes</h2>
    <p>Many companies wish, they would be able to develop their own software:</p>
    <ul><li>For optimal adjustment to their customers needs</li>
        <li>For being able to serve the best quality</li>
        <li>and for optimizing their productivity.</li></ul>
    <p>Yet for many this is not possible due to resources.</p>
    <p><strong>The goal of the translate5 project is enable companies to fulfill those needs.<br>And jointly build and maintain that system with the power of the crowd.</strong></p>
    <h2>Building a crowd of companies</h2>
    
    <p>Through <a href="#crowdfunding">a crowdfunding (see below)</a> translate5 reached the state, that it can serve as a cloud translation tool (in addition to being a review tool since 2012).</p>
    <p>Thus the next phase started to bring translate5 as a cloud and community-based translation system into existence: <strong>Building a crowd of companies, that commit to start using translate5 as a translation tool in daily business.</strong> And together complete, what still is needed.</p>
    <p>By joining the crowd of companies you can help to pave the way for a wide spread use of a tool, that</p>
        <ul><li>you can extend and integrate as you need it</li>
            <li>allows as many users as you want</li>
            <li>and allows to set and propagate open standards in the industry.</li></ul>
        
    
    <h2>Joining the crowd of companies</h2>
    <p><strong><a href="mailto:support@translate5.net">So contact us if you would like to see that happen</a>.</strong></p>
    <p>The model for joining is quite simple:</p>
    <ul><li>You support translate5 by funding 10 hours of work/month.</li>
        <li>You get what you need for it from translate5's development team
            <ul>
                <li>Consulting</li>
                <li>Training</li>
                <li>Maintenance</li>
                <li>Development</li>
                <li>Fixes</li>
                <li>or other services around translate5</li>
            </ul>
        </li>
        <li>Hours you do not need are accumulated and you decide, where to invest them into development.</li>
    </ul>
    <p>Companies of the crowd optionally also support each other with tasks like providing documentation, discussing best practice processes or introducing translate5 to translators and other companies.</p>
    <p><strong>translate5's development is backed and lead by MittagQI, a company of software professionals absolutely dedicated to <a href="https://www.fsf.org/about/what-is-free-software" target="_blank">the principles of free software</a>. Our aim is to enable you to own your own software.</strong></p>
</article>
<article class="post" id="crowdfunding">
    <header>
        <div class="title"><h2>Crowdfunding for an Open Source translation system</h2></div>
    </header>
    <p>From 2015 to 2017 a crowdfunding collected altogether €61.500,-- in three phases with 17 companies participating.</p>
    <p>The money was used to build a cloud translation tool based on already existing components:</p>
    <ul>
                <li>The cloud review platform translate5</li>
                <li><a href="http://community.opentm2.org" target="_blank">The desktop translation tool OpenTM2</a></li>
                <li><a href="http://www.statmt.org/moses/" target="_blank">Moses Machine Translation</a></li>
            </ul>
    <p>The result is the current translate5 system with its integrations. Of course completed by many more features that have been build into translate5 since 2015 (and before since 2012).</p>
    <p>The following companies supported the crowdfunding and/or funded additional features &mdash; thank you very much!!!</p>
    <div class="crowdlinks_container">
        <?php
            echo renderSupporterEntrySite('https://www.beo-doc.de', 'beo Gesellschaft für Sprachen und Technologie mbH', 'beo.png', 285, 150);
            echo renderSupporterEntrySite('https://www.itl.eu', 'itl Institut für technische Literatur AG', 'itl.png', 220, 150);
            echo renderSupporterEntrySite('https://www.supertext.ch', 'Supertext AG', 'supertext.png', 250, 150);
            echo renderSupporterEntrySite('https://www.oneword.de', 'oneword GmbH', 'oneword.png', 395, 150);
            ?>
    	<div style="clear:both;">
        <?php
            
            echo renderSupporterEntrySite('https://www.worldtranslation.com', 'Worldtranslation is your professional language service provider', 'worldtranslation.png', 380, 150);
            echo renderSupporterEntrySite('https://www.schmieder-uebersetzungen.de', 'Schmieder Übersetzungen &amp; Sprachmanagement', 'schmieder.png', 400, 150);
            echo renderSupporterEntrySite('https://www.transline.de', 'Transline. Übersetzen. Verstehen.', 'transline.png', 370, 150);
        ?>
        </div>
        <?php 
            
            echo renderSupporterEntrySite('https://www.dfki.de/web', 'DFKI Deutsches Forschungszentrum für Künstliche Intelligenz GmbH', 'dfki.png', 310, 150, TRUE);
            echo renderSupporterEntrySite('https://soluzione.de', 'soluzione Script GmbH', 'soluzione.png', 240, 150);
            echo renderSupporterEntrySite('https://www.pangeanic.com', 'Pangeanic', 'pangeanic.png', 310, 150);
            echo renderSupporterEntrySite('https://lexitech.com', 'Lexitech', 'lexitech.png', 290, 150);
            
            echo renderSupporterEntrySite('https://www.mt-g.eu', 'mt-g medical translation GmbH & Co. KG', 'mt-g.png', 255, 150, TRUE);
            echo renderSupporterEntrySite('http://www.globalese-mt.com', 'Globalese MorphoLogic Localisation Ltd.', 'globalese.png', 230, 150);
            echo renderSupporterEntrySite('http://www.lucysoftware.com', 'Lucy Software and Services GmbH', 'lucy.png', 200, 150);
            echo renderSupporterEntrySite('https://www.locasoft.com', 'LocaSoft GmbH', 'locasoft.png', 200, 150);
            echo renderSupporterEntrySite('http://www.iolar.com', 'Iolar', 'iolar.png', 265, 150);
            
            echo renderSupporterEntrySite('https://www.smartspokes.com', 'SMARTSPOKES AG', 'smartspokes.png', 250, 145, TRUE);
            echo renderSupporterEntrySite('http://www.yavaway.com', 'Yavaway Translation', 'yavaway.png', 180, 145);
            echo renderSupporterEntrySite('http://www.translationprojex.com', 'TranslationProjex', 'translationprojex.png', 210, 145);
            echo renderSupporterEntrySite('https://www.swissglobal.ch', 'SwissGlobal Language Services AG', 'swissglobal.png', 240, 145);
            echo renderSupporterEntrySite('https://www.textform.com', 'text&amp;form GmbH', 'textform.png', 270, 145);
        ?>
    </div>
</article>