<?php
 /*
 START LICENSE AND COPYRIGHT
 
 This file is part of Translate5 Editor PHP Serverside and build on Zend Framework
 
 Copyright (c) 2013 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ÄTT) MittagQI.com

 This file may be used under the terms of the GNU General Public License version 3.0
 as published by the Free Software Foundation and appearing in the file gpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU General Public License version 3.0 requirements will be met:
 http://www.gnu.org/copyleft/gpl.html.

 For this file you are allowed to make use of the same FLOSS exceptions to the GNU 
 General Public License version 3.0 as specified by Sencha for Ext Js. 
 Please be aware, that Marc Mittag / MittagQI take no warranty  for any legal issue, 
 that may arise, if you use these FLOSS exceptions and recommend  to stick to GPL 3. 
 For further information regarding this topic please see the attached license.txt
 of this software package.
 
 MittagQI would be open to release translate5 under EPL or LGPL also, if this could be
 brought in accordance with the ExtJs license scheme. You are welcome to support us
 with legal support, if you are interested in this.
 
 
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU General Public License version 3.0 http://www.gnu.org/copyleft/gpl.html
             with FLOSS exceptions (see floss-exception.txt and ux-exception.txt at the root level)
 
 END LICENSE AND COPYRIGHT 
 */

/**#@+
 * @author Marc Mittag
 * @package trantlate5
 * @version 0.7
 *
 */
?>
<div class="main">
<h1>Information for developers</h1>
    <p><a href="http://confluence.translate5.net/" target="_blank">translate5 Confluence</a> is where translate5 developers and users collaborate and share knowledge. </p>
    <p>In <a href="http://confluence.translate5.net/" target="_blank">translate5 Confluence</a> you'll find a lot of developing related information about translate5.</p>
    <p>translate5 source code is <a href="#source">published at bitbucket</a>.</p>
    <h2>translate5 Confluence spaces for developers</h2>
    <ul><li><a href="http://confluence.translate5.net/display/TAD" target="_blank">Architecture documentation</a></li>
    <li><a href="http://confluence.translate5.net/display/CON" target="_blank">Configuration</a></li>
        <li><a href="http://confluence.translate5.net/display/TPLO" target="_blank">Plug-in overview</a></li>
    </ul>

    
    <h2>Contribute to the development</h2>
    <p>translate5 project welcomes your contributions to the development on the level you like:</p>
    <ul>
        <li>Report bugs</li>
        <li>Propose features</li>
        <li>Fix bugs</li>
        <li>Develop plug-ins</li>
        <li>Contribute to core development</li>
    </ul>
    <h4>translate5 JIRA - report bugs and propose features</h4>
    <p>To report a bug or propose a feature, you need to log into <a href="http://jira.translate5.net/" target="_blank">translate5 JIRA</a>.</p>
    <p>If you want to report a bug, please be sure you really encountered a one. In case of any doubt, ask about it in <a href="https://groups.yahoo.com/neo/groups/translate5/info" target="_blank">translate5 Yahoo mailing list</a>.</p>
    <p>If you want to propose a feature, please be sure, your feature proposal is not already registered as a feature request in <a href="http://jira.translate5.net/" target="_blank">translate5 JIRA</a>. If it is already registered, please comment on the feature and/or vote for it.</p>
    <h4>Be part of the development</h4>
    <p>translate5 project is happy to have you as part of the development. Please write to <a href="mailto:support@translate5.net">support@translate5.net</a> and we will open an account in <a href="#source">translate5 code repository</a> for you.</p>
    <p><strong>The easiest way to contribute to translate5 development is to develop a translate5 plug-in, though.</strong> This can be done completely independent of translate5 core development. Plug-ins can be documented and uploaded to <a href="http://confluence.translate5.net/display/TPLO" target="_blank">translate5 plug-in directory</a>.</p>
    <p>How to develop a translate5 plug-in is documented in <a href="http://confluence.translate5.net/display/TAD" target="_blank">translate5 architecture documentation</a></p>
    <a name="source"></a><h4>translate5 source code</h4>
    <p>The current stable master branch of translate5 is <a href="https://bitbucket.org/mittagqi" target="_blank">published on bitbucket</a>.</p>
    <p>It is updated every night with the latest commits.</p>
    <p>For installation and update purposes we recommend the <a href="http://confluence.translate5.net/display/TIU" target="_blank">translate5 install &amp; update routines</a>, though. They build on packages provided by translate5 development team on a weekly basis.</p>
    
    <h2>Post questions in translate5 Yahoo mailing list</h2>
    <p><b>Before you ask a question at <a href="https://groups.yahoo.com/neo/groups/translate5/info" target="_blank">translate5 Yahoo mailing list</a>:</b></p>
    <p>Please check carefully:</p>
    <ul>
        <li>Is my question answered in <a href="http://confluence.translate5.net/" target="_blank">translate5 Confluence</a>?</li>
        <li>Has my question already been asked in the <a href="https://groups.yahoo.com/neo/groups/translate5/info" target="_blank">translate5 Yahoo mailing list</a>?</li>
    </ul>
</div>
<div class="clear">&nbsp;</div>
