<?php
 /*
 START LICENSE AND COPYRIGHT
 
 This file is part of Translate5 Editor PHP Serverside and build on Zend Framework
 
 Copyright (c) 2013 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ÄTT) MittagQI.com

 This file may be used under the terms of the GNU General Public License version 3.0
 as published by the Free Software Foundation and appearing in the file gpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU General Public License version 3.0 requirements will be met:
 http://www.gnu.org/copyleft/gpl.html.

 For this file you are allowed to make use of the same FLOSS exceptions to the GNU 
 General Public License version 3.0 as specified by Sencha for Ext Js. 
 Please be aware, that Marc Mittag / MittagQI take no warranty  for any legal issue, 
 that may arise, if you use these FLOSS exceptions and recommend  to stick to GPL 3. 
 For further information regarding this topic please see the attached license.txt
 of this software package.
 
 MittagQI would be open to release translate5 under EPL or LGPL also, if this could be
 brought in accordance with the ExtJs license scheme. You are welcome to support us
 with legal support, if you are interested in this.
 
 
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU General Public License version 3.0 http://www.gnu.org/copyleft/gpl.html
             with FLOSS exceptions (see floss-exception.txt and ux-exception.txt at the root level)
 
 END LICENSE AND COPYRIGHT 
 */

?>
    <h1>translate5 windows installer: Download and install it now!</h1>
    <div class="main">
        <p>
            In English language only.
        </p>
        <p>
The installer uses just 5MB - and you do not need any IT-knowledge to use it. 
Just a few clicks- and translate5 installer will load all needed components from the internet and install them for you. 
        </p>
        <p>
Since extending translate5 with your own plugins and upcoming community plugins is one of the strong points of 
translate5 (and true community Open Source in general), even external components integrated in translate5, 
like openTMStermTagger, can be handled by the installer.
        </p>
        <p>
            <a class="start-button" style="float:left;width:150px;margin-left:40px;" href="/downloads/translate5-1.0-windows-installer.exe" title="translate5-1.0-windows-installer.exe">Download executable package (.exe)</a>
            <a class="start-button" style="float:left;width:150px;margin-left:40px;" href="/downloads/UNZIP-BEFORE-INSTALL-translate5-1.0-windows-installer.zip" title="UNZIP-BEFORE-INSTALL-translate5-1.0-windows-installer.zip">Download zipped package (.zip)</a>
        </p>
    </div>
    <div class="clear">&nbsp;</div>