<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2017 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html
  
 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or 
 plugin-exception.txt in the root folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/**#@+
 * @author Marc Mittag
 * @package trantlate5
 * @version 0.7
 *
 */
?>
<article class="post">
    <header>
        <div class="title"><h2>Extend with powerful plug-ins</h2></div>
    </header>
    <p><strong>The plug-in mechanism of translate5 allows to build extremly powerful functionality as plug-ins</strong>.</p> 
    <p>As examples</p>
    <ul>
        <li><strong><a href="/index/outstanding-features#visualReview">VisualReview (Review in perfect layout for most file formats)</a></strong></li>
        <li><strong><a href="/index/outstanding-features#trackChanges">MS-Word-style inline TrackChanges</a></strong></li>
        <li><strong><a href="/index/outstanding-features#tm-mt-integration">The integration of Translation Memory and MT systems</a></strong></li>
    </ul>
    <p>are all build as translate5 plug-ins &mdash; but interact seemlessly with the entire application.</p>
    <p><strong>Extending translate5 with plug-ins is the way to go for new functionality</strong>. They:</p>
     <ul>
        <li><strong><a href="#modularity">Allow modularity of the system</a></strong></li>
        <li><strong><a href="#private">Allow to keep your functionality private</a></strong></li>
        <li><strong><a href="#sell">Allow to sell your functionality</a></strong></li>
    </ul>
    <img src="/images/cloud-api-technology-large.png" style="width: 100%">
    <a name="modularity"></a><br><br><a name="private"></a>
    <h2>Plug-ins: Modularity of the system</h2>
    <p>Plug-ins allow everyone to extend translate5, without the need to change the core of the system.</p>
    <p>This frees plug-in developers of the need to let every line of code being approved by the core development team, that has the duty to ensure the stability of the system.</p>
    <p>And it allows functionality in translate5 to be easily switched on and off when needed. <a href="https://confluence.translate5.net/display/TFD/Plug-in+system" target="_blank">For more information about translate5's plug-in system visit translate5's Confluence</a>.</p>
    <a name="sell"></a>
    <h2>Keep your functionality private</h2>
    <p>translate5's core and core plug-ins are under AGPL3 license.</p>
    <p>In short terms: AGPL3 commits every company that uses a cloud application to tell its users, where they can find the source code of the application. Thus all changes of third parties to translate5's core code must be made public.</p>
    <p><strong>That is different for translate5's plug-ins:</strong> translate5's plug-in exception allows you to freely choose between the Open Source GPL3 license and the Open Source AGPL3 license. GPL3 allows you to run a the software on a cloud server without passing the server side code to the users of the cloud.</p>
    <p>Therefore you can extend translate5 with functionality private to your company and keep the plug-in for yourself.</p>
 <h2>Sell your functionality</h2>
 <p>AGPL3 and GPL3 are licenses published by the <a href="https://www.fsf.org/about/" target="_blank">Free Software Foundation</a>. They very strongly state, <a href="https://www.gnu.org/philosophy/selling.html" target="_blank">that it is a missunderstanding, that free software must or should be free of charge</a>. Instead, they encourage people <a href="https://www.gnu.org/philosophy/selling.html" target="_blank">to charge for free software</a>. As <a href="/index/mission">translate5's mission statement explains</a>, free software is about freedom.</p>
 <p>Thus the translate5 development team actively encourages companies to develop translate5 plug-ins and sell them (yet keep them under GPL3 or AGPL3 license, ensuring the software freedom).</p>
 <p><a href="http://www.mittagqi.com" target="_blank">MittagQI</a>&mdash; the company behind translate5's lead development team&mdash; uses the same mechanism to finance the development of complex plug-ins like <a href="/index/outstanding-features#visualReview">visualReview</a> and <a href="/index/outstanding-features#trackChanges">trackChanges</a>, that are reserved to companies contributing to translate5 <a href="/index/crowd-of-companies">in the frame of the "crowd of companies"</a>. </p>
</article>
