<?php
 /*
 START LICENSE AND COPYRIGHT
 
 This file is part of Translate5 Editor PHP Serverside and build on Zend Framework
 
 Copyright (c) 2013 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ÄTT) MittagQI.com

 This file may be used under the terms of the GNU General Public License version 3.0
 as published by the Free Software Foundation and appearing in the file gpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU General Public License version 3.0 requirements will be met:
 http://www.gnu.org/copyleft/gpl.html.

 For this file you are allowed to make use of the same FLOSS exceptions to the GNU 
 General Public License version 3.0 as specified by Sencha for Ext Js. 
 Please be aware, that Marc Mittag / MittagQI take no warranty  for any legal issue, 
 that may arise, if you use these FLOSS exceptions and recommend  to stick to GPL 3. 
 For further information regarding this topic please see the attached license.txt
 of this software package.
 
 MittagQI would be open to release translate5 under EPL or LGPL also, if this could be
 brought in accordance with the ExtJs license scheme. You are welcome to support us
 with legal support, if you are interested in this.
 
 
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU General Public License version 3.0 http://www.gnu.org/copyleft/gpl.html
             with FLOSS exceptions (see floss-exception.txt and ux-exception.txt at the root level)
 
 END LICENSE AND COPYRIGHT 
 */

/**#@+
 * @author Marc Mittag
 * @package trantlate5
 * @version 0.7
 *
 */
?>
<h1><?php echo $this->translate->_('translate5 - neues Projekt importieren'); ?></h1>
<div class="main">
<?php
if(count($this->form->getErrorMessages())>0){ ?>
    <h2 class="errors"><?php echo $this->translate->_('Fehler im Formular'); ?></h2>
    <ul class="errors">
    <?php
    foreach ($this->form->getErrorMessages() as $message) {
        ?><li><?php echo $message; ?></li><?php
    }
    ?>
    </ul>
    <?php
}
?>
<h2><?php echo $this->translate->_('Wichtiger Hinweis:'); ?></h2>
<ul class="important-notices">
    <li><?php echo $this->translate->_('Diese translate5 Demoversion ist öffentlich, alle hochgeladenen Projekte können von jedem eingesehen und exportiert werden!'); ?></li>
    <li><?php echo $this->translate->_('Momentan können Dateien im SDLXLIFF Format und Terminologie im TBX Format importiert werden.'); ?></li>
    <li><?php echo $this->translate->_('Damit die Terminologie anhand der TBX Daten ausgezeichnet werden kann, müssen die Quell- und Zielsprache entsprechend gesetzt werden.'); ?></li>
    <li><?php echo $this->translate->_('Bitte beachten Sie die <a href="/index/usage/#import">Bedienungshinweise zu den Import Einstellungen</a>.'); ?></li>
</ul>
<?php
    echo $this->form;
?>
<p><?php echo $this->translate->_('Je nach Größe und Umfang Ihrer Daten kann der Import einige Minuten dauern.'); ?></p>
</div>
<div class="sidebar">
<?php
    echo $this->render('index/testdataSidebar.phtml');
?>
    <div class="teaser">
        <h2><?php echo $this->translate->_('Hinweise zur Bedienung'); ?></h2>
        <ul>
            <li><a href="/index/usage/#import"><?php echo $this->translate->_('Projekt Import'); ?></a></li>
            <li><a href="/index/usage/#lektorat"><?php echo $this->translate->_('Lektorat'); ?></a></li>
        </ul>
    </div>
    <?php
    echo $this->render('index/betanotice.phtml');
    ?>
</div>
<div class="clear">&nbsp;</div>
<p><a href="/index/tasks">&#171; <?php echo $this->translate->_('zurück zur Übersicht'); ?></a></p>