<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2015 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3.0 requirements will be met:
 http://www.gnu.org/licenses/agpl.html

 There is a plugin exception available for use with this release of translate5 for
 open source applications that are distributed under a license other than AGPL:
 Please see Open Source License Exception for Development of Plugins for translate5
 http://www.translate5.net/plugin-exception.txt or as plugin-exception.txt in the root
 folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execptions
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/**#@+
 * @author Marc Mittag
 * @package trantlate5
 * @version 0.7
 *
 */
$session = new Zend_Session_Namespace();
?>
    <h3 style="margin-top: 0;">Integration of OpenTM2, translate5 and Moses coming soon:</h3>
    <h2 class="important" style="margin-top: 0px;">The crowdfunding successfully raised &euro;&nbsp;40.500,-- altogether :-)</h2>
    <p>A big thank you goes to all 12 companies supporting the crowdfunding phase 1 &amp; 2!!! And a special thank you to <a href="http://www.locasoft.com/" target="_blank">LocaSoft</a>, <a href="http://www.supertext.com/" target="_blank">Supertext</a>, <a href="http://www.oneword.de/" target="_blank">oneword</a>, <a href="http://www.mt-g.de/" target="_blank">mt-g</a> and <a href="http://www.beo-doc.de/" target="_blank">beo</a>, who at the end went the extra mile to make the success possible!</p>
    <p><strong>For the first time in translation industry</strong> a modern, cloud-based and community based Open Source translation system is approaching :-)</p>
    <p><strong>Unique:</strong> The system</p>
    <ul>
        <li>is fully Open Source</li>
        <li>is based on a growing community of small &amp; mid-sized companies</li>
        <li>is NOT produced by an LSP, but by independent Open Source developers</li>
        <li>is backed by LSPs, MT providers and TMS providers alike</li>
        <li>is modern, cloud-based, fast, easy extendable &amp; easy integratable</li>
    </ul>
    <p>
        <strong><a class="important" href="/login">Try it!</a></strong>
    </p>
    <p>Still there may be features, that need to be developed for your needs to use it. This gets easier with every company, that joins the community.</p>
    <p><strong><a href="/index/join" class="important">So join the community of companies</a> working together on Open Source and thus keeping their independence!</strong></p>
    <p>The major goal of the campaign is to join efforts in creating a modern community-based Open Source Translation system that meets the major needs of Language Service Providers.</p><br>
<h2>More about translate5 project</h2>

    <h3>translate5 mission</h3>
    <p>translate5 is Open Source software developed for the language industry through input and support of the language industry. Please read <a href="/index/mission">translate5 mission statement</a> for more information.</p>
    <h3>Engage in translate5</h3>
    <p>translate5 exists and is developed through its community - as <a href="/index/usage">user</a>, <a href="/index/join">developer</a> or <a href="/index/join">supporter of the development</a>. Be part of it.</p>
    <h3>Professional usage</h3>    
    <p>For professional usage, you can rely on <a href="http://www.mittagqi.com/" target="_blank">MittagQI (translate5 development lead)</a> as <a href="http://www.mittagqi.com/en/translate5/maintenance-contract" target="_blank">support</a> and/or <a href="http://www.mittagqi.com/en/translate5/installations-hosting" target="_blank">software as a service provider</a>. And maybe other companies in the future.</p>
    <h2>Have fun with translate5!</h2>
