<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2017 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html
  
 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or 
 plugin-exception.txt in the root folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/**#@+
 * @author Marc Mittag
 * @package trantlate5
 * @version 0.7
 *
 */
$session = new Zend_Session_Namespace();
?>
<article class="post">
<header>
    <div class="title"><h2>What's special about it:<br> Features &amp; Crowd of Companies</h2></div>
</header>
    <h2>Open Source approach &mdash; Crowd of companies</h2>
    <ul>
        <li>Fully Open Source</li>
        <li><a href="/index/crowd-of-companies">Crowd of companies: Controlled by the needs of its users</a></li>
        <li>Lead by independent  Open Source developers &mdash; <a href="http://www.mittagqi.com/" target="_blank">MittagQI</a></li>
        <li><a href="/index/crowd-of-companies#crowdfunding">Backed by LSPs, MT providers and industry companies alike</a></li>
        <li><a href="/index/support-the-project">Everyone can contribute</a></li>
    </ul>
    
    <p><strong>The only modern, cloud-based and community-driven Open Source translation system !</strong></p>
    
    <h2>Outstanding features</h2>
    <ul>
        <li><a href="/index/outstanding-features#performance">100.000 segments &amp; 1000 files per task possible</a></li>
        <li><a href="/index/outstanding-features#visualReview">VisualReview: Review in perfect layout for most file formats</a></li>
        <li><a href="/index/outstanding-features#trackChanges">Inline, MS-Word style track Changes</a></li>
        <li><a href="/index/outstanding-features#tm-mt-integration">You decide, which TM / MT-engine you want to integrate</a> (default OpenTM2 &amp; Moses)</li>
        <li><a href="/index/outstanding-features#term-portal">Terminology Portal</a> (mobile ready!)</li>
    </ul>
    <p>A complete bullet list of features <a href="https://confluence.translate5.net/display/TFD/Overview+of+features" target="_blank">can be found in translate5 Confluence</a>.</p>
    <h2>Most flexible integration options</h2>
    <ul>
        <li><a href="/index/integrate#REST">Every GUI-feature usable via REST-API</a></li>
        <li><a href="/index/integrate#editor-only">Editor-only integration possible</a></li>
        <li><a href="/index/extend">Very powerful plug-ins possible</a> (no need to change the core)</li>
        <li><a href="/index/integrate#integrated-resources">Integrates and builds upon multiple other Open Source tools</a></li>
    </ul>
    
    <p><strong>Its made for seemless integration into your companies processes !</strong></p>
    
    <p>
        <strong><a class="important button big" href="/login">Try it!</a></strong>
    </p>
</article>
