<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2015 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3.0 requirements will be met:
 http://www.gnu.org/licenses/agpl.html

 There is a plugin exception available for use with this release of translate5 for
 open source applications that are distributed under a license other than AGPL:
 Please see Open Source License Exception for Development of Plugins for translate5
 http://www.translate5.net/plugin-exception.txt or as plugin-exception.txt in the root
 folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execptions
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/**#@+
 * @author Marc Mittag
 * @package trantlate5
 * @version 0.7
 *
 */
$session = new Zend_Session_Namespace();
?>
<div class="main">
<h1>Welcome to translate5 project</h1>

    <h2>translate5 mission</h2>
    <p>translate5 is Open Source software, developed for the language industry through the input and support of the language industry. Please read <a href="/index/mission">translate5 mission statement</a> for more information.</p>
    <h2>Engage in translate5</h2>
    <p>translate5 exists and is developed through its community - as <a href="/index/usage">user</a>, <a href="/index/developer">developer</a> or supporter of the development. Be part of it.</p>
    <h2>Professional usage</h2>    
    <p>For professional usage you can rely on <a href="http://www.mittagqi.com/" target="_blank">MittagQI (translate5 development lead)</a> as <a href="http://www.mittagqi.com/en/translate5/maintenance-contract" target="_blank">support</a> and/or <a href="http://www.mittagqi.com/en/translate5/installations-hosting" target="_blank">software as a service provider</a>. And maybe other companies in the future.</p><br>
    <h2>Have fun with translate5!</h2>
</div>
<div class="sidebar">
    <div class="teaser">
        <h3>Main supporters</h3>
    <a href="http://www.beo-doc.de/" target="_blank"><img src="/images/supporters/beo-logo.jpg" style="width:100px;" alt="beo Gesellschaft für Sprachen und Technologie mbH"></a>
    <a href="http://www.dfki.de/" target="_blank"><img src="/images/supporters/dfki-logo.jpg"  style="width:150px;" alt="DFKI Deutsches Forschungszentrum für Künstliche Intelligenz GmbH"></a>
    <a href="http://www.mittagqi.com/" target="_blank"><img src="/images/supporters/mittagqi-logo.png"  style="width:100px;"></a>
    <a href="http://www.itl.eu/" target="_blank"><img src="/images/supporters/itl-logo.jpg"  style="width:100px;" alt="itl Institut für technische Literatur AG"></a>
     <h3>Supporters of selected features</h3>
     <a href="http://xtra-services.com/" target="_blank">XTRA Translation Services</a><br><br>
    <a href="http://www.textform.com/" target="_blank">text&amp;form</a><br><br>
    <a href="http://www.oneword.de/" target="_blank">oneword GmbH</a>
     <h3>Individual supporters</h3>
     <a href="http://www.mccosh.de/" target="_blank">Daniel Mc Cosh</a><br><br>
     Peter Bourgonje<br><span class="thankyou">(Moses support)</span><br>
    </div>
    
</div>
<div class="clear">&nbsp;</div>
