<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2017 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html
  
 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or 
 plugin-exception.txt in the root folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/**#@+
 * @author Marc Mittag
 * @package trantlate5
 * @version 0.7
 *
 */
?>
<article class="post">
    <header>
        <div class="title"><h2>Extremely flexible for integrations</h2></div>
    </header>
    <p>translate5 is made for easy &amp; flexible integration it in your processes:</p> 
    
    <ul>
        <li><strong><a href="#REST">REST-API for every GUI feature</a></strong></li>
        <li><strong><a href="#editor-only">Editor-only integration possible</a></strong></li>
        <li><strong><a href="#term-portal">Stand-alone usage as terminology portal</a></strong></li>
    </ul>
    <p><strong><a href="/index/extend">Extending translate5 with plug-ins</a> is the way to go for new functionality</strong> &mdash; and allows very feature-rich extensions like <a href="/index/outstanding-features#visualReview">visualReview</a> or trackChanges.</p>
    <p><strong><a href="#integrated-resources">Integrating existing other systems as micro-services</a></strong> is quite easy with translate5 and already widely done (Open Source and proprietary ones).</p>
    <img src="/images/cloud-api-technology-large.png" style="width: 100%">
    <a name="REST"></a><br><br><a name="editor-only"></a>
    <h2>REST-API for every GUI feature</h2>
    <p>Every feature you can use in the GUI, you also can use through <a href="https://confluence.translate5.net/display/TAD/REST+API">its REST-API</a> and therefore call it by another application.</p>
    <p>This is due to the architecture design of translate5 - and therefore future proof and guaranteed.</p>
    <h2>Editor-only integration possible</h2>
    <p>In case you manage your users, translation memories, terminology, tasks, etc. in other applications, <strong>you can only integrate the editor component of translate5</strong> and manage everything else via API from the other application(s).<a name="term-portal"></a></p>
    <p>This is a scenario already done by a number of companies &mdash; and a valid one taken the fact, that the features of translate's editor are leading in many regards in the translation industry.</p>
    
    <h2>Stand-alone usage as terminology portal</h2>
    <p>In case you simply would like a terminology portal for your end users (optionally integrated e.g. with Across or Multiterm) <strong>you can only use the translate5 terminology portal.</strong></p>
    <p>Users that only have the right to use the TermPortal are directly forwarded to the TermPortal after login.</p><a name="integrated-resources"></a>
    <p>Terminology can be imported via API, from the file system or directly from Across crossAPI.</p>
    <p>If you would like to see more functionality in translate5's TermPortal &mdash; like managing and editing the terminology directly inside translate5 &mdash; <a href="mailto:support@translate5.net">contact us</a>.</p>
    
    <h2>Integrated as resources: Other Open Source Systems</h2>
    <p>The architecture was build in a way that makes it easy to integrate also other systems as resources (even proprietary ones like SDL GroupShare).</p>
    <p>This flexibility of integration was used, to integrate other Open Source tools. Combined with and by translate5 they form a translation system, that contains the work of thousands of working hours worth millions of Euros.</p>
    <p>So as of today translate5 integrates and builds upon the following tools and components:</p>
    <ul>
        <li>The translate5 review system (cloud based), combining everything together</li>
        <li><a href="http://community.opentm2.org" target="_blank">OpenTM2 translation memory</a> (originally desktop based and developed by IBM, turned into a service by the crowdfunding)</li>
        <li><a href="http://www.statmt.org/moses/" target="_blank">Moses MT engine</a></li>
        <li><a href="https://github.com/heartsomeXPhantom/openTMSTermTagger" target="_blank">OpenTMSTermtagger</a> (for highlighing terminology)</li>
        <li><a href="http://okapiframework.org/" target="_blank">Okapi FrameWork</a> (for conversion of source file formats to xliff)</li>
        <li><a href="https://languagetool.org/" target="_blank">LanguageTool</a> (for spell- grammar and style-checking)</li>
    </ul>
    
</article>