<?php
 /*
 START LICENSE AND COPYRIGHT
 
 This file is part of Translate5 Editor PHP Serverside and build on Zend Framework
 
 Copyright (c) 2013 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ÄTT) MittagQI.com

 This file may be used under the terms of the GNU General Public License version 3.0
 as published by the Free Software Foundation and appearing in the file gpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU General Public License version 3.0 requirements will be met:
 http://www.gnu.org/copyleft/gpl.html.

 For this file you are allowed to make use of the same FLOSS exceptions to the GNU 
 General Public License version 3.0 as specified by Sencha for Ext Js. 
 Please be aware, that Marc Mittag / MittagQI take no warranty  for any legal issue, 
 that may arise, if you use these FLOSS exceptions and recommend  to stick to GPL 3. 
 For further information regarding this topic please see the attached license.txt
 of this software package.
 
 MittagQI would be open to release translate5 under EPL or LGPL also, if this could be
 brought in accordance with the ExtJs license scheme. You are welcome to support us
 with legal support, if you are interested in this.
 
 
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU General Public License version 3.0 http://www.gnu.org/copyleft/gpl.html
             with FLOSS exceptions (see floss-exception.txt and ux-exception.txt at the root level)
 
 END LICENSE AND COPYRIGHT 
 */

/**#@+
 * @author Marc Mittag
 * @package trantlate5
 * @version 0.7
 *
 */
$session = new Zend_Session_Namespace();
?>
<div class="main">
<h1>translate5 mission</h1>
    <p><i>This page is still in discussion within the translate5 community and is subject to change.</i></p>
    <h2>Collaboratively develop the software that companies, freelancers and MT-researchers need</h2>
    <p>Many translation companies, translation departments, freelancers and MT-researchers are technically skilled. They know, what they want and expect from their software.</p>
    <p><strong>The goal of the translate5 project is to give the control over the development of software to its users.</strong></p>
    <p>Developers need to produce what the users of their software need and want. And users can engage in development, if they want to and have the skills and knowledge to do so.</p>
    
    <hr>
    <h2>Joint development: the conceptual base</h2>
    <p>The language industry is becoming more technically complex.</p>
    <p>For small- and medium-sized companies and language departments, joining development forces with others to develop the software they need will become an important factor in maintaining independence from the big players of the language industry.</p>
    <p>For MT- researchers it is extremely helpful to be in close cooperation with companies using translation software in business - and to engage in common software development. Translation professionals benefit from the inputs of MT- research in development and translation processes.</p>
    <p><strong>The conceptual base for these needs is joint development based on Open Source.<br><br>Studies show, that many of the most successful companies cooperate with their competitors.</strong></p>
    <p>This concept is akin to the concept of other Open Source community projects in the language industry,  most notably <a href="http://www.opentag.com/okapi/wiki/" target="_blank">Okapi</a> (basic framework and suite of tools) and <a href="http://omegat.org/" target="_blank">OmegaT</a> (desktop translation tool).</p>
    <p>The translate5 project aims to cooperate with these and other Open Source projects wherever possible. As a web server environment, translate5 aims to serve as an API-based integration hub for many different tools (both Open Source and proprietary) to help users enjoy the combined power of different tools in an easy-to-use GUI.</p>
    <hr>
    <h2>Why Open Source</h2>
    <p>Open Source is free software. It is free in the sense of "no costs to use", but its main sense is "freedom". Users are free to do what they want with the software - integrate it, extend it, develop it -  so long as they respect the Open Source license.</p>
    <p><strong>This gives users security for their business: They will be able to rely on the software no matter, what happens to any company backing it. They always will be able to find someone to support or develop it.</strong></p>
    <p>In addition, the freedom of Open Source enables software to attract much more attention, from both users and contributors, than closed source software can.</p>
</div>
<div class="clear">&nbsp;</div>