<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5

 Copyright (c) 2013 - 2021 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt
 included in the packaging of this file.  Please review the following information
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html

 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or
 plugin-exception.txt in the root folder of translate5.

 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
             http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/* @var Zend_View $this */

$f = Zend_Registry::get('frontController');
/* @var Zend_Controller_Front $f */

//with /index/monitoring?json=1 we can use in Uptime Kuma Monitor Type "HTTP(s) - Json Query"
// and test for status = "All Ok". If this is not the case we get the reason in the Upime Kuma log and messages.
if ($this->isJsonQuery) {
    $f->getResponse()->setHttpResponseCode(200);
    $f->getResponse()->setHeader('Content-type', 'application/json');
    $f->getResponse()->sendHeaders();
    $res = new stdClass();
    $res->status = $this->monitoringMessage;
    echo json_encode($res);

    return;
}

$httpCode = (int) $this->monitoringHttpCode;
if ($httpCode > 0) {
    $f->getResponse()->setHttpResponseCode($httpCode);
    $f->getResponse()->sendHeaders();
}

echo $this->monitoringMessage;
