<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2017 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html
  
 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or 
 plugin-exception.txt in the root folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/**#@+
 * @author Marc Mittag
 * @package trantlate5
 * @version 0.7
 *
 */
?>
<article class="post">
    <header>
        <div class="title"><h2>Outstanding features</h2></div>
    </header>
    <p>The inputs of its users and the freedom of the development allow to develop outstanding features. For example:</p><a name="visualReview"></a>
    <ul>
        <li><strong><a href="#visualReview">VisualReview: Review in perfect layout &mdash; for most file formats</a></strong></li>
        <li><strong><a href="#trackChanges">Inline MS-Word style Track Changes</a></strong></li>
        <li><strong><a href="#tm-mt-integration">You decide, which TM / MT-engine you want to integrate (default OpenTM2 &amp; Moses)</a></strong></li>
        <li><strong><a href="#performance">100.000 segments &amp; 1000 files per task with high performance</a></strong></li>
        <li><strong><a href="#term-portal">Terminology Portal</a> (mobile ready!)</strong></li>
    </ul>
    <p>A complete bullet list of features <a href="https://confluence.translate5.net/display/TFD/Overview+of+features" target="_blank">can be found in translate5 Confluence</a>.</p>
    
    <h2>VisualReview: Review in perfect layout &mdash; for most file formats</h2>
    <p>With the VisualReview plug-in for translate5 users can proofread or postedit content in perfect layout (PDF quality). Still the changes go directly back into your bilingual source.</p>
    <p>Supported are most file formats: For example Indesign, FrameMaker, MS Word, MS Powerpoint, HTML, etc.</p>
    <p>Full automated process integrations with other CAT-tools are possible <a href="https://www.across.net/en/interface-translation/translate5/" target="_blank">and e.g. for Across already available</a>.</p>
    <p>VisualReview is <a href="/index/extend#sell">a paid Open Source plug-in</a>, available <a href="/index/crowd-of-companies">for companies that support translate5 project</a>.</p>
    <a name="trackChanges"></a><img src="/images/visualReview-gross.png" style="width: 100%;"><br><br>
    
    <h2>Inline MS-Word style Track Changes</h2>
    <p>Inline MS-Word style Track Changes allow users to change content and see the changes marked analogous to MS Word Track Changes: Added content is highlighted, deleted content highlighted and crossed out.</p>
    <p>A tooltip shows, who applied the change and when it has been applied.</p>
    <p>For every user a different highlight color is used. This is true for several users in the same workflow step (you can assign the same workflow step to multiple users) and for users across workflow steps.</p>
    <p>TrackChanges is <a href="/index/extend#sell">a paid Open Source plug-in</a>, available <a href="/index/crowd-of-companies">for companies that support translate5 project</a>.</p>
    <a name="tm-mt-integration"></a><img src="/images/trackChanges.png" style="width: 100%;"><br><br>
    <h2>You decide, which TM / MT-engine you want to integrate (default OpenTM2 &amp; Moses)</h2>
    <p>The flexibility of "match resource integration" (how we call it) is brought to the translate5 community by <a href="/index/crowd-of-companies#crowdfunding">the translate5 crowdfunding from 2015 to 2017</a>.</p>
    <p>It allows to integrate new match resources (translation memory or machine translation engines) with very little effort in translate5.</p>
    <p>The mechanism that integrates the match resources is completely independent from the resource - only an appropriate connector has to be build. If the API of the resource is good, the integration is done quickly. The integration of <a href="http://www.lucysoftware.com/english/machine-translation/" target="_blank">Lucy LT</a> for example was a matter of one development day of work.</p>
    <p>The match analysis and pre-translation mechanisms work in a way agnostic to the integrated resource: You simply select the translation memories you want to use (independent if they are OpenTM2 memories or others) and a translation is simulated in the background during the import process. The resulting match values are counted, including internal fuzzies (fuzzy matches that will be generated during translation).</p>
    <a name="performance"></a><img src="/images/tm-mt-resources.png" style="width: 100%;"><br><br>  
    <h2>100.000 segments &amp; 1000 files per task with high performance</h2>
    <p>If you work on a task with 100 segments and 1 file or on one with 100.000 segments (or more) and 1000 files &mdash; you will barely recognize a difference in performance. Translate5 is as smooth and fast as always. (Imports of course take longer with more segments ;-) )</p>
    <a name="term-portal"></a><img src="/images/100000-segments-1000-files.png" style="width: 100%;"><br><br>
    <h2>Terminology Portal</a> (mobile ready!)</h2>
    <p>The terminology portal in its current stage is aimed at end users, who want to search for terminology. <a href="/index/integrate#term-portal">It can be used stand-alone</a> (without using other translate5 components) by language service providers and industry companies alike (or of course together with other translate5 components).</p>
    <p>At the current stage the maintenance of terminology is still meant to be done in other tools like Multiterm or crossTerm (<a href="/index/crowd-of-companies">we are looking for supporters for the next stage of the development!</a>)</p>
    <p>TBX files can be imported via REST-API, from the filesystem or directly from crossAPI.</p>
    <p><a href="/login">Try it out online!</a></p>
    <img src="/images/termportal.png" style="width: 100%;">
</article>
