<?php
 /*
 START LICENSE AND COPYRIGHT
 
 This file is part of Translate5 Editor PHP Serverside and build on Zend Framework
 
 Copyright (c) 2013 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ÄTT) MittagQI.com

 This file may be used under the terms of the GNU General Public License version 3.0
 as published by the Free Software Foundation and appearing in the file gpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU General Public License version 3.0 requirements will be met:
 http://www.gnu.org/copyleft/gpl.html.

 For this file you are allowed to make use of the same FLOSS exceptions to the GNU 
 General Public License version 3.0 as specified by Sencha for Ext Js. 
 Please be aware, that Marc Mittag / MittagQI take no warranty  for any legal issue, 
 that may arise, if you use these FLOSS exceptions and recommend  to stick to GPL 3. 
 For further information regarding this topic please see the attached license.txt
 of this software package.
 
 MittagQI would be open to release translate5 under EPL or LGPL also, if this could be
 brought in accordance with the ExtJs license scheme. You are welcome to support us
 with legal support, if you are interested in this.
 
 
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU General Public License version 3.0 http://www.gnu.org/copyleft/gpl.html
             with FLOSS exceptions (see floss-exception.txt and ux-exception.txt at the root level)
 
 END LICENSE AND COPYRIGHT 
 */

/**#@+
 * @author Marc Mittag
 * @package trantlate5
 * @version 0.7
 *
 */
?>
<h1>translate5 developer information</h1>

<div class="main">
    <p>English language only</p>
        <h2>translate5 Yahoo user group</h2>
    <p>Any questions regarding usage or development of translate5 can be asked in <a href="https://groups.yahoo.com/neo/groups/translate5/info" target="_blank">translate5 Yahoo user group</a>. Please read the documentation before you ask.</p>

    <h2>translate5 feature documentation</h2>
    <p>The <a href="http://confluence.translate5.net/display/TFD" target="_blank">translate5 feature documentation</a> is addressed to everyone who wants to know more about translate5.</p>

        <h2>translate5 architecture documentation</h2>
        <p>The <a href="http://confluence.translate5.net/display/TAD/translate5+architecture+documentation" target="_blank">translate5 architecture documentation</a> is addressed to developers who want to contribute to translate5 or integrate it. </p>
   
    
    <h2>translate5 issue tracker</h2>
    <p>You are free to report any feature proposals or bugs to our <a href="http://jira.translate5.net/" target="_blank">translate5 JIRA issue tracker</a>.</p>
    <h2>translate5 source code on bitbucket</h2>
    <p>The current stable master branch of translate5 is always <a href="https://bitbucket.org/mittagqi" target="_blank">published on bitbucket</a>.  New major features are at first available to those who fund them. Later on they will be added to the public master of translate5.
</p>
<p>translate5 is spread over multiple Bitbucket repositories and also requires a number of external libraries. The top repository is "translate5", which contains the dependencies as submodules or references.
</p>

<p>MittagQI - Quality Informatics<br />Konrad-Lorenz-Weg 10<br />72116 Mössingen<br />Tel. 07473/220202<br />Fax 07473/220211<br />E-Mail: service@MittagQI.com</p>
</div>
<div class="clear">&nbsp;</div>
