<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2017 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html
  
 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or 
 plugin-exception.txt in the root folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/**#@+
 * @author Marc Mittag
 * @package trantlate5
 * @version 0.7
 *
 */
?>
<article class="post">
    <header>
        <div class="title"><h2>How to support the translate5 project</h2></div>
    </header>
<p>The idea behind translate5 is to build a community-based Open Source translation system.</p>
<p>A system, that companies can integrate and extend the way, they need it. A system not owned, developed and supported by competitors, but by Open Source companies and the community.</p>

<h2>Options to support translate5 and be part of the community</h2>
<p>translate5 is mainly driven by a crowd of companies dedicated to the project. The best way to support translate5 is <a href="/index/crowd-of-companies">to join this group of companies</a>.</p>
<p>As done by this group of companies, everyone else is also invited to:</p>
<a name="spread"></a>
<ul>
    <li><a href="#spread">Spread the word</a></li>
    <li><a href="#feedback">Give us feedback / report issues</a></li>
    <li><a href="#fund-features">Fund features</a></li>
    <li><a href="#documentation">Contribute to documentation</a></li>
    <li><a href="#plug-ins">Develop plug-in's</a></li>
    <li><a href="#core">Contribute to core development</a></li>
    <li><a href="#permanent">Permanent funding</a></li>
</ul>
<a name="feedback"></a>
<h3>Spread the word</h3>
<p>What helps ver much is to spread the word.</p><p>Talk with people about the idea of a community-based Open Source system in the translation industry. A system that has the backing of experienced Open Source companies and is free, open and based on a large community. Write about it on FB, LinkedIn, Twitter, ect.</p>

<a name="fund-features"></a>
<h3>Give us feedback / report issues</h3>
<p>Tell us, what you think of translate5.</p>
<p> What should be improved? Where is a bug? Which feature would you like to see?</p>
<p>Write us at <a href="mailto:support@translate5.net">support@translate5.net</a> or commit your issues directly to <a href="http://jira.translate5.net" target="_blank">translate5 JIRA</a>.</p>

<a name="documentation"></a>
<h3>Fund features</h3>
<p>That's the way most of translate5's current feature set has been able to develop. You use or want to use translate5 and need some new functionality?</p>
<p>Write us at <a href="mailto:support@translate5.net">support@translate5.net</a>. Most new features are developed as plug-in's - so every user can choose, if he/she wants to use it.</p>

<a name="plug-ins"></a>
<h3>Contribute to documentation</h3>
<p>You think, translate5's documentation for users, administrators or developers should be improved?</p><p>Create yourself an account at <a href="http://confluence.translate5.net" target="_blank">confluence.translate5.net</a> and start writing. In case of any questions: <a href="mailto:support@translate5.net">Contact us</a>.</p>

<a name="core"></a>
<h3>Develop plug-in's</h3>
<p>You need some new functionality and want to develop it yourself?</p>
<p><a href="http://confluence.translate5.net/display/TPLO" target="_blank">Write a translate5 plug-in</a>. Most of the new features can and should be written as plug-in's.</p><p>This enables you to extend translate5 without needing to change the core and thus makes it much more easy to keep updating translate5. It also enables users to easily (de)activate features according to their needs.</p>
<p>And: Contribute to the community and publish your plug-in at <a href="http://confluence.translate5.net/display/TPLO" target="_blank">translate5's plug-in space</a>.</p>
<p>Feel free to <a href="mailto:support@translate5.net">contact us</a> for support or for giving you the publicity you deserve, when contributing a plug-in.</p>

<a name="permanent"></a>
<h3>Contribute to core development</h3>
<p>translate5 is relied on by LSPs in their daily business. Thus to ensure quality, the master of translate5's core repository and the plug-ins developed by MittagQI are only writeable for very few people.</p>
<p>If you want to contribute to translate5's core - please <a href="mailto:support@translate5.net">contact us</a> and we find the best way to do it.</p>


<h3>Permanent funding</h3>
<p>So far most of translate5 has been developed supported by funding dedicated to distinct features.</p>
<p>Yet to develop translate5 into the envisioned system for the community, often developments are needed, that do not get enough attraction of users to fund them directly.</p>
<p>translate5 is professional software, written during working time of software professionals.</p>
<p>So to ensure stability and a good future orientated software, the best you can do for translate5 is to support it permanently with a certain amount. This gives us the possibility to do what needs to be done for the sake of the software and the community.</p>

<p> Or to <a href="/index/crowd-of-companies">to join the crowd of companies, that use translate5 in their daily business</a></p><p> And: We are completely transparent to our contributors, for what the money is used. <a href="mailto:support@translate5.net">Contact us</a>!</p>
</article>
