<?php
 /*
 START LICENSE AND COPYRIGHT
 
 This file is part of Translate5 Editor PHP Serverside and build on Zend Framework
 
 Copyright (c) 2013 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ÄTT) MittagQI.com

 This file may be used under the terms of the GNU General Public License version 3.0
 as published by the Free Software Foundation and appearing in the file gpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU General Public License version 3.0 requirements will be met:
 http://www.gnu.org/copyleft/gpl.html.

 For this file you are allowed to make use of the same FLOSS exceptions to the GNU 
 General Public License version 3.0 as specified by Sencha for Ext Js. 
 Please be aware, that Marc Mittag / MittagQI take no warranty  for any legal issue, 
 that may arise, if you use these FLOSS exceptions and recommend  to stick to GPL 3. 
 For further information regarding this topic please see the attached license.txt
 of this software package.
 
 MittagQI would be open to release translate5 under EPL or LGPL also, if this could be
 brought in accordance with the ExtJs license scheme. You are welcome to support us
 with legal support, if you are interested in this.
 
 
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU General Public License version 3.0 http://www.gnu.org/copyleft/gpl.html
             with FLOSS exceptions (see floss-exception.txt and ux-exception.txt at the root level)
 
 END LICENSE AND COPYRIGHT 
 */

/**#@+
 * @author Marc Mittag
 * @package trantlate5
 * @version 0.7
 * @obsolete FIXME
 */
$session = new Zend_Session_Namespace();
$config = Zend_Registry::get('config');
?>
<h1><?php echo $this->translate->_('translate5 Demoversion'); ?></h1>

<div class="main">
<?php
if(!empty($this->tasks)){
?>
    <h2><?php echo $this->translate->_('Hinweise zur Bedienung'); ?></h2>
    <ul>
<li><?php echo $this->translate->_('<b>Bitte beachten Sie:</b> Diese translate5 Demoversion ist öffentlich, alle hochgeladenen Projekte können von jedem eingesehen werden. Ein Export spielt alle aktuell eingecheckten Dateien eines Projektes aus.'); ?></li>        
<li><?php echo $this->translate->_('<b>Brower-Support:</b> Die aktuelle Version unterstützt offiziell neuere Versionen von Firefox, Chrome und Safari, sowie Internet Explorer 7, 8, 9 und 10.'); ?></li>
<li><?php echo $this->translate->_('<b>QM-Subsegment-Markierungen</b> werden im Export aktuell nur beim Format CSV abgebildet.'); ?></li>
</ul>
<h2><?php echo $this->translate->_('Projektübersicht'); ?></h2>
<table>
    <tr>
        <th><?php echo $this->translate->_('Projekt'); ?></th>
        <th colspan="2"><?php echo $this->translate->_('Actions'); ?></th>
    </tr>
<?php
$actionUrl = APPLICATION_RUNDIR.'/index/%s/taskGuid/%s';
$actionEditorUrl = APPLICATION_RUNDIR.'/editor/%s/taskGuid/%s';
foreach($this->tasks as $task){
    $name = empty($task['taskName']) ? $this->translate->_('Kein Name') : $task['taskName'];
?>
    <tr>
        <td><?php echo $name;?></td>
        <?php /*
        <td style="width:70px;"><a href="<?php printf($actionUrl, 'delete', $task['taskGuid']); ?>" title="<?php echo $this->translate->_('löschen');?>"><?php echo $this->translate->_('löschen');?></a></td>
           */ ?>
        <td style="width:60px;"><a href="<?php printf($actionUrl, 'edit', $task['taskGuid']); ?>" title="<?php echo $this->translate->_('lektorieren');?>"><?php echo $this->translate->_('lektorieren');?></a></td>
        <td style="width:250px;">
            <a href="<?php printf($actionUrl, 'export', $task['taskGuid']); ?>" title="<?php echo $this->translate->_('exportieren');?>"><?php echo $this->translate->_('exportieren');?></a><br />
            <a href="<?php printf($actionUrl, 'export/diff/1', $task['taskGuid']); ?>" title="<?php echo $this->translate->_('exportieren mit Änderungshistorie');?>"><?php echo $this->translate->_('exportieren mit Änderungshistorie');?></a><br />
  <?php 
    $modelTask = ZfExtended_Factory::get('editor_Models_Task');
    /* @var $modelTask editor_Models_Task */
    $modelTask->loadByTaskGuid($task['taskGuid']);
    $qmFlagsPresent = $modelTask->getQmSubsegmentFlags();
    
    if(!empty($qmFlagsPresent) && $config->runtimeOptions->editor->enableQmSubSegments) { 
        $qmStatUrl = sprintf($actionEditorUrl, 'qmstatistics/index', $task['taskGuid']);
        $tit = $this->translate->_('Export QM-Statistik');
        $label_t = $this->translate->_('Export Zieltext QM-Statistik (XML)');
        $label_s = $this->translate->_('Export Ausgangstext QM-Statistik (XML)');
?>
        <a href="<?php echo $qmStatUrl; ?>" title="<?php echo $tit; ?>"><?php echo $label_t;?></a>
<?php 
        if($modelTask->getEnableSourceEditing()) { 
?>
        <br /><a href="<?php echo $qmStatUrl; ?>?type=source" title="<?php echo $tit;?>"><?php echo $label_s;?></a>
<?php 
        }
?>
<?php 
    }else{ 
      ?>
        </td>
<?php
    }
?>
    </tr>
<?php 
}
?>
</table>
<?php
} //end of if(!empty($this->tasks))
?>
</div>
<div class="sidebar">
    <div class="teaser">
        <h2><?php echo $this->translate->_('Neues Projekt anlegen'); ?></h2>
        <ul>
            <li><a href="<?php echo APPLICATION_RUNDIR; ?>/index/import"><?php echo $this->translate->_('Neue Projektdaten importieren'); ?></a></li>
        </ul>
    </div>
    <?php
        echo $this->render('index/testdataSidebar.phtml');
        echo $this->render('index/betanotice.phtml');
    ?>
</div>
<div class="clear">&nbsp;</div>