<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2015 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3.0 requirements will be met:
 http://www.gnu.org/licenses/agpl.html

 There is a plugin exception available for use with this release of translate5 for
 open source applications that are distributed under a license other than AGPL:
 Please see Open Source License Exception for Development of Plugins for translate5
 http://www.translate5.net/plugin-exception.txt or as plugin-exception.txt in the root
 folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execptions
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

?>
    <h1>translate5 usage &amp; documentation</h1>
    <p><a href="http://confluence.translate5.net/" target="_blank">translate5 Confluence</a> is where translate5 developers and users collaborate and share knowledge. </p>
    <p>In <a href="http://confluence.translate5.net/" target="_blank">translate5 Confluence</a> you'll find all information related to usage and documentation about translate5.</p>
    <h2>Most important translate5 Confluence spaces for usage</h2>
    <ul><li><a href="http://confluence.translate5.net/display/TIU" target="_blank">Installation and update</a></li>
    <li><a href="http://confluence.translate5.net/display/BUS" target="_blank">Basic usage</a></li>
        <li><a href="http://confluence.translate5.net/display/TFD" target="_blank">Feature documentation</a></li>
    </ul>
    <h2>Integrations with other tools</h2>
    <p>Integrations of translate5 are very easy. Every feature in translate5 can be called via API by another software. <br><br>In addition, translate5 can be used in editor-only mode. In this case task- and user-management can be done in another application. A task and a user session is opened via link. <a href="http://confluence.translate5.net/display/IWT" target="_blank"></a>For more details please see our wiki</a>.</p>
    <h2>Other translate5 Confluence spaces</h2>
    <ul>
        <li><a href="http://confluence.translate5.net/display/TAD" target="_blank">Architecture documentation (for developers)</a></li>
        <li><a href="http://confluence.translate5.net/display/CON" target="_blank">Configuration (for administrators)</a></li>
        <li><a href="http://confluence.translate5.net/display/IWT" target="_blank">Integration with other tools</a></li>
        <li><a href="http://confluence.translate5.net/display/TPLO" target="_blank">Plug-in's (for developers &amp; administrators)</a></li>
        <li><a href="http://confluence.translate5.net/display/TAD" target="_blank">Architecture documentation (for developers)</a></li>
    </ul>
