<?php
 /*
 START LICENSE AND COPYRIGHT
 
 This file is part of Translate5 Editor PHP Serverside and build on Zend Framework
 
 Copyright (c) 2013 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ÄTT) MittagQI.com

 This file may be used under the terms of the GNU General Public License version 3.0
 as published by the Free Software Foundation and appearing in the file gpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU General Public License version 3.0 requirements will be met:
 http://www.gnu.org/copyleft/gpl.html.

 For this file you are allowed to make use of the same FLOSS exceptions to the GNU 
 General Public License version 3.0 as specified by Sencha for Ext Js. 
 Please be aware, that Marc Mittag / MittagQI take no warranty  for any legal issue, 
 that may arise, if you use these FLOSS exceptions and recommend  to stick to GPL 3. 
 For further information regarding this topic please see the attached license.txt
 of this software package.
 
 MittagQI would be open to release translate5 under EPL or LGPL also, if this could be
 brought in accordance with the ExtJs license scheme. You are welcome to support us
 with legal support, if you are interested in this.
 
 
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU General Public License version 3.0 http://www.gnu.org/copyleft/gpl.html
             with FLOSS exceptions (see floss-exception.txt and ux-exception.txt at the root level)
 
 END LICENSE AND COPYRIGHT 
 */
?>
<div class="main">
    <h1>translate5 usage &amp; documentation</h1>
    <p><a href="http://confluence.translate5.net/" target="_blank">translate5 Confluence</a> is where translate5 developers and users collaborate and share knowledge. </p>
    <p>In <a href="http://confluence.translate5.net/" target="_blank">translate5 Confluence</a> you'll find all usage and documentation related information about translate5.</p>
    <h2>Most important translate5 Confluence spaces for usage</h2>
    <ul><li><a href="http://confluence.translate5.net/display/BUS" target="_blank">Installation and update</a></li>
    <li><a href="http://confluence.translate5.net/display/BUS" target="_blank">Basic usage</a></li>
        <li><a href="http://confluence.translate5.net/display/TFD" target="_blank">Feature documentation</a></li>
    </ul>
    <h2>Post questions in translate5 Yahoo mailing list</h2>
    <p><b>Before you ask a question at <a href="https://groups.yahoo.com/neo/groups/translate5/info" target="_blank">translate5 Yahoo mailing list</a>:</b></p>
    <p>Please check carefully:
    <ul>
        <li>Is my question answered in <a href="http://confluence.translate5.net/" target="_blank">translate5 Confluence</a>?</li>
        <li>Has my question already been asked in the <a href="https://groups.yahoo.com/neo/groups/translate5/info" target="_blank">translate5 Yahoo mailing list</a>?</li>
    </ul></p>
</div>
<div class="clear">&nbsp;</div>