<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2017 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html
  
 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or 
 plugin-exception.txt in the root folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

?>
<article class="post">
    <p><a href="/index/outstanding-features">submenu: Outstanding features</a></p>
    <p><a href="/index/source">submenu: Get the source code</a></p>
    <header>
        <div class="title"><h2>translate5 usage, installation &amp; documentation</h2></div>
    </header>
    <p><a href="http://confluence.translate5.net/" target="_blank">translate5 Confluence</a> is where translate5 developers and users collaborate and share knowledge. </p>
    <p>In <a href="http://confluence.translate5.net/" target="_blank">translate5 Confluence</a> you'll find all information related to usage and documentation about translate5.</p>
    <h2>Most important translate5 Confluence spaces</h2>
    <ul><li><a href="http://confluence.translate5.net/display/TIU" target="_blank">Installation and update</a></li>
    <li><a href="http://confluence.translate5.net/display/BUS" target="_blank">Basic usage</a></li>
        <li><a href="http://confluence.translate5.net/display/TFD" target="_blank">Feature documentation</a></li>
    </ul>
    <h2>Integrations with other tools</h2>
    <p>Integrations of translate5 are very easy. Every feature in translate5 can be <a href="http://confluence.translate5.net/display/TAD/REST+API" target="_blank">called via API</a> by another software. <br><br>In addition, translate5 can be used in editor-only mode. In this case task- and user-management can be done in another application. A task and a user session is opened via link. <br><br>Another option is to integrate translation memory systems or machine translation engines as <a href="http://confluence.translate5.net/display/TPLO/MatchResource" target="_blank">match resources with translate5</a>.<br><br><a href="http://confluence.translate5.net/display/IWT" target="_blank">For more details please see our wiki</a>.</p>
    <h2>Other translate5 Confluence spaces</h2>
    <ul>
        <li><a href="http://confluence.translate5.net/display/TAD" target="_blank">Architecture documentation (for developers)</a></li>
        <li><a href="http://confluence.translate5.net/display/CON" target="_blank">Configuration (for administrators)</a></li>
        <li><a href="http://confluence.translate5.net/display/TPLO" target="_blank">Plug-in's (for developers &amp; administrators)</a></li>
        <li><a href="http://confluence.translate5.net/display/IWT" target="_blank">Integration with other tools</a></li>
    </ul>
</article>