<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5

 Copyright (c) 2013 - 2021 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt
 included in the packaging of this file.  Please review the following information
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html

 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or
 plugin-exception.txt in the root folder of translate5.

 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
             http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/* @var $this Zend_View */
$config = Zend_Registry::get('config');
?>
  <h2><?php echo $this->translate->_('Application error'); ?></h2>
  <p><?php echo $this->translate->_('We apologize for the problem you encountered!'); ?></p>
  <p><?php echo $this->translate->_('Our administrators are automatically notified of the error. If you have any questions or concerns, please contact our support team.'); ?></p>
<?php
if (! headers_sent() && getenv('T5_REDIRECT_ON_ERROR')) {
    echo '<p><b>You will be redirected automatically to our status page.</b></p>';
    header('Refresh: 5; url=' . getenv('T5_REDIRECT_ON_ERROR'));
}
