<?php
/*
 START LICENSE AND COPYRIGHT
 
 This file is part of translate5
 
 Copyright (c) 2013 - 2017 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.
 
 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com
 
 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt
 included in the packaging of this file.  Please review the following information
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html
 
 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or
 plugin-exception.txt in the root folder of translate5.
 
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt
 
 END LICENSE AND COPYRIGHT
 */
?>


<div id="container-header" class="container">
    <div id="logo"></div>
<?php 
    // see View_Helper_LanguageSelector
    $session = new Zend_Session_Namespace();
    $translate = ZfExtended_Zendoverwrites_Translate::getInstance();
    $availableTranslations = $translate->getAvailableTranslations();
    asort($availableTranslations);
    echo '<form action="#" method="post" name="languageSelector" id="languageSelector">';
    echo '<select id="locale">';
    foreach ($availableTranslations as $locale => $translation) {
        $selected = ($locale == $session->locale) ? ' selected' : '';
        echo '<option value="'.$locale.'"'.$selected.'>'.$translation.'</option>';
    }
    echo '</select>';
    echo '</form>';
    
    $userModel=ZfExtended_Factory::get('ZfExtended_Models_User');
    /* @var $userModel ZfExtended_Models_User */
    $isUserAllowed=$userModel->isAllowed("editor_instanttranslate","all");
    
    //check if the user is allowed to acces the term portal
    if($isUserAllowed){
        echo '<div id="instantTranslateButtonContainer"><a id="instantTranslateButton" class="ui-button ui-widget ui-corner-all">'.$translate->_("Sofortübersetzung").'</a></div>';
    }else{
        echo '<div id="instantTranslateButtonContainer"></div>';
    }
?>
    <div id="logout"><a href="#" class="ui-button ui-widget ui-corner-all ui-state-active ui-state-focus">Logout</a></div>
</div>
<?php 
if(isset($this->error)){
    echo '<div class="container ui-state-error ui-corner-all">';
    echo $this->error;
    echo '</div>';
    return;
}    
?>
<div id="container-content" class="container">
    
    <div class="wrap">
            <div id="searchForm" class="ui-toolbar ui-widget-header ui-helper-clearfix">
                <input class="serchField ui-widget ui-widget-content ui-corner-all" type="text" placeholder="<?php echo $this->translations["search"];?>..." name="search" id="search">
                <button id="searchButton"></button>
                <?php
                    $languages = $this->languages;
                    uasort($languages, function($a, $b) {
                        return strcmp($a['rfc5646'], $b['rfc5646']);
                    });
                    $preselectedLang = false;
                    if (isset($_GET['lang'])) {
                        // if param 'lang' is given, select it
                        $preselectedLang = $_GET['lang'];
                    } else if (!empty($this->preselectedLang)) {
                        // if the preselectedLang exist, select it
                        $preselectedLang = $this->preselectedLang;
                    }
                    echo '<select name="languages" id="languages">';
                    foreach ($languages as $lang){
                        $isSelected=($preselectedLang !== false) && ($preselectedLang == $lang["rfc5646"]);
                        echo '<option '.($isSelected ? 'selected="selected"' : '').' value="'.implode(",", $lang['languageGroup']).'">'.$lang["rfc5646"].'</option>';
                    }
                    echo '</select>';
                ?>
            </div>
    </div>
    
    <div class="ui-state-error ui-corner-all" id="error-no-results" style="display:none;"><?php echo $this->translations["noResults"];?></div>
    
    <div class="wrap" id="finalResultContent" style="display: none;">
    	<div id="searchTermsHolder" class="ui-tabs ui-corner-all ui-widget ui-widget-content">
        	<ul id="searchTermsSelect" size="10" style="display: inline-block;">
        	</ul>
    	</div>
    	<div id="resultTermsHolder">
          <ul>
            <li><a href="#resultTermsHolder-1"><?php echo $this->translations["termTableTitle"];?></a></li>
            <li><a href="#resultTermsHolder-2"><?php echo $this->translations["termEntryAttributeTableTitle"];?></a></li>
          </ul>
          <div id="resultTermsHolder-1">
                <div class="tabble-inner-style" id="termTable">
                </div>
          </div>
          <div id="resultTermsHolder-2">
              <div class="tabble-inner-style" id="termAttributeTable">
              </div>
          </div>
        </div>
    </div>
    
</div>

<script type="text/javascript">
//init the labels here, for later usage
//FIXME: Refactor the Variable stuff to php2js stuff
var attributeLabels='<?php echo json_encode($this->labels);?>';
attributeLabels = JSON.parse(attributeLabels);
var collectionIds=<?php echo json_encode($this->collectionIds);?>;
var rfcLanguageFlags=<?php echo json_encode($this->rfcFlags);?>;
var moduleFolder = '<?php echo $this->moduleFolder; ?>';
var SESSION_LOCALE='<?php echo $session->locale; ?>';
var noExistingAttributes='<?php echo $this->translations["noExistingAttributes"];?>';

function setSizesInFinalResultContent(){
    var SCROLLBAROFFSET = 30; // Due to the scrollbar etc, #searchTermsHolder and #resultTermsHolder have different content-width (Chrome and Firefox: 26.600000000000023)
    if ($('#searchTermsHolder').is(':visible')) {
        // (1) Left column: ensure that the scrollable area has always the maximal possible height that is available in the current browser window.
        $('#searchTermsHolder').css("height", window.innerHeight - $('#searchTermsHolder').position().top - 20);
        // (2) Right column: must not wrap underneath the left column until BOTH of them are wrapped to rows (is out of sight otherwise!)
        if ($('#resultTermsHolder').is(':visible')) {
            var widthTerms = $('#searchTermsHolder').width(),
                widthResults = $('#resultTermsHolder').width();
            if ( (widthResults - widthTerms > SCROLLBAROFFSET) &&       // = check if they have the same size (= wrapped as rows and both displayed in full width already)
                 (widthResults + widthTerms > window.innerWidth) ) {    // = together they are broader than the window and the results would be wrapped
                $('#resultTermsHolder').css("width", window.innerWidth - widthTerms - 100); // 100 is just to get small enough to not be wrapped; flex ("auto") will adjust the width by itself then
            }
        }
    }
}

$( function() {
    $('#logout a').mouseover(function(){
            $(this).removeClass("ui-state-active");
        });
    $('#logout a').mouseout(function(){
            $(this).addClass("ui-state-active");
        });
    $('#logout').on("click",function(){
        window.location = Editor.data.loginUrl;
    });
    $('#languages').selectmenu({
        change: function( event, ui ) {
            startAutocomplete();
        }
      });
    $('#locale').selectmenu({
        change: function() {
            var action = $(this).val();
            $("#languageSelector").attr("action", "?locale=" + action);
            $("#languageSelector").submit();
        }
      });
    $("#searchTermsSelect").on( "selectableselected", function( event, ui ) {
        findTermsAndAttributes($(ui.selected).attr('data-value'));
    });
    $("#resultTermsHolder").tabs();
    $("#search").focus();
    $(window).resize(function() {
        setSizesInFinalResultContent();
    });
} );

</script>
<script src="<?php echo APPLICATION_RUNDIR; ?>/modules/editor/termportal/js/Termportal.js"></script>
<script type="text/javascript">
    checkDirectSearch();
</script>