<?php
/*
 START LICENSE AND COPYRIGHT
 
 This file is part of translate5
 
 Copyright (c) 2013 - 2017 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.
 
 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com
 
 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt
 included in the packaging of this file.  Please review the following information
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html
 
 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or
 plugin-exception.txt in the root folder of translate5.
 
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt
 
 END LICENSE AND COPYRIGHT
 */

?>

<link rel="stylesheet" href="<?php echo APPLICATION_RUNDIR; ?>/modules/editor/termportal/js/jquery-ui-1.12.1/jquery-ui.min.css">
<script src="<?php echo APPLICATION_RUNDIR; ?>/modules/editor/termportal/js/jquery-ui-1.12.1/external/jquery/jquery.js"></script>
<script src="<?php echo APPLICATION_RUNDIR; ?>/modules/editor/termportal/js/jquery-ui-1.12.1/jquery-ui.min.js"></script>

<link rel="stylesheet" href="<?php echo APPLICATION_RUNDIR; ?>/modules/editor/termportal/css/termportal.css">

<div id="header">
    <img src="/images/translate5.png?v=1" alt="translate5">
    <div id="slogan">open source web-based translation system<br><small>translation, proofreading, postediting &amp; QA</small></div>
</div>

<div id="container">

    <?php 
    if(isset($this->error)){
        echo '<div class="ui-state-error ui-corner-all">';
        echo $this->error;
        echo '</div>';
        exit;
    }
    
    ?>
    
    <div class="wrap">
          <?php
          if (count($this->languages) <= 3) {
              echo '<div name="languages" id="languages">';
              foreach ($this->languages as $lang){
                  echo '<label for="'.$lang["id"].'">'.$lang["rfc5646"].'</label>';
                  echo '<input type="radio" name="languages" value="'.$lang["id"].'" id="'.$lang["id"].'">';
              }
              echo '</div>';
          } else {
              echo '<select name="languages" id="languages">';
              foreach ($this->languages as $lang){
                  echo '<option value="'.$lang["id"].'">'.$lang["rfc5646"].'</option>';
              }
              echo '</select>';
          }
          ?>
            <div id="searchForm" class="ui-toolbar ui-widget-header ui-helper-clearfix">
                <input class="serchField ui-widget ui-widget-content ui-corner-all" type="text" placeholder="Search.." name="search" id="search">
                <button id="searchButton"></button>
            </div>
    </div>
    
    <div class="wrap" id="finalResultContent" style="display: none;">
    	<div id="searchTermsHolder" class="ui-tabs ui-corner-all ui-widget ui-widget-content">
        	<ul id="searchTermsSelect" size="10" style="width: 200px; display: inline-block;">
        	</ul>
    	</div>
    	<div id="resultTermsHolder">
          <ul>
            <li><a href="#resultTermsHolder-1"><?php echo $this->translations["termTableTitle"];?></a></li>
            <li><a href="#resultTermsHolder-2"><?php echo $this->translations["termEntryAttributeTableTitle"];?></a></li>
          </ul>
          <div id="resultTermsHolder-1">
                <table class="tabble-inner-style" id="termTable">
                </table>
          </div>
          <div id="resultTermsHolder-2">
              <table class="tabble-inner-style" id="termAttributeTable">
              </table>
          </div>
        </div>
    </div>

</div>

<script type="text/javascript">
//init the labels here, for later usage
var attributeLabels='<?php echo json_encode($this->labels);?>';
attributeLabels = JSON.parse(attributeLabels);

var termTableTitle='<?php echo $this->translations["termTableTitle"];?>';
var termEntryAttributeTableTitle='<?php echo $this->translations["termEntryAttributeTableTitle"];?>';
var termAttributeTableTitle='<?php echo $this->translations["termAttributeTableTitle"];?>';
var collectionIds=<?php echo json_encode($this->collectionIds);?>;

$( function() {
    <?php if (count($this->languages) <= 3): ?>
        $("#languages input").first().prop("checked", true);
        $("#languages input").checkboxradio();
    <?php else: ?>
        $("#languages").selectmenu();
    <?php endif; ?>
    
    $("#resultTermsHolder").tabs();
} );

</script>
<script src="<?php echo APPLICATION_RUNDIR; ?>/modules/editor/termportal/js/Termportal.js"></script>