<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2021 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html
  
 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or 
 plugin-exception.txt in the root folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/**#@+
 * @author Marc Mittag
 * @package portal
 * @version 2.0
 *
 */

/* @var $this Zend_View */
$this->render('general.phtml');

$params = [        
        'header' => $this->header,
        'footer' => $this->footer,
        'role' => $this->translate->_($this->role),
        'reviewersFragment' => '',
];

$taskNr = $this->task->getTaskNr();
if(!empty($taskNr)) {
    $taskNr .= ' - ';
}
$this->subject = $this->translate->_('Translate5 - Aufgabe zugewiesen').' "'.$taskNr.$this->task->getTaskName().'"';


$template = '{header}

Im Projektportal {portalLink} wurde Ihnen eine Aufgabe zugewiesen.<br />
<br />
<b>Rolle:</b> {role}<br/>
{taskFragment}{reviewersFragment}{footer}';


if(!empty($this->associatedUsers)) {
    $params['reviewersFragment'] = $this->htmlOnly;
}
$this->textbody = strip_tags($this->templateApply($template, $params));

if(!empty($this->associatedUsers)) {
    $params['reviewersFragment'] = $this->translate->_("\n<br/>".'<b>Alle der Aufgabe zugeordneten Benutzer:</b>'."\n<br/>");
    $params['reviewersFragment'] .= $this->workflowNotifyMail()->renderUserList($this->associatedUsers, $this->receiver->userGuid);
}
if($this->addCompetitiveDisclaimer) {
    //the disclaimer is injected to the role for correct positioning also we do not have to touch all client overwritten templates
    $params['role'] .= $this->translate->_("\n<br/>\n<br/>".'<b>Achtung:</b> Konkurrierende Benutzer: Der erste Benutzer, der einen Job annimmt, führt einen Job aus. Allen anderen wird automatisch die Aufgabe entzogen.'."\n<br/>");
}
echo $this->templateApply($template, $params);

