<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5

 Copyright (c) 2013 - 2021 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt
 included in the packaging of this file.  Please review the following information
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html

 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or
 plugin-exception.txt in the root folder of translate5.

 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
             http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/**#@+
 * @author Marc Mittag
 * @package portal
 * @version 2.0
 *
 */

/* @var $this Zend_View */
$this->render('general.phtml');

$params = [
    'header' => $this->header,
    'footer' => $this->footer,
    'role' => $this->translate->_($this->role),
    'reviewersFragment' => '',
];

$taskNr = $this->task->getTaskNr();
if (! empty($taskNr)) {
    $taskNr .= ' - ';
}
$this->subject = $this->translate->_('translate5 – task associated') . ' "' . $taskNr . $this->task->getTaskName() . '"';

if (! empty($this->associatedUsers)) {
    $params['reviewersFragment'] = $this->htmlOnly;
}
$this->textbody = strip_tags($this->templateApply('{header}

In the project portal {portalLink}, a task was assigned to you.<br />
<br />
<b>Role:</b> {role}<br/>
{taskFragment}{reviewersFragment}{footer}', $params));

if (! empty($this->associatedUsers)) {
    $params['reviewersFragment'] = $this->translate->_('
<br/><b>All users assigned to the task:</b>
<br/>');
    $params['reviewersFragment'] .= $this->workflowNotifyMail()->renderUserList($this->associatedUsers, $this->receiver->userGuid);
}
if ($this->addCompetitiveDisclaimer) {
    //the disclaimer is injected to the role for correct positioning also we do not have to touch all client overwritten templates
    $params['role'] .= $this->translate->_('
<br/>
<br/><b>Warning:</b> Competing users: Only the first user to accept a job can perform it; the task is automatically removed from others.
<br/>');
}
echo $this->templateApply('{header}

In the project portal {portalLink}, a task was assigned to you.<br />
<br />
<b>Role:</b> {role}<br/>
{taskFragment}{reviewersFragment}{footer}', $params);
