<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2015 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3.0 requirements will be met:
 http://www.gnu.org/licenses/agpl.html

 There is a plugin exception available for use with this release of translate5 for
 open source applications that are distributed under a license other than AGPL:
 Please see Open Source License Exception for Development of Plugins for translate5
 http://www.translate5.net/plugin-exception.txt or as plugin-exception.txt in the root
 folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execptions
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/


$session = new Zend_Session_Namespace();
$vendor = $this->vendor;
$poData = $this->poData;

if($vendor->IsCompany){
    $vendorText = $vendor->FirstName.' '.$vendor->LastName.',';
}
else {
    $vendorText = $vendor->FirstName.' '.$vendor->LastName.',';
}

echo 'Dear '.$vendorText.'

'.($this->isEdit?'Your PO for this project has changed. The attached PO replaces the former PO with the same number.':'Attached please find your PO for this project.').'

Please quote your vendor number, the Project Manager, the PO number and the exact PO value on your invoice and send it to invoice@tmuebersetzungen.de

Kind regards,
'.$this->pmFirstName.' '.$this->pmSurName.'

----------------------------------------------------------------------------------
TransMission Übersetzungen GmbH
Hohnerstr. 23
70469 Stuttgart
Directors: Andrea Kunze, Katrin Gast
Registered: District Court Stuttgart HRB 724850
----------------------------------------------------------------------------------

Note: This is an automatically generated email.

“This email may contain confidential information and may be privileged. lf you are not the intended recipient please notify the sender immediately by sending the email back and delete it from your system. Unauthorized use or transfer of confidential information may have legal consequences.“
';
