<?php
/*
 START LICENSE AND COPYRIGHT
 
 This file is part of translate5
 
 Copyright (c) 2013 - 2015 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.
 
 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com
 
 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt
 included in the packaging of this file.  Please review the following information
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3.0 requirements will be met:
 http://www.gnu.org/licenses/agpl.html
 
 There is a plugin exception available for use with this release of translate5 for
 open source applications that are distributed under a license other than AGPL:
 Please see Open Source License Exception for Development of Plugins for translate5
 http://www.translate5.net/plugin-exception.txt or as plugin-exception.txt in the root
 folder of translate5.
 
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execptions
 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt
 
 END LICENSE AND COPYRIGHT
 */


$session = new Zend_Session_Namespace();
$vendor = $this->vendor;
$poData = $this->poData;

if($vendor->IsCompany){
    $vendorText = $vendor->FirstName.' '.$vendor->LastName.',';
}
else {
    $vendorText = $vendor->FirstName.' '.$vendor->LastName.',';
}

echo 'Hallo '.$vendorText.'

'.($this->isEdit?'ihre Auftragsbestätigung/PO hat sich geändert. Die PO im Anhang ersetzt die vorige PO mit derselben Nummer.':'im Anhang befindet sich die Auftragsbestätigung/PO für diesen Auftrag.').'

Bitte weisen Sie Ihre Lieferantennummer, den zuständigen Projektmanager, die Bestellnummer und den Auftragswert der PO auf Ihrer Rechnung aus und schicken diese an invoice@tmuebersetzungen.de.

Mit freundlichen Grüßen
'.$this->pmFirstName.' '.$this->pmSurName.'

----------------------------------------------------------------------------------
TransMission Übersetzungen GmbH
Hohnerstr. 23
70469 Stuttgart
Geschäftsführerinnen: Andrea Kunze, Katrin Gast
Amtsgericht Stuttgart - Registergericht HRB 724850
----------------------------------------------------------------------------------

Hinweis: Dies ist eine automatisch generierte E-Mail.

„Diese E-Mail kann vertrauliche Informationen enthalten. Wenn Sie nicht der rechtmäßige Empfänger sind, informieren Sie den Absender bitte unverzüglich durch Rücksendung der E-Mail und löschen Sie sie auf Ihrem System. Die unberechtigte Nutzung oder Weitergabe von vertraulichen Informationen kann straf- und zivilrechtlich verfolgt werden.“
';