-- /*
-- START LICENSE AND COPYRIGHT
-- 
--  This file is part of translate5
--  
--  Copyright (c) 2013 - 2017 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.
-- 
--  Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com
-- 
--  This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
--  as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
--  included in the packaging of this file.  Please review the following information 
--  to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
--  http://www.gnu.org/licenses/agpl.html
--   
--  There is a plugin exception available for use with this release of translate5 for
--  translate5: Please see http://www.translate5.net/plugin-exception.txt or 
--  plugin-exception.txt in the root folder of translate5.
--   
--  @copyright  Marc Mittag, MittagQI - Quality Informatics
--  @author     MittagQI - Quality Informatics
--  @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
-- 			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt
-- 
-- END LICENSE AND COPYRIGHT
-- */

UPDATE `LEK_languages` SET `rfc5646`='el' WHERE `rfc5646`='gr';
INSERT INTO `LEK_languages` (`rfc5646`, `langName`, `lcid`, `rtl`) VALUES
('af','Afrikaans',NULL,0),
('af-ZA','Afrikaans (Südafrika)',1078,0),
('ar','Arabisch',NULL,1),
('ar-AE','Arabisch (Vereinigte Arabische Emirate)',14337,1),
('ar-BH','Arabisch (Bahrain)',15361,1),
('ar-DZ','Arabisch (Algerien)',5121,1),
('ar-EG','Arabisch (Ägypten)',3073,1),
('ar-IQ','Arabisch (Irak)',2049,1),
('ar-JO','Arabisch (Jordanien)',11265,1),
('ar-KW','Arabisch (Kuwait)',13313,1),
('ar-LB','Arabisch (Libanon)',12289,1),
('ar-LY','Arabisch (Libyen)',4097,1),
('ar-MA','Arabisch (Marokko)',6145,1),
('ar-OM','Arabisch (Oman)',8193,1),
('ar-QA','Arabisch (Katar)',16385,1),
('ar-SA','Arabisch (Saudi-Arabien)',1025,1),
('ar-SY','Arabisch (Syrien)',10241,1),
('ar-TN','Arabisch (Tunesien)',7169,1),
('ar-YE','Arabisch (Jemen)',9217,1),
('az','Aserbaidschanisch (Latein)',NULL,0),
('Az-Cyrl','Aserbaidschanisch (Kyrillisch)',NULL,0),
('az-AZ','Aserbaidschanisch (Latein) (Aserbaidschan)',1068,0),
('az-Cyrl-AZ','Aserbaidschanisch (Kyrillisch) (Aserbaidschan)',2092,0),
('be','Weißrussisch',NULL,0),
('be-BY','Weißrussisch (Weißrussland)',1059,0),
('bg','Bulgarisch',NULL,0),
('bg-BG','Bulgarisch (Bulgarien)',1026,0),
('bn','Bengalisch',NULL,0),
('bo','Tibetisch',NULL,0),
('bs','Bosnisch',NULL,0),
('bs-BA','Bosnisch (Bosnien und Herzegowina)',NULL,0),
('ca','Katalanisch',NULL,0),
('ca-ES','Katalanisch (Spanien)',1027,0),
('cs','Tschechisch',NULL,0),
('cs-CZ','Tschechisch (Tschechien)',1029,0),
('cy','Walisisch',NULL,0),
('cy-GB','Walisisch (UK)',1106,0),
('da','Dänisch',NULL,0),
('da-DK','Dänisch (Dänemark)',1030,0),
('de','Deutsch',NULL,0),
('de-AT','Deutsch (Österreich)',3079,0),
('de-CH','Deutsch (Schweiz)',2055,0),
('de-DE','Deutsch (Deutschland)',1031,0),
('de-LI','Deutsch (Liechtenstein)',5127,0),
('de-LU','Deutsch (Luxemburg)',4103,0),
('dv','Dhivehi',NULL,1),
('dv-MV','Dhivehi (Malediven)',1125,1),
('ee','Estnisch',NULL,0),
('el','Griechisch',NULL,0),
('el-GR','Griechisch (Griechenland)',1032,0),
('en','Englisch',NULL,0),
('en-AU','Englisch (Australien)',3081,0),
('en-BZ','Englisch (Belize)',10249,0),
('en-CA','Englisch (Kanada)',4105,0),
('en-CB','Englisch (Karibik)',9225,0),
('en-GB','Englisch (UK)',2057,0),
('en-IE','Englisch (Irland)',6153,0),
('en-JM','Englisch (Jamaika)',8201,0),
('en-NZ','Englisch (Neuseeland)',5129,0),
('en-PH','Englisch (Philippinen)',13321,0),
('en-TT','Englisch (Trinidad und Tobego)',11273,0),
('en-US','Englisch (US)',1033,0),
('en-ZA','Englisch (Südafrika)',7177,0),
('en-ZW','Englisch (Simbabwe)',12297,0),
('eo','Esperanto',NULL,0),
('es','Spanisch',NULL,0),
('es-AR','Spanisch (Argentinien)',11274,0),
('es-BO','Spanisch (Bolivien)',16394,0),
('es-CL','Spanisch (Chile)',13322,0),
('es-CO','Spanisch (Kolumbien)',9226,0),
('es-CR','Spanisch (Costa Rica)',5130,0),
('es-DO','Spanisch (Dominikanische Republik)',7178,0),
('es-EC','Spanisch (Ecuador)',12298,0),
('es-ES','Spanisch (Spanien)',1034,0),
('es-GT','Spanisch (Guatemala)',4106,0),
('es-HN','Spanisch (Honduras)',18442,0),
('es-MX','Spanisch (Mexiko)',2058,0),
('es-NI','Spanisch (Nicaragua)',19466,0),
('es-PA','Spanisch (Panama)',6154,0),
('es-PE','Spanisch (Peru)',10250,0),
('es-PR','Spanisch (Puerto Rico)',20490,0),
('es-PY','Spanisch (Paraguay)',15370,0),
('es-SV','Spanisch (El Salvador)',17418,0),
('es-UY','Spanisch (Uruguay)',14346,0),
('es-VE','Spanisch (Venezuela)',8202,0),
('et','Estnisch',NULL,0),
('et-EE','Estnisch (Estland)',1061,0),
('eu','Baskisch',NULL,0),
('eu-ES','Baskisch (Spanien)',1069,0),
('fa','Persisch (Farsi)',NULL,1),
('fa-IR','Persisch (Iran)',1065,1),
('fi','Finnisch',NULL,0),
('fi-FI','Finnisch (Finnland)',1035,0),
('fo','Färöisch',NULL,0),
('fo-FO','Färöisch (Färöer)',1080,0),
('fr','Französisch',NULL,0),
('fr-BE','Französisch (Belgien)',2060,0),
('fr-CA','Französisch (Kanada)',3084,0),
('fr-CH','Französisch (Schweiz)',4108,0),
('fr-FR','Französisch (Frankreich)',1036,0),
('fr-LU','Französisch (Luxemburg)',5132,0),
('fr-MC','Französisch (Monaco)',6156,0),
('ga-IE','Gälisch (Irisch)',NULL,0),
('gl','Galicisch',NULL,0),
('gl-ES','Galicisch (Spanien)',1110,0),
('gu','Gujarati',NULL,0),
('gu-IN','Gujarati (Indien)',1095,0),
('he','Hebräische',NULL,1),
('he-IL','Hebräische (Israel)',1037,1),
('hi','Hindi',NULL,0),
('hi-IN','Hindi (Indien)',1081,0),
('hr','Kroatisch',NULL,0),
('hr-BA','Kroatisch (Bosnien und Herzegomina)',NULL,0),
('hr-HR','Kroatisch (Kroatien)',1050,0),
('hu','Ungarisch',NULL,0),
('hu-HU','Ungarisch (Ungarn)',1038,0),
('hy','Armenisch',NULL,0),
('hy-AM','Armenisch (Armenien)',1067,0),
('id','Indonesisch',NULL,0),
('id-ID','Indonesisch (Indonesien)',1057,0),
('ig','Igbo',NULL,0),
('is','Isländisch',NULL,0),
('is-IS','Isländisch (Island)',1039,0),
('it','Italienisch',NULL,0),
('it-CH','Italienisch (Schweiz)',2064,0),
('it-IT','Italienisch (Italien)',1040,0),
('ja','Japanisch',NULL,0),
('ja-JP','Japanisch (Japan)',1041,0),
('ka','Georgisch',NULL,0),
('ka-GE','Georgisch (Georigien)',1079,0),
('kk','Kasachisch',NULL,0),
('kk-KZ','Kasachisch (Kasachstan)',1087,0),
('km','Khmer',NULL,0),
('kn','Kannada',NULL,0),
('kn-IN','Kannada (Indien)',1099,0),
('ko','Koreanisch',NULL,0),
('ko-KR','Koreanisch (Korea)',1042,0),
('kok','Konkani',NULL,0),
('kok-IN','Konkani (Indien)',1111,0),
('ky','Kirgisisch',NULL,0),
('ky-KG','Kirgisisch (Kirgisistan)',1088,0),
('lt','Litauisch',NULL,0),
('lt-LT','Litauisch (Litauen)',1063,0),
('lv','Lettisch',NULL,0),
('lv-LV','Lettisch (Lettland)',1062,0),
('mi','Māori',NULL,0),
('mi-NZ','Māori (Neuseeland)',NULL,0),
('mk','Mazedonisch',NULL,0),
('mk-MK','Mazedonisch (Mazedonien)',1071,0),
('ml','Malayalam',NULL,0),
('mn','Mongolisch',NULL,0),
('mn-MN','Mongolisch (Mongolei)',1104,0),
('mo','Moldawisch',NULL,0),
('mr','Marathi',NULL,0),
('mr-IN','Marathi (Indien)',1102,0),
('ms','Malaysisch',NULL,0),
('ms-BN','Malaysisch (Brunei)',2110,0),
('ms-MY','Malaysisch (Malaysia)',1086,0),
('mt','Maltesisch',NULL,0),
('mt-MT','Maltesisch (Malta)',NULL,0),
('nb','Norwegisch (Bokmal)',NULL,0),
('nb-NO','Norwegisch (Bokmal) (Norwegen)',1044,0),
('nl','Niederländisch',NULL,0),
('nl-BE','Niederländisch (Belgien)',2067,0),
('nl-NL','Niederländisch (Niederlande)',1043,0),
('nn','Norwegisch (Nynorsk)',NULL,0),
('nn-NO','Norwegisch (Nynorsk) (Norwegen)',2068,0),
('ns','Nord-Sotho',NULL,0),
('ns-ZA','Nord-Sotho (Südafrika)',NULL,0),
('pa','Panjabi',NULL,0),
('pa-IN','Panjabi (Indien)',1094,0),
('pl','Polnisch',NULL,0),
('pl-PL','Polnisch (Polen)',1045,0),
('ps','Paschtu',NULL,1),
('ps-AR','Paschtu (Afghanistan)',NULL,1),
('pt','Portugiesisch',NULL,0),
('pt-BR','Portugiesisch (Brasilien)',1046,0),
('pt-PT','Portugiesisch (Portugal)',2070,0),
('qu','Quechua',NULL,0),
('qu-BO','Quechua (Bolivien)',NULL,0),
('qu-EC','Quechua (Ecuador)',NULL,0),
('qu-PE','Quechua (Peru)',NULL,0),
('ro','Rumänisch',NULL,0),
('ro-RO','Rumänisch (Rumänien)',1048,0),
('ru','Russisch',NULL,0),
('ru-RU','Russisch (Russland)',1049,0),
('sa','Sanskrit',NULL,0),
('sa-IN','Sanskrit (Indien)',1103,0),
('se','Samisch',NULL,0),
('se-FI','Samisch (Finnland)',NULL,0),
('se-NO','Samisch (Norwegen)',NULL,0),
('se-SE','Samisch (Schweden)',NULL,0),
('sk','Slowakisch',NULL,0),
('sk-SK','Slowakisch (Slowakei)',1051,0),
('sl','Slowenisch',NULL,0),
('sl-SI','Slowenisch (Slowenien)',1060,0),
('so','Somali',NULL,0),
('sq','Albanisch',NULL,0),
('sq-AL','Albanisch (Albanien)',1052,0),
('sr','Serbisch (Latein)',NULL,0),
('Sr-Cyrl','Serbisch (Kyrillisch)',NULL,0),
('sr-BA','Serbisch (Latein) (Bosnien und Herzegowina)',NULL,0),
('sr-Cyrl-BA','Serbisch (Kyrillisch) (Bosnien und Herzegowina)',NULL,0),
('sr-SP','Serbisch (Latein) (Serbien und Montenegro)',2074,0),
('sr-Cyrl-SP','Serbisch (Kyrillisch) (Serbien und Montenegro)',3098,0),
('st','Sesotho',NULL,0),
('sv','Schwedisch',NULL,0),
('sv-FI','Schwedisch (Finnland)',2077,0),
('sv-SE','Schwedisch (Schweden)',1053,0),
('sw','Suaheli',NULL,0),
('sw-KE','Suaheli (Kenia)',1089,0),
('syr','Syrisch',NULL,0),
('syr-SY','Syrisch (Syrien)',1114,0),
('ta','Tamilisch',NULL,0),
('ta-IN','Tamilisch (Indien)',1097,0),
('te','Telugu',NULL,0),
('te-IN','Telugu (Indien)',1098,0),
('tg','Tadschikisch',NULL,0),
('th','Thai',NULL,0),
('th-TH','Thai (Thailand)',1054,0),
('tk','Turkmenisch',NULL,0),
('tl','Tagalog',NULL,0),
('tl-PH','Tagalog (Philippinen)',NULL,0),
('tn','Tswana',NULL,0),
('tn-ZA','Tswana (Südafrika)',NULL,0),
('tr','Türkisch',NULL,0),
('tr-TR','Türkisch (Türkei)',1055,0),
('tt','Tatarisch',NULL,0),
('tt-RU','Tatarisch (Russland)',NULL,0),
('ts','Tsonga',NULL,0),
('uk','Ukrainisch',NULL,0),
('uk-UA','Ukrainisch (Ukraine)',1058,0),
('ur','Urdu',NULL,1),
('ur-PK','Urdu (Pakistan)',1056,1),
('uz','Usbekisch (Latein)',NULL,0),
('Uz-Cyrl','Usbekisch (Kyrillisch)',NULL,0),
('uz-UZ','Usbekisch (Latein) (Usbekistan)',1091,0),
('uz-Cyrl-UZ','Usbekisch (Kyrillisch) (Usbekistan)',2115,0),
('vi','Vietnamesisch',NULL,0),
('vi-VN','Vietnamesisch (Vietnam)',1066,0),
('xh','Xhosa',NULL,0),
('xh-ZA','Xhosa (Südafrika)',NULL,0),
('yo','Yoruba',NULL,0),
('zh','Chinesisch',NULL,0),
('zh-CN','Chinesisch vereinfacht',2052,0),
('zh-HK','Chinesisch (Hong Kong)',3076,0),
('zh-MO','Chinesisch (Macau)',5124,0),
('zh-SG','Chinesisch (Singapur)',4100,0),
('zh-TW','Chinesisch traditionell',1028,0),
('zu','Zulu',NULL,0),
('zu-ZA','Zulu (Südafrika)',NULL,0)
ON DUPLICATE KEY UPDATE
`langName`=VALUES(`langName`),
`lcid`=VALUES(`lcid`),
`rtl`=VALUES(`rtl`);
