
-- /*
-- START LICENSE AND COPYRIGHT
-- 
--  This file is part of translate5
--  
--  Copyright (c) 2013 - 2017 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.
-- 
--  Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com
-- 
--  This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
--  as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
--  included in the packaging of this file.  Please review the following information 
--  to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
--  http://www.gnu.org/licenses/agpl.html
--   
--  There is a plugin exception available for use with this release of translate5 for
--  translate5: Please see http://www.translate5.net/plugin-exception.txt or 
--  plugin-exception.txt in the root folder of translate5.
--   
--  @copyright  Marc Mittag, MittagQI - Quality Informatics
--  @author     MittagQI - Quality Informatics
--  @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
-- 			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt
-- 
-- END LICENSE AND COPYRIGHT
-- */

INSERT INTO `LEK_change_log` (`dateOfChange`, `jiraNumber`, `type`, `title`, `description`, `userGroup`) VALUES ('2019-11-12', 'TRANSLATE-1839', 'feature', 'Show some KPIs in translate5 task overview', 'One KPI is for example the average time until delivery of a task.', '12'),
('2019-11-12', 'TRANSLATE-1858', 'change', 'GroupShare TMs with several languages', 'Such TMs are listed now correctly.', '12'),
('2019-11-12', 'TRANSLATE-1849', 'change', 'OpenID Connect integration should be able to handle and merge roles from different groups for one user', 'OpenID Connect integration should be able to handle and merge roles from different groups for one user', '8'),
('2019-11-12', 'TRANSLATE-1848', 'change', 'define collection per user in automated term proposal export', 'the collections to be exported can be defined now', '8'),
('2019-11-12', 'TRANSLATE-1869', 'bugfix', 'Calling TermPortal without Session does not redirect to login', 'Now the user is redirected to the login page.', '12'),
('2019-11-12', 'TRANSLATE-1866', 'bugfix', 'TermPortal does not filter along termCollection, when showing terms of a termEntry', 'This is fixed now.', '8'),
('2019-11-12', 'TRANSLATE-1819', 'bugfix', 'TermPortal: comment is NOT mandatory when editing is canceled', 'TermPortal: comment is NOT mandatory when editing is canceled', '8'),
('2019-11-12', 'TRANSLATE-1865', 'bugfix', 'JS error when resetting segment to initial value', 'JS error when resetting segment to initial value', '8'),
('2019-11-12', 'TRANSLATE-1480', 'bugfix', 'JS Error on using search and replace', 'This is fixed now.', '8'),
('2019-11-12', 'TRANSLATE-1863', 'bugfix', 'InvalidXMLException: E1024 - Invalid XML does not bubble correctly into frontend on import', 'Now the error is logged and shown correctly', '12'),
('2019-11-12', 'TRANSLATE-1861', 'bugfix', 'Not all known default matchrate Icons are shown', 'All icons are shown again.', '14'),
('2019-11-12', 'TRANSLATE-1850', 'bugfix', 'Non userfriendly error on saving workflow user prefs with an already deleted user', 'A human readable error message is shown now.', '12'),
('2019-11-12', 'TRANSLATE-1860', 'bugfix', 'Error code error logging in visual review', 'Errors are now logged into the task log.', '12'),
('2019-11-12', 'TRANSLATE-1862', 'bugfix', 'Copy & Paste from outside the segment', 'Copy & Paste from outside the segment is now possible', '14'),
('2019-11-12', 'TRANSLATE-1857', 'bugfix', 'Some strings in the interface are shown in German', 'Translated the missing strings', '12'),
('2019-11-12', 'TRANSLATE-1363', 'bugfix', 'Ensure that search and replace can not be sent without field to be searched', 'The problem is fixed now', '8'),
('2019-11-12', 'TRANSLATE-1867', 'bugfix', 'TBX-Import: In TBX without termEntry-IDs terms get merged along autogenerated termEntry-ID', 'The generation of termEntry-ID was changed in the case the TBX does not provide such an ID.', '12'),
('2019-11-12', 'TRANSLATE-1552', 'bugfix', 'Auto set needed ACL roles', 'If a user gets the role pm, the editor role is needed too. Such missing roles are added now automatically.', '8'),
('2019-11-12', 'VISUAL-52', 'bugfix', 'Red bubble on changed alias segments in layout', 'Changed alias segments are now also shown as edited', '14'),
('2019-11-12', 'VISUAL-62', 'bugfix', 'Integrate PDF optimization via ghostscript to reduce font errors on HTML conversion', 'This must be activated in the config. If activated import errors of the PDF files should be reduced.', '8');