
-- /*
-- START LICENSE AND COPYRIGHT
--
--  This file is part of translate5
--
--  Copyright (c) 2013 - 2017 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.
--
--  Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com
--
--  This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
--  as published by the Free Software Foundation and appearing in the file agpl3-license.txt
--  included in the packaging of this file.  Please review the following information
--  to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
--  http://www.gnu.org/licenses/agpl.html
--
--  There is a plugin exception available for use with this release of translate5 for
--  translate5: Please see http://www.translate5.net/plugin-exception.txt or
--  plugin-exception.txt in the root folder of translate5.
--
--  @copyright  Marc Mittag, MittagQI - Quality Informatics
--  @author     MittagQI - Quality Informatics
--  @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
--              http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt
--
-- END LICENSE AND COPYRIGHT
-- */

-- userGroup calculation: basic: 1; editor: 2; pm: 4; admin: 8
            
INSERT INTO `LEK_change_log` (`dateOfChange`, `jiraNumber`, `type`, `title`, `description`, `userGroup`) VALUES ('2025-08-14', 'TRANSLATE-4784', 'feature', 'MatchAnalysis & Pretranslation - Uplifting fuzzy matches by looking what content protection tags we do not have in the fuzzy match', 'Improve fuzzy matches fetching for segments with content protection', '15'),
('2025-08-14', 'TRANSLATE-3569', 'feature', 'VisualReview / VisualTranslation - provide Visual for MS Office files via LibreOffice CMD', 'Added ability to have a visual from MS Office of LibreOffice-Files without having to upload the PDF version', '15'),
('2025-08-14', 'TRANSLATE-3118', 'feature', 'Editor general, usability editor - Rework Richtext Editor', 'The editing component in translate5\'s editor (the open segment) has been rewritten from the scratch. The old editing component was still written to support Internent Explorer 11. With it there were problems like jumping cursor in certain situations and other usability flaws. This is now solved. Also the new editing component moves now with the scrolling, a mulitply requested usability enhancement.', '15'),
('2025-08-14', 'TRANSLATE-4831', 'change', 'VisualReview / VisualTranslation - Visual: API-Test for the new Features (Print Visual, PDF-Import as Reflown HTML)', 'API-tests for the visual features "Export visual as PDF" and "Import PDF(s) as text-reflown HTML"', '15'),
('2025-08-14', 'TRANSLATE-4794', 'change', 'Editor general - Editor in grid is behind the row', 'Fixed bug with the editor which might have caused editing a segment to be impossible', '15'),
('2025-08-14', 'TRANSLATE-4778', 'change', 'file format settings - Add entities to File-Format-Settings to patch imported XML files', 'Added entities to File-Format-Settings to patch imported XML files', '15'),
('2025-08-14', 'TRANSLATE-4774', 'change', 'VisualReview / VisualTranslation, Workflows - Optionally attach visual printed to PDF into email to PM in "Review and print approval" workflow', 'Added optional attachment of visual printed to PDF into mail to PM in "Review and print approval" workflow', '15'),
('2025-08-14', 'TRANSLATE-4645', 'change', 'Import/Export - PDF Import/Export: Use HTML generated by Visual Reflow as source for a PDF workfile', 'VISUAL: Utilize the Visual Test-reflow as source for PDF imports optionally', '15'),
('2025-08-14', 'TRANSLATE-3717', 'change', 'usability editor - Enlarge opened editable segment, if text is too large for the field', 'Editor is now growing vertically if content is longer than the editor', '15'),
('2025-08-14', 'TRANSLATE-2183', 'change', 'SpellCheck (LanguageTool integration) - Cursor not inside segment after replacing spelling error or after pop-up points to tag error or when spell check adds decorations', 'Cursor is now inside the segment after applying a replacement suggested by spellcheck', '15'),
('2025-08-14', 'TRANSLATE-4867', 'bugfix', 'Client management - Zend_Db_Statement_Exception when loading customers', 'Fixed a bug when no customers were set to a language resource.', '15'),
('2025-08-14', 'TRANSLATE-4725', 'bugfix', 'Import/Export - Termcollections: outdated docs, endpoint fix', 'FIXED: TermCollections API problems solved, documentation updated', '15'),
('2025-08-14', 'TRANSLATE-3873', 'bugfix', 'Editor general - Integrate new rich text segment editor into translate5 overall editor', 'Integrated new rich text editor into segments grid in the way of how old one was integrated but except the scrolling behaviour so that roweditor panel is now scrolled with the grid', '15');