<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2021 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html
  
 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or 
 plugin-exception.txt in the root folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/* * #@+
 * @author Marc Mittag
 * @package portal
 * @version 2.0
 *
 */
/**
 * Generiert das allgemeine Layout
 *
 * - Achtung: Bei Hinzufügen weiterer Layoutelemente darauf achten, dass diese
 *   im Viewhelper View_Helper_DisableBodyLayout deaktiviert werden
 */
$config = Zend_Registry::get('config');
/* @var $config Zend_Config */

$version = '?v='.$this->appVersion;

$this->headLink()->prependStylesheet(APPLICATION_RUNDIR.'/modules/editor/instanttranslate/css/instanttranslate.css'.$version);

$jqueryPath = APPLICATION_RUNDIR.'/js/jquery-ui/jquery-ui-1.12.1';
$this->headLink()->prependStylesheet($jqueryPath.'/jquery-ui.min.css'.$version);

//$jqueryIconFontPath = APPLICATION_RUNDIR.'/js/jquery-ui/jquery-ui-iconfont-2.3.2';
//$this->headLink()->prependStylesheet($jqueryIconFontPath.'/jquery-ui-1.12.icon-font.min.css'.$version);
?>
<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php echo $this->headTitle() ?>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headStyle() ?>
        <link rel="shortcut icon" href="<?php echo APPLICATION_RUNDIR . $config->runtimeOptions->server->pathToIMAGES; ?>/favicon.ico" type="image/x-icon"/>
<?php echo $this->headScript() ?>
        <script src="<?php echo $jqueryPath; ?>/external/jquery/jquery.js<?php echo $version; ?>"></script>
        <script src="<?php echo $jqueryPath; ?>/jquery-ui.min.js<?php echo $version; ?>"></script>
    </head>
    <body class="instantTranslate">
        <?php
            echo $this->layout()->content;
        ?>
    </body>
</html>
