<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5

 Copyright (c) 2013 - 2021 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt
 included in the packaging of this file.  Please review the following information
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html

 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or
 plugin-exception.txt in the root folder of translate5.

 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
             http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/* @var $this Zend_View */
?>
  
Editor.controller.Localizer.addPluginInit('frontEndMessageBus', function() {
    Ext.define("Editor.locale.plugins.FrontEndMessageBus.controller.MessageBus", {
        override: "Editor.plugins.FrontEndMessageBus.controller.MessageBus",
        strings: {
            taskCloseTitle: '<?php echo $this->translate->_('Task closed in another window'); ?>',
            taskCloseMsg: '<?php echo $this->translate->_('You have closed the task in another window. Please close this window too, or reload it to reopen the task.'); ?>',
            taskCloseClose: '<?php echo $this->translate->_('Close'); ?>',
            taskCloseReload: '<?php echo $this->translate->_('Reopen'); ?>'
        }
    });

    Ext.define("Editor.locale.plugins.FrontEndMessageBus.controller.MultiUserUsage", {
        override: "Editor.plugins.FrontEndMessageBus.controller.MultiUserUsage",
        strings: {
            noConnection: '<?php echo $this->translate->_('You are experiencing connection problems. <br />Please check the stability of your Internet connection. <br />If you keep seeing this message, it may also indicate <br />that the WebSocket protocol (wss://) is blocked by your firewall.'); ?>',
            noConnectionSeg: '<?php echo $this->translate->_('Without a connection to the server, you cannot edit a segment.'); ?>',
            inUseTitle: '<?php echo $this->translate->_('Segment already in use'); ?>',
            inUseMsg: '<?php echo $this->translate->_('The selected segment is already in use by another user and cannot be opened.'); ?>',
            inUse: '<?php echo $this->translate->_('Another user was quicker and has currently locked the segment for editing.'); ?>',
            currentUser: '<?php echo $this->translate->_('Current editor'); ?>',
            editors: '<?php echo $this->translate->_('Editors:'); ?>',
            myself: '<?php echo $this->translate->_('Myself'); ?>',
            selectedBy: '<?php echo $this->translate->_('Selected by'); ?>',
            segmentChangedOnServerTitle: '<?= $this->translate->_('Segment was changed on server side') ?>',
            segmentChangedOnServerMessage: '<?= $this->translate->_('Segment was changed on server side.<br/><br/><b>Source text:</b><br/>{source}<br/><br/><b>Target text:</b><br/>{target}<br/><br/>Do you want to accept changes?'); ?>',
        }
    });
});
