<?php
/*
START LICENSE AND COPYRIGHT

 Copyright (c) 2013 - 2019 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file is part of a plug-in for translate5. 
 translate5 can be optained via the instructions that are linked at http://www.translate5.net
 For the license of translate5 itself please see http://www.translate5.net/license.txt
 For the license of this plug-in, please see below.
 
 This file is part of a plug-in for translate5 and may be used under the terms of the
 GNU GENERAL PUBLIC LICENSE version 3 as published by the Free Software Foundation and 
 appearing in the file gpl3-license.txt included in the packaging of the translate5 plug-in
 to which this file belongs. Please review the following information to ensure the 
 GNU GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/gpl.html
   
 There is a plugin exception available for use with this release of translate5 for 
 translate5 plug-ins that are distributed under GNU GENERAL PUBLIC LICENSE version 3: 
 Please see http://www.translate5.net/plugin-exception.txt or plugin-exception.txt in the
 root folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU GENERAL PUBLIC LICENSE version 3 with plugin-execption
			 http://www.gnu.org/licenses/gpl.html
			 http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/* @var $this Zend_View */
?>
  
Editor.controller.Localizer.addPluginInit('frontEndMessageBus', function() {
    Ext.define("Editor.locale.plugins.FrontEndMessageBus.controller.MultiUserUsage", {
        override: "Editor.plugins.FrontEndMessageBus.controller.MultiUserUsage",
        strings: {
            noConnection: '<?php echo $this->translate->_('Keine Verbindung zum Server');?>',
            noConnectionSeg: '<?php echo $this->translate->_('Sie können kein Segment editieren, so lange keine Verbindung zum Server besteht.');?>',
            inUseTitle: '<?php echo $this->translate->_('Segment bereits in Bearbeitung');?>',
            inUseMsg: '<?php echo $this->translate->_('Das ausgewählte Segment wird von einem anderen Benutzer bereits bearbeitet und kann daher nicht geöffnet werden.');?>',
            inUse: '<?php echo $this->translate->_('Ein anderer Benutzer war schneller und hat im Moment das Segment zur Bearbeitung gesperrt.');?>',
            currentUser: '<?php echo $this->translate->_('Aktueller Bearbeiter');?>',
            editors: '<?php echo $this->translate->_('Bearbeiter: ');?>',
            myself: '<?php echo $this->translate->_('Ich');?>',
            selectedBy: '<?php echo $this->translate->_('Ausgewählt von');?>'
        }
    });
});
