<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2017 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html
  
 There is a plugin exception available for use with this release of translate5 for
 translate5 plug-ins that are distributed under GNU AFFERO GENERAL PUBLIC LICENSE version 3:
 Please see http://www.translate5.net/plugin-exception.txt or plugin-exception.txt in the root
 folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/**#@+
 * @author Marc Mittag
 * @package portal
 * @version 2.0
 *
 */

$session = new Zend_Session_Namespace();
$portal = $session->runtimeOptions->server->protocol.$session->runtimeOptions->server->name;

$data = [
    'portalLink' => '<a href="'.$portal.'">'.$portal.'</a>',
    'companyName' => $session->runtimeOptions->companyName,
    'salutation' => $this->mailEmployeeSalutation(),
    'surName' => $this->user->surName,
];
    
$this->header = $this->templateApply('{salutation} {surName},<br />
<br />', $data);

$this->footer = $this->templateApply('<br />
<br />Vielen Dank und viele Grüße,
<br />Ihr Projektmanagement Team
<br />{companyName}
<br />
<br />Diese Email wurde automatisch generiert. Bitte antworten Sie nicht auf diese E-Mail!', $data);

