<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5

 Copyright (c) 2013 - 2024 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt
 included in the packaging of this file.  Please review the following information
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html

 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or
 plugin-exception.txt in the root folder of translate5.

 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
             http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/* @var $this Zend_View */
$this->render('general.phtml');

$this->subject = $this->translate->_('Translate5 - Aufgabe automatisch abgeschlossen') . ': ' . $this->task->getTaskName();

//is automatically merged with data from general.phtml
$data = [
    'header' => $this->header,
    'body' => sprintf(
        $this->translate->_('Die Aufgabe %s wurde von translate5 automatisch abgeschlossen und ist nicht mehr bearbeitbar. Bei Fragen wenden Sie sich bitte an Ihr Projektmanagement-Team.'),
        $this->task->getTaskName()
    ),
    'footer' => $this->footer,
];

$mailBody = $this->templateApply('{header}{body}{footer}', $data);

$this->textbody = strip_tags($mailBody);
echo $mailBody;
