<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2015 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3.0 requirements will be met:
 http://www.gnu.org/licenses/agpl.html

 There is a plugin exception available for use with this release of translate5 for
 open source applications that are distributed under a license other than AGPL:
 Please see Open Source License Exception for Development of Plugins for translate5
 http://www.translate5.net/plugin-exception.txt or as plugin-exception.txt in the root
 folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execptions
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/* @var $this Zend_View */
?>
  
  Editor.controller.Localizer.addPluginInit('matchResource', function() {
  
  
    Ext.define("Editor.locale.plugins.MatchResource.controller.Editor", {
        override: "Editor.plugins.MatchResource.controller.Editor",
        msgDisabledMatchRate: '<?php echo $this->translate->_('Das Projekt enthält alternative Übersetzungen. Bei der Übernahme von Matches wird die Segment Matchrate daher nicht verändert.');?>'
    });
    Ext.define("Editor.locale.plugins.MatchResource.view.MatchGridViewController", {
        override: "Editor.plugins.MatchResource.view.MatchGridViewController",
        strings: {
            serverErrorMsgDefault: '<?php echo $this->translate->_('Die Anfrage an die Match Resource dauerte zu lange.');?>',
            serverErrorMsg500:'<?php echo $this->translate->_('Die Anfrage führte zu einem Fehler im angefragten Dienst.');?>',
        	serverErrorMsg408:'<?php echo $this->translate->_('Request Timeout');?>',
        }
    });
    Ext.define("Editor.locale.plugins.MatchResource.view.EditorPanel", {
        override: "Editor.plugins.MatchResource.view.EditorPanel",
        strings: {
            searchTitle: '<?php echo $this->translate->_('Konkordanzsuche');?>',
            matchTitle:'<?php echo $this->translate->_('Match Ergebnisse');?>',
        	sourceEmptyText:'<?php echo $this->translate->_('Quelltextsuche');?>',
        	targetEmptyText:'<?php echo $this->translate->_('Zieltextsuche');?>',
        }
    });
  });