<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2017 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html
  
 There is a plugin exception available for use with this release of translate5 for
 translate5 plug-ins that are distributed under GNU AFFERO GENERAL PUBLIC LICENSE version 3:
 Please see http://www.translate5.net/plugin-exception.txt or plugin-exception.txt in the root
 folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/* @var $this Zend_View */
?>
  
  Editor.controller.Localizer.addPluginInit('matchResource', function() {
  
    Ext.define("Editor.locale.plugins.MatchResource.controller.Editor", {
        override: "Editor.plugins.MatchResource.controller.Editor",
        strings: {
            msgDisabledMatchRate: '<?php echo $this->translate->_('Das Projekt enthält alternative Übersetzungen. Bei der Übernahme von Matches wird die Segment Matchrate daher nicht verändert.');?>',
            msgDisabledSourceEdit: '<?php echo $this->translate->_('Beim Bearbeiten der Quellspalte können Matches nicht übernommen werden.');?>'
        }
    });
    
    Ext.define("Editor.locale.plugins.MatchResource.controller.TaskAssoc", {
        override: "Editor.plugins.MatchResource.controller.TaskAssoc",
        strings: {
            assocSave: '<?php echo $this->translate->_('Eintrag gespeichert!');?>',
            assocDeleted: '<?php echo $this->translate->_('Eintrag gelöscht!');?>',
            assocSaveError: '<?php echo $this->translate->_('Fehler beim Speichern der Änderungen!');?>'
        }
    });
    
    Ext.define("Editor.locale.plugins.MatchResource.controller.TmOverview", {
        override: "Editor.plugins.MatchResource.controller.TmOverview",
        strings: {
            matchresource: '<?php echo $this->translate->_('Matchressourcen');?>',
            deleteConfirm: '<?php echo $this->translate->_('Matchressource endgültig löschen?');?>',
            deleteConfirmText: '<?php echo $this->translate->_('Soll die gewählte Matchressource "{0}" wirklich endgültig gelöscht werden?');?>',
            deleteConfirmLocal: '<?php echo $this->translate->_('Matchressource löschen?');?>',
            deleteConfirmLocalText: '<?php echo $this->translate->_('Soll die gewählte Matchressource "{0}" aus der Liste der hier angezeigten Matchressourcen gelöscht werden? <br /> Es werden keine Daten im verknüpften TM System gelöscht, da keine Verbindung besteht.');?>',
            deleted: '<?php echo $this->translate->_('Matchressource gelöscht.');?>',
            edited: '<?php echo $this->translate->_('Die Matchressource "{0}" wurde erfolgreich geändert.');?>',
            created: '<?php echo $this->translate->_('Die Matchressource "{0}" wurde erfolgreich erstellt.');?>',
            noResourcesAssigned: '<?php echo $this->translate->_('Keine Matchressourcen zugewiesen.');?>',
            taskassocgridcell: '<?php echo $this->translate->_('Zugewiesene Matchressourcen');?>',
            exportTm: '<?php echo $this->translate->_('als TM Datei exportieren');?>',
            exportTmx: '<?php echo $this->translate->_('als TMX Datei exportieren');?>'
        }
    });
    
    Ext.define("Editor.locale.plugins.MatchResource.view.MatchGridViewController", {
        override: "Editor.plugins.MatchResource.view.MatchGridViewController",
        strings: {
            loading: '<?php echo $this->translate->_('wird geladen...');?>',
            noresults: '<?php echo $this->translate->_('Es wurden keine Ergebnisse gefunden.');?>',
            serverErrorMsgDefault: '<?php echo $this->translate->_('Die Anfrage an die Matchressource dauerte zu lange.');?>',
            serverErrorMsg500:'<?php echo $this->translate->_('Die Anfrage führte zu einem Fehler im angefragten Dienst.');?>',
            serverErrorMsg408:'<?php echo $this->translate->_('Die Anfrage an die Matchressource dauerte zu lange.');?>',
        }
    });
    Ext.define("Editor.locale.plugins.MatchResource.view.SearchGridViewController", {
        override: "Editor.plugins.MatchResource.view.SearchGridViewController",
        strings: {
            loading: '<?php echo $this->translate->_('wird geladen...');?>',
            noresults: '<?php echo $this->translate->_('Es wurden keine Ergebnisse gefunden.');?>',
            searchResultGridTitle: '<?php echo $this->translate->_('{0} Ergebnisse');?>',
            serverErrorMsgDefault: '<?php echo $this->translate->_('Die Anfrage an die Matchressource dauerte zu lange.');?>',
            serverErrorMsg500:'<?php echo $this->translate->_('Die Anfrage führte zu einem Fehler im angefragten Dienst.');?>',
            serverErrorMsg408:'<?php echo $this->translate->_('Die Anfrage an die Matchressource dauerte zu lange.');?>',
        }
    });
    
    Ext.define("Editor.locale.plugins.MatchResource.view.AddTmWindow", {
        override: "Editor.plugins.MatchResource.view.AddTmWindow",
        strings: {
            add: '<?php echo $this->translate->_('Matchressource hinzufügen');?>',
            resource: '<?php echo $this->translate->_('Ressource');?>',
            name: '<?php echo $this->translate->_('Name');?>',
            source: '<?php echo $this->translate->_('Quellsprache');?>',
            target: '<?php echo $this->translate->_('Zielsprache');?>',
            file: '<?php echo $this->translate->_('TM/TMX-Datei (optional)');?>',
            importTmxType: '<?php echo $this->translate->_('Bitte verwenden Sie eine TM oder TMX Datei!');?>',
            color: '<?php echo $this->translate->_('Farbe');?>',
            colorTooltip: '<?php echo $this->translate->_('Farbe dieser Matchressource');?>',
            save: '<?php echo $this->translate->_('Speichern');?>',
            cancel: '<?php echo $this->translate->_('Abbrechen');?>'
        }
    });
    
    Ext.define("Editor.locale.plugins.MatchResource.view.EditTmWindow", {
        override: "Editor.plugins.MatchResource.view.EditTmWindow",
        strings: {
            edit: '<?php echo $this->translate->_('Matchressource bearbeiten');?>',
            resource: '<?php echo $this->translate->_('Ressource');?>',
            name: '<?php echo $this->translate->_('Name');?>',
            source: '<?php echo $this->translate->_('Quellsprache');?>',
            target: '<?php echo $this->translate->_('Zielsprache');?>',
            file: '<?php echo $this->translate->_('TM-Datei');?>',
            color: '<?php echo $this->translate->_('Farbe');?>',
            colorTooltip: '<?php echo $this->translate->_('Farbe dieser Matchressource');?>',
            save: '<?php echo $this->translate->_('Speichern');?>',
            cancel: '<?php echo $this->translate->_('Abbrechen');?>'
        }
    });
    
    Ext.define("Editor.locale.plugins.MatchResource.view.EditorPanel", {
        override: "Editor.plugins.MatchResource.view.EditorPanel",
        strings: {
            searchTitle: '<?php echo $this->translate->_('Konkordanzsuche');?>',
            matchTitle:'<?php echo $this->translate->_('Matches');?>',
            sourceEmptyText:'<?php echo $this->translate->_('Quelltextsuche');?>',
            targetEmptyText:'<?php echo $this->translate->_('Zieltextsuche');?>',
            panelTitle:'<?php echo $this->translate->_('Matches und Konkordanz-Suche');?>',
        }
    });
    
    Ext.define("Editor.locale.plugins.MatchResource.view.MatchGrid", {
        override: "Editor.plugins.MatchResource.view.MatchGrid",
        strings: {
            source: '<?php echo $this->translate->_('Quelltext');?>',
            target: '<?php echo $this->translate->_('Zieltext');?>',
            match: '<?php echo $this->translate->_('Matchrate');?>',
            ctrl: '<?php echo $this->translate->_('STRG');?>',
            tooltipMsg: '<?php echo $this->translate->_('Diesen Match in das geöffnete Segment übernehmen.');?>',
            atributeTooltipMsg: '<?php echo $this->translate->_('Attribute:');?>',
            lastEditTooltipMsg: '<?php echo $this->translate->_('letzte Änderung:');?>',
            createdTooltipMsg: '<?php echo $this->translate->_('erstellt:');?>'
        }
    });
    
    Ext.define("Editor.locale.plugins.MatchResource.view.SearchGrid", {
        override: "Editor.plugins.MatchResource.view.SearchGrid",
        strings: {
            source: '<?php echo $this->translate->_('Quelltext');?>',
            target: '<?php echo $this->translate->_('Zieltext');?>',
            match: '<?php echo $this->translate->_('Matchrate');?>',
            ctrl: '<?php echo $this->translate->_('STRG');?>',
            tmresource: '<?php echo $this->translate->_('TM-Ressource');?>',
            sourceEmptyText:'<?php echo $this->translate->_('Quelltextsuche');?>',
            targetEmptyText:'<?php echo $this->translate->_('Zieltextsuche');?>',
            search:'<?php echo $this->translate->_('Alle durchsuchen');?>',
            singleSearch:'<?php echo $this->translate->_('Suche in {0}');?>'
        }
    });
    
    Ext.define("Editor.locale.plugins.MatchResource.view.TaskAssocPanel", {
        override: "Editor.plugins.MatchResource.view.TaskAssocPanel",
        title: '<?php echo $this->translate->_('Matchressourcen zuweisen');?>',
        strings: {
            reload: '<?php echo $this->translate->_('Aktualisieren');?>',
            save: '<?php echo $this->translate->_('Speichern');?>',
            empty: '<?php echo $this->translate->_('Keine Matchressource in der Sprachkombination des geöffneten Tasks verfügbar.');?>',
            groupHeader: '<?php echo $this->translate->_('Ressource: {name}');?>',
            checked: '<?php echo $this->translate->_('Ressource in Aufgabe verwenden');?>',
            name: '<?php echo $this->translate->_('Name');?>',
            segmentsUpdateable: '<?php echo $this->translate->_('Segmente zurückspeichern');?>',
            source: '<?php echo $this->translate->_('Quellsprache');?>',
            target: '<?php echo $this->translate->_('Zielsprache');?>'
        }
    });
    
    Ext.define("Editor.locale.plugins.MatchResource.view.TmOverviewPanel", {
        override: "Editor.plugins.MatchResource.view.TmOverviewPanel",
        title: '<?php echo $this->translate->_('Matchressourcen');?>',
        strings: {
            name: '<?php echo $this->translate->_('Name');?>',
            edit: '<?php echo $this->translate->_('Bearbeiten');?>',
            erase: '<?php echo $this->translate->_('Löschen');?>',
            download: '<?php echo $this->translate->_('Dateibasiertes TM herunterladen und lokal speichern');?>',
            resource: '<?php echo $this->translate->_('Ressource');?>',
            refresh: '<?php echo $this->translate->_('Aktualisieren');?>',
            color: '<?php echo $this->translate->_('Farbe');?>',
            add: '<?php echo $this->translate->_('Hinzufügen');?>',
            import: '<?php echo $this->translate->_('Weitere TM Daten in Form einer TMX Datei importieren und dem TM hinzufügen');?>',
            noTaskAssigned: '<?php echo $this->translate->_('Keine Aufgaben zugewiesen.');?>',
            sourceLang: '<?php echo $this->translate->_('Quellsprache');?>',
            targetLang: '<?php echo $this->translate->_('Zielsprache');?>',
            tmmtStatusColumn: '<?php echo $this->translate->_('Status');?>',
            tmmtStatus: {
                loading: '<?php echo $this->translate->_('Statusinformationen werden geladen');?>',
                error: '<?php echo $this->translate->_('Fehler');?>',
                available: '<?php echo $this->translate->_('verfügbar');?>',
                unknown: '<?php echo $this->translate->_('unbekannt');?>',
                noconnection: '<?php echo $this->translate->_('Keine Verbindung!');?>',
                import: '<?php echo $this->translate->_('importiert');?>',
                notloaded: '<?php echo $this->translate->_('verfügbar');?>'
            },
            taskassocgridcell: '<?php echo $this->translate->_('Zugewiesene Aufgaben');?>'
        }
    });
    
    Ext.define("Editor.locale.plugins.MatchResource.view.ImportTmWindow", {
        override: "Editor.plugins.MatchResource.view.ImportTmWindow",
        title: '<?php echo $this->translate->_('Matchressourcen');?>',
        strings: {
            file: '<?php echo $this->translate->_('TMX-Datei');?>',
            title: '<?php echo $this->translate->_('TMX Datei importieren');?>',
            importTmx: '<?php echo $this->translate->_('Weitere TM Daten in Form einer TMX Datei importieren und dem bestehenden TM hinzufügen');?>',
            importTmxType: '<?php echo $this->translate->_('Bitte verwenden Sie eine TMX Datei!');?>',
            importSuccess: '<?php echo $this->translate->_('Weitere TM Daten erfolgreich importiert!');?>',
            save: '<?php echo $this->translate->_('Speichern');?>',
            cancel: '<?php echo $this->translate->_('Abbrechen');?>'
        }
    });
});