<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2015 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3.0 requirements will be met:
 http://www.gnu.org/licenses/agpl.html

 There is a plugin exception available for use with this release of translate5 for
 open source applications that are distributed under a license other than AGPL:
 Please see Open Source License Exception for Development of Plugins for translate5
 http://www.translate5.net/plugin-exception.txt or as plugin-exception.txt in the root
 folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execptions
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/* @var $this Zend_View */
?>
  
  Editor.controller.Localizer.addPluginInit('matchResource', function() {
  
    Ext.define("Editor.locale.plugins.MatchResource.controller.Editor", {
        override: "Editor.plugins.MatchResource.controller.Editor",
        msgDisabledMatchRate: '<?php echo $this->translate->_('Das Projekt enthält alternative Übersetzungen. Bei der Übernahme von Matches wird die Segment Matchrate daher nicht verändert.');?>'
    });
    
    Ext.define("Editor.locale.plugins.MatchResource.controller.TaskAssoc", {
        override: "Editor.plugins.MatchResource.controller.TaskAssoc",
        strings: {
            assocSave: '<?php echo $this->translate->_('Eintrag gespeichert!');?>',
            assocDeleted: '<?php echo $this->translate->_('Eintrag gelöscht!');?>',
            assocSaveError: '<?php echo $this->translate->_('Fehler beim Speichern der Änderungen!');?>'
        }
    });
    
    Ext.define("Editor.locale.plugins.MatchResource.controller.TmOverview", {
        override: "Editor.plugins.MatchResource.controller.TmOverview",
        strings: {
            matchresource: '<?php echo $this->translate->_('Matchressourcen');?>',
            deleteConfirm: '<?php echo $this->translate->_('Matchressource endgültig löschen?');?>',
            deleteConfirmText: '<?php echo $this->translate->_('Soll die gewählte Matchressource "{0}" wirklich endgültig gelöscht werden?');?>',
            deleted: '<?php echo $this->translate->_('Matchressource gelöscht.');?>',
            edited: '<?php echo $this->translate->_('Die Matchressource "{0}" wurde erfolgreich geändert.');?>',
            created: '<?php echo $this->translate->_('Die Matchressource "{0}" wurde erfolgreich erstellt.');?>'
        }
    });
    
    Ext.define("Editor.locale.plugins.MatchResource.view.MatchGridViewController", {
        override: "Editor.plugins.MatchResource.view.MatchGridViewController",
        strings: {
            loading: '<?php echo $this->translate->_('wird geladen...');?>',
            noresults: '<?php echo $this->translate->_('Es wurden keine Ergebnisse gefunden.');?>',
            serverErrorMsgDefault: '<?php echo $this->translate->_('Die Anfrage an die Matchressource dauerte zu lange.');?>',
            serverErrorMsg500:'<?php echo $this->translate->_('Die Anfrage führte zu einem Fehler im angefragten Dienst.');?>',
            serverErrorMsg408:'<?php echo $this->translate->_('Die Anfrage an die Matchressource dauerte zu lange.');?>',
        }
    });
    Ext.define("Editor.locale.plugins.MatchResource.view.SearchGridViewController", {
        override: "Editor.plugins.MatchResource.view.SearchGridViewController",
        strings: {
            loading: '<?php echo $this->translate->_('wird geladen...');?>',
            noresults: '<?php echo $this->translate->_('Es wurden keine Ergebnisse gefunden.');?>',
            serverErrorMsgDefault: '<?php echo $this->translate->_('Die Anfrage an die Matchressource dauerte zu lange.');?>',
            serverErrorMsg500:'<?php echo $this->translate->_('Die Anfrage führte zu einem Fehler im angefragten Dienst.');?>',
            serverErrorMsg408:'<?php echo $this->translate->_('Die Anfrage an die Matchressource dauerte zu lange.');?>',
        }
    });
    Ext.define("Editor.locale.plugins.MatchResource.view.AddTmWindow", {
        override: "Editor.plugins.MatchResource.view.AddTmWindow",
        strings: {
            add: '<?php echo $this->translate->_('Matchressource hinzufügen');?>',
            resource: '<?php echo $this->translate->_('Ressource');?>',
            name: '<?php echo $this->translate->_('Name');?>',
            source: '<?php echo $this->translate->_('Quellsprache');?>',
            target: '<?php echo $this->translate->_('Zielsprache');?>',
            file: '<?php echo $this->translate->_('TM-Datei');?>',
            color: '<?php echo $this->translate->_('Farbe');?>',
            colorTooltip: '<?php echo $this->translate->_('Farbe welche für diese Match Resource verwendet wird');?>',
            save: '<?php echo $this->translate->_('Speichern');?>',
            cancel: '<?php echo $this->translate->_('Abbrechen');?>'
        }
    });
    
    Ext.define("Editor.locale.plugins.MatchResource.view.EditorPanel", {
        override: "Editor.plugins.MatchResource.view.EditorPanel",
        strings: {
            searchTitle: '<?php echo $this->translate->_('Konkordanzsuche');?>',
            matchTitle:'<?php echo $this->translate->_('Matchergebnisse');?>'
        }
    });
    
    Ext.define("Editor.locale.plugins.MatchResource.view.MatchGrid", {
        override: "Editor.plugins.MatchResource.view.MatchGrid",
        strings: {
            source: '<?php echo $this->translate->_('Quelltext');?>',
            target: '<?php echo $this->translate->_('Zieltext');?>',
            match: '<?php echo $this->translate->_('Matchrate');?>',
            tooltipMsg: '<?php echo $this->translate->_('Diesen Match in das geöffnete Segment übernehmen.');?>',
            atributeTooltipMsg: '<?php echo $this->translate->_('Attribute:');?>',
            lastEditTooltipMsg: '<?php echo $this->translate->_('letzte Änderung:');?>',
            createdTooltipMsg: '<?php echo $this->translate->_('erstellt:');?>'
        }
    });
    
    Ext.define("Editor.locale.plugins.MatchResource.view.SearchGrid", {
        override: "Editor.plugins.MatchResource.view.SearchGrid",
        strings: {
            source: '<?php echo $this->translate->_('Quelltext');?>',
            target: '<?php echo $this->translate->_('Zieltext');?>',
            match: '<?php echo $this->translate->_('Matchrate');?>',
            tmresource: '<?php echo $this->translate->_('TM-Ressource');?>',
            sourceEmptyText:'<?php echo $this->translate->_('Quelltextsuche');?>',
            targetEmptyText:'<?php echo $this->translate->_('Zieltextsuche');?>'
        }
    });
    
    Ext.define("Editor.locale.plugins.MatchResource.view.SearchResultGrid", {
        override: "Editor.plugins.MatchResource.view.SearchResultGrid",
        strings: {
            source: '<?php echo $this->translate->_('Quelltext');?>',
            target: '<?php echo $this->translate->_('Zieltext');?>',
            match: '<?php echo $this->translate->_('Matchrate');?>',
            tmresource: '<?php echo $this->translate->_('TM-Ressource');?>'
        }
    });
    
    Ext.define("Editor.locale.plugins.MatchResource.view.TaskAssocPanel", {
        override: "Editor.plugins.MatchResource.view.TaskAssocPanel",
        title: '<?php echo $this->translate->_('Matchressourcen zuweisen');?>',
        strings: {
            reload: '<?php echo $this->translate->_('Aktualisieren');?>',
            save: '<?php echo $this->translate->_('Speichern');?>',
            empty: '<?php echo $this->translate->_('Keine Match Resource in der Sprachkombination des geöffneten Tasks verfügbar.');?>',
            groupHeader: '<?php echo $this->translate->_('Dienst: {name}');?>',
            name: '<?php echo $this->translate->_('Name');?>',
            source: '<?php echo $this->translate->_('Quellsprache');?>',
            target: '<?php echo $this->translate->_('Zielsprache');?>'
        }
    });
    
    Ext.define("Editor.locale.plugins.MatchResource.view.TmOverviewPanel", {
        override: "Editor.plugins.MatchResource.view.TmOverviewPanel",
        title: '<?php echo $this->translate->_('Matchressourcen');?>',
        strings: {
            name: '<?php echo $this->translate->_('Name');?>',
            edit: '<?php echo $this->translate->_('Bearbeiten');?>',
            erase: '<?php echo $this->translate->_('Löschen');?>',
            resource: '<?php echo $this->translate->_('Ressource');?>',
            refresh: '<?php echo $this->translate->_('Aktualisieren');?>',
            color: '<?php echo $this->translate->_('Farbe');?>',
            add: '<?php echo $this->translate->_('hinzufügen');?>'
        }
    });
    
});