<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5

 Copyright (c) 2013 - 2021 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt
 included in the packaging of this file.  Please review the following information
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html

 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or
 plugin-exception.txt in the root folder of translate5.

 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
             http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

$this->render('general.phtml');

//Define Action String
$this->subject = $this->translate->_('translate5 – task partly finished') . ' "' . $this->task->getTaskNr() . ' - ' . $this->task->getTaskName() . '"';
$action = $this->templateApply('In the project portal , the task {task.taskNr} {portalLink}, the task <b>{task.taskNr} – {task.taskName}</b> has been completed by a user of the role <i>{currentRole}</i>:<br />', [
    'task' => $this->task->getDataObject(),
    'currentRole' => $this->translate->_($this->triggeringStep),
]);

//list of current users:
$usersCurrentText = $this->templateApply('All users with the current role <i>{currentRole}</i>:
{currentUsers}<br/>', [
    'currentUsers' => $this->htmlOnly,
]) . "\n";
$usersCurrentHTML = $this->templateApply('All users with the current role <i>{currentRole}</i>:
{currentUsers}<br/>', [
    'currentUsers' => $this->workflowNotifyMail()->renderUserList($this->currentUsers),
]) . "\n";

//create text body
$this->textbody = strip_tags($this->templateApply('{header}
{action}<br />
{currentUser}<br />
<br />
{usersCurrentRole}<br />
{footer}', [
    'header' => $this->header,
    'footer' => $this->footer,
    'action' => $action,
    'currentUser' => $this->htmlOnly,
    'usersCurrentRole' => $usersCurrentText,
]));

echo $this->templateApply('{header}
{action}<br />
{currentUser}<br />
<br />
{usersCurrentRole}<br />
{footer}', [
    'currentUser' => empty($this->currentUser) ? '' : $this->workflowNotifyMail()->renderUserList([$this->currentUser]),
    'usersCurrentRole' => $usersCurrentHTML,
]);
