<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5

 Copyright (c) 2013 - 2021 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt
 included in the packaging of this file.  Please review the following information
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html

 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or
 plugin-exception.txt in the root folder of translate5.

 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
             http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/** @var ZfExtended_View $this */

$this->render('general.phtml');

//Define Action String
if ($this->isCron) {
    $this->subject = $this->translate->_('translate5 – task finished automatically') . ' "' . $this->task->getTaskNr() . ' - ' . $this->task->getTaskName() . '"';
    $action = $this->templateApply('In the project portal {portalLink}, the task {task.taskNr} <b>{task.taskNr} – {task.taskName}</b> was automatically finished for all users of the role <i>{previousRole}</i> due to a deadline overrun.<br />', [
        'task' => $this->task->getDataObject(),
        'previousRole' => $this->translate->_($this->triggeringStep),
    ]);
} else {
    $this->subject = $this->translate->_('Translate5 – task finished') . ' "' . $this->task->getTaskNr() . ' - ' . $this->task->getTaskName() . '"';
    $action = $this->templateApply('In the project portal {portalLink}, the task {task.taskNr} <b>{task.taskNr} – {task.taskName}</b> has been completed by all users in the role <i>{previousRole}</i>.<br />', [
        'task' => $this->task->getDataObject(),
        'previousRole' => $this->translate->_($this->triggeringStep),
    ]);
}

//Define User List of next role users
if (empty($this->nextStep) && in_array($this->triggeringStep, $this->workflow->getSteps())) {
    $userNotificationHTML = $this->templateApply('The task has been fully processed, no further users are assigned to the task.') . "<br/>\n<br/>\n";
    $userNotificationText = $this->templateApply('The task has been fully processed, no further users are assigned to the task.', [
        'userList' => $this->htmlOnly,
    ]) . "<br/>\n<br/>\n";
} elseif (! empty($this->nextStep) && in_array($this->triggeringStep, $this->workflow->getSteps())) {
    //Fucking here up with role and step. Since in the heavily overwritten texts we still have nextRole we set the nextStep just the into the nextRole param
    $userNotificationHTML = $this->templateApply('The task has now automatically been made available to the following users with the role <i>{nextRole}</i>:<br />
{userList}<br />
The users have been informed accordingly via e-mail.', [
        'nextRole' => $this->translate->_($this->nextStep),
        'userList' => $this->workflowNotifyMail()->renderUserList($this->users),
    ]) . "<br/>\n<br/>\n";
    $userNotificationText = $this->templateApply('The task has now automatically been made available to the following users with the role <i>{nextRole}</i>:<br />
{userList}<br />
The users have been informed accordingly via e-mail.', [
        'userList' => $this->htmlOnly,
    ]) . "<br/>\n<br/>\n";
} else {
    $userNotificationHTML = $this->templateApply('The role <i>{previousRole}</i> was not part of this workflow, therefore, no further users were notified.') . "<br/>\n<br/>\n";
    $userNotificationText = $this->templateApply(
        'The role <i>{previousRole}</i> was not part of this workflow, therefore, no further users were notified.',
        [
            'userList' => $this->htmlOnly,
        ]
    ) . "<br/>\n<br/>\n";
}

//list of previous users:
$userPreviousText = $this->templateApply('Users of previous role <i>{previousRole}</i>:
{previousUsers}<br/>', [
    'previousUsers' => $this->htmlOnly,
]) . "\n";
$userPreviousHTML = $this->templateApply('Users of previous role <i>{previousRole}</i>:
{previousUsers}<br/>', [
    'previousUsers' => $this->workflowNotifyMail()->renderUserList($this->previousUsers),
]) . "\n";

//create text body
$this->textbody = strip_tags($this->templateApply('{header}
{action}<br />
{usersNotified}<br />
{usersPreviousRole}<br />
<br />
{changedSegments}
{footer}', [
    'header' => $this->header,
    'footer' => $this->footer,
    'action' => $action,
    'usersNotified' => $userNotificationText,
    'usersPreviousRole' => $userPreviousText,
    'changedSegments' => $this->htmlOnly,
]));

echo $this->templateApply('{header}
{action}<br />
{usersNotified}<br />
{usersPreviousRole}<br />
<br />
{changedSegments}
{footer}', [
    //just overwrite the changedSegments
    'usersNotified' => $userNotificationHTML,
    'usersPreviousRole' => $userPreviousHTML,
    'changedSegments' => $this->workflowNotifyHtmlMailSegmentList($this->segments),
]);
