<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2021 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html
  
 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or 
 plugin-exception.txt in the root folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/**#@+
 * @author Marc Mittag
 * @package portal
 * @version 2.0
 *
 */

/* @var $this Zend_View */
$this->render('general.phtml');

$this->subject = $this->translate->_('Translate5 - Aufgabe mit Fehlern / Warnungen importiert').' "'.$this->task->getTaskNr().' - '.$this->task->getTaskName().'"';

//is automatically merged with data from general.phtml
$data = [
    'header' => $this->header,
    'footer' => $this->footer,
];

$data['messages'] = join("</tr><tr>", array_map(function($item) {
    $item = (object) $item;
    $url = str_replace('{0}', $this->eventCode, $this->config->runtimeOptions->errorCodesUrl);
    $html = '<tr>';
    $html .= '<td style="white-space:nowrap;padding-right:10px;">'.$item->created.'</td>';
    $html .= '<td>'.ZfExtended_Logger_Summary::getLevel($item->level).'</td>';
    $html .= '<td><a href="'.$url.'">'.$item->eventCode.'</a></td>';
    return $html.'<td>'.htmlspecialchars($item->message).'</td>';
}, $this->logs));

$mailBody = $this->templateApply('{header}
Die folgende Aufgabe wurde mit Fehlern / Warnungen / Hinweisen importiert. Mit der Bitte um Beachtung.<br />
<br />
{taskFragment}
<br />
<br />
<table><tr><th style="text-align:left;padding-right:10px;">Datum:</th>
<th style="text-align:left;padding-right:10px;">Typ:</th>
<th style="text-align:left;padding-right:10px;">Code:</th>
<th style="text-align:left;padding-right:10px;">Meldung:</th></tr>
<tr>{messages}</tr></table>
{footer}', $data);

$this->textbody = strip_tags($mailBody);
echo $mailBody;

