<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5

 Copyright (c) 2013 - 2021 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt
 included in the packaging of this file.  Please review the following information
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html

 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or
 plugin-exception.txt in the root folder of translate5.

 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
             http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/*
 * SECTION TO INCLUDE PROGRAMMATIC LOCALIZATION
 * ============================================

    $translate->_('Im Projektportal {portalLink} wurde ein neues {projectType} erstellt.<br />
<strong>Project ID:</strong> {projectId} <br />
<strong>Project Name:</strong> {projectName}');

    $translate->_('Im Projektportal {portalLink} wurde ein neues {projectType} erstellt.<br />
<strong>Project ID:</strong> {projectId} <br />
<strong>Project Name:</strong> {projectName} <br />
<strong>Erstellt von:</strong> {createdByUser}');

 */

/* @var $this Zend_View */

$this->render('general.phtml');

// Setup subject
$this->subject = $this->translate->_('Translate5 - Projekt erstellt')
    . ' "' . $this->project->getId()
    . ' - ' . $this->project->getTaskName() . '"';

// Prepare data to merged with general.phtml's data
$data = [
    'header' => $this->header,
    'footer' => $this->footer,
    'role' => $this->translate->_(ACL_ROLE_PM),
    'projectId' => $this->project->getId(),
    'projectName' => $this->project->getTaskName(),
    'projectType' => $this->translate->_('taskType::' . $this->project->getTaskType()->id()),
];

$message = 'Im Projektportal {portalLink} wurde ein neues {projectType} erstellt.<br />
<strong>Project ID:</strong> {projectId} <br />
<strong>Project Name:</strong> {projectName}';

if(!empty($this->showTaskDescription)){
    $data['taskDescription'] = $this->project->getDescription();
    $message .= '<br /> <strong>'.$this->translate->_('Projektbeschreibung').':</strong> {taskDescription}';
}

if ($this->createdByUser) {
    $data['createdByUser'] = $this->createdByUser;
    $message .= ' <br />
<strong>Erstellt von:</strong> {createdByUser}';
}

if (! empty($this->taskCustomFields)) {
    foreach ($this->taskCustomFields as $customField) {
        $message .= ' <br />'
            . '<strong>' .
            $customField['label']
            . ':</strong> ' . $customField['value'];
    }
}

$data['body'] = $this->templateApply($message, $data);

// Build mail body
$mailBody = $this->templateApply('
{header}
{body}
{footer}', $data);

// Prepare a text version
$this->textbody = strip_tags($mailBody);

// Print mail body
echo $mailBody;
