<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2017 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html
  
 There is a plugin exception available for use with this release of translate5 for
 translate5 plug-ins that are distributed under GNU AFFERO GENERAL PUBLIC LICENSE version 3:
 Please see http://www.translate5.net/plugin-exception.txt or plugin-exception.txt in the root
 folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/**#@+
 * @author Marc Mittag
 * @package portal
 * @version 2.0
 *
 */

/* @var $this Zend_View */
$this->render('workflow/general.phtml');

$this->subject = $this->translate->_('Translate5 - Aufgabe zugewiesen').' "'.$this->task->getTaskNr().' - '.$this->task->getTaskName().'"';

//is automatically merged with data from general.phtml
$data = [
    'sourceLanguageTranslated' => $this->translate->_($this->sourceLanguage),
    'targetLanguageTranslated' => $this->translate->_($this->targetLanguage),
    'relaisLanguageTranslated' => $this->translate->_($this->relaisLanguage),
    'relaisLanguageFragment' => ($this->relaisLanguage ? $this->translate->_('<b>Relaissprache:</b> {relaisLanguageTranslated}<br />') : ''),
    'header' => $this->header,
    'footer' => $this->footer,
    'task' => $this->task->getDataObject(),
];

//FIXME date format!
//$data['task']->targetDeliveryDate = $data['task']->targetDeliveryDate;

$mailBody = $this->templateApply('{header}
Im Projektportal {portalLink} wurde Ihnen die Aufgabe <b>{task.taskNr} - {task.taskName}</b> zugewiesen.<br />
<b>Aufgabe:</b> {task.taskName}<br />
<b>Quellsprache:</b> {sourceLanguageTranslated}<br />
<b>Zielsprache:</b> {targetLanguageTranslated}<br />
{relaisLanguageFragment}<b>Lieferdatum:</b> {task.targetDeliveryDate}<br />
<b>Wortanzahl:</b> {task.wordCount}<br />
{footer}', $data);

$this->textbody = strip_tags($mailBody);
//FIXME: 
error_log($this->textbody);
echo $mailBody;

