<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2021 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html
  
 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or 
 plugin-exception.txt in the root folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/**#@+
 * @author Marc Mittag
 * @package portal
 * @version 2.0
 *
 */

$this->render('general.phtml');

//Define Action String
$this->subject = $this->translate->_('Translate5 - Aufgabe teilweise abgeschlossen').' "'.$this->task->getTaskNr().' - '.$this->task->getTaskName().'"';
$action = 'Im Projektportal {portalLink} wurde die Aufgabe <b>{task.taskNr} - {task.taskName}</b> durch einen Benutzer der Rolle <i>{currentRole}</i> abgeschlossen:<br />';
$action = $this->templateApply($action, [
    'task' => $this->task->getDataObject(),
    'currentRole' => $this->translate->_($this->triggeringStep),
]);

//list of current users:
$usersCurrentTpl = "Alle Benutzer der aktuellen Rolle <i>{currentRole}</i>:\n{currentUsers}<br/>\n";
$usersCurrentText = $this->templateApply($usersCurrentTpl,[
    'currentUsers' => $this->htmlOnly
]);
$usersCurrentHTML = $this->templateApply($usersCurrentTpl,[
    'currentUsers' => $this->workflowNotifyMail()->renderUserList($this->currentUsers)
]);

$template = '{header}
{action}<br />
{currentUser}<br />
<br />
{usersCurrentRole}<br />
{footer}';

//create text body
$this->textbody = strip_tags($this->templateApply($template, [
    'header' => $this->header,
    'footer' => $this->footer,
    'action' => $action,
    'currentUser' => $this->htmlOnly,
    'usersCurrentRole' => $usersCurrentText,
]));

echo $this->templateApply($template, [
    'currentUser' => empty($this->currentUser) ? '' : $this->workflowNotifyMail()->renderUserList([$this->currentUser]),
    'usersCurrentRole' => $usersCurrentHTML,
]);
