<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2021 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html
  
 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or 
 plugin-exception.txt in the root folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/**#@+
 * @author Marc Mittag
 * @package portal
 * @version 2.0
 *
 */

/* @var $this Zend_View */
$this->render('general.phtml');

$this->subject = $this->translate->_('Translate5 - Visuelle PDF-Freigabeergebnisse').' "'.$this->task->getTaskNr().' - '.$this->task->getTaskName().'"';

//is automatically merged with data from general.phtml
$data = [
    'header' => $this->header,
    'footer' => $this->footer,
    'role' => $this->translate->_(ucfirst(ACL_ROLE_PM)),
    'isApprovedQuestion' => $this->translate->_('Ist die Aufgabe genehmigt?'),
    'isApprovedAnswer' => $this->translate->_($this->isApproved ? 'Ja' : 'Nein'),
    'annotationLabel' => $this->translate->_('Anmerkung'),
    'pageLabel' => $this->translate->_('Seite'),
    'annotations' => '',
];

if(!empty($this->annotations)) {
    foreach ($this->annotations as $annotation) {
        $data['annotations'].= $annotation['text'].' / '.$annotation['page'].'<br>';
    }
}

$mailBody = $this->templateApply('{header}
Im Projektportal {portalLink} wurde Ihnen eine Aufgabe zugewiesen.<br/>
<br/>
<b>{isApprovedQuestion} <u>{isApprovedAnswer}</u></b>
<br/>
<br/>
<b>Rolle:</b> {role}<br/>
{taskFragment}
<br/>
<b>{annotationLabel} / {pageLabel}</b><br/>
{annotations}
{footer}', $data);

$this->textbody = strip_tags($mailBody);
echo $mailBody;
