<section id="sidebar">
                <!-- Intro -->
                <section id="intro">
                    <header>
                        <h1><a href="https://www.translate5.net/" target="_blank">Open Source translation management system</a></h1>
                        <p><a href="https://www.translate5.net/" target="_blank">Cloud translation, review- and post&shy;editing & terminology system</a></p>
                        <ul class="icons">
                            <li><i class="fa-chevron-circle-right"></i> <a href="/login">Login</a></li>
                        </ul>
                    </header>
                    <h2>About translate5</h2>
                    <ul class="icons">
                        <li><i class="fa-chevron-circle-right"></i> <a href="https://www.translate5.net/solutions/" target="_blank">Solution scenarios</a></li>
                        <li><i class="fa-chevron-circle-right"></i> <a href="https://www.translate5.net/resources/" target="_blank">Resources</a></li>
                        <li><i class="fa-chevron-circle-right"></i> <a href="https://www.translate5.net/who-is-behind/" target="_blank">Who is behind</a></li>
                    </ul>
                    <ul class="icons">
                        <li><a href="https://twitter.com/translate5_marc" class="fa-twitter" target="_blank"><span class="label">Twitter</span></a></li>
                        <li><a href="https://www.facebook.com/Translate5-412951439069652/" class="fa-facebook" target="_blank"><span class="label">Facebook</span></a></li>
                        <li><a href="mailto:info@translate5.net" class="fa-envelope" target="_blank"><span class="label">Email</span></a></li>
                    </ul>
                </section>