<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2021 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html
  
 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or 
 plugin-exception.txt in the root folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/* @var $this Zend_View */
?>  
Editor.controller.Localizer.addPluginInit('changeLog', function() {
    Ext.define("Editor.locale.plugins.ChangeLog.controller.Changelog", {
        override: "Editor.plugins.ChangeLog.controller.Changelog",
        btnText: '<?php echo $this->translate->_('Änderungsprotokoll der Version ');?>'
    });
    
    Ext.define("Editor.locale.plugins.ChangeLog.view.Changelog", {
        override: "Editor.plugins.ChangeLog.view.Changelog",
        strings: {
            date: '<?php echo $this->translate->_('Datum');?>',
            jiranumber: '<?php echo $this->translate->_('Änderungsnr.');?>',
            description: '<?php echo $this->translate->_('Beschreibung');?>',
            title: '<?php echo $this->translate->_('Aktuelle Änderungen an der Anwendung');?>',
            close: '<?php echo $this->translate->_('Schließen');?>'
        }
    });
    Ext.define("Editor.locale.plugins.ChangeLog.view.TypeColumn", {
        override: "Editor.plugins.ChangeLog.view.TypeColumn",
        strings: {
            type: '<?php echo $this->translate->_('Typ');?>'
        },
        types: {
            bugfix: '<?php echo $this->translate->_('Bugfix');?>',
            feature: '<?php echo $this->translate->_('Feature');?>',
            change: '<?php echo $this->translate->_('Change');?>'
        }
    });
});