<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2021 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html
  
 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or 
 plugin-exception.txt in the root folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/**#@+
 * @author Marc Mittag
 * @package editor
 * @version 1.0
 *
 */
echo sprintf('Hallo Admin,

es trat ein Fehler im Portal auf. Dies führte zu einem Abbruch der aufgerufenen Aktion.

Der Benutzer hat eine allgemeine Fehlermeldung erhalten.

Diese Mail wird in verschiedenen Versionen verschickt, je nachdem, was in der
application.ini aktiviert wurde.

Einmal mit einer Datei, die nur die einfache
Fehlermeldung enthält, einmal mit angehängtem miniDump, der die
wichtigsten Infos enthält, und einmal mit vollem Dump.

Falls der Mini- oder der Fulldump nicht ankommt, es aber laut application.ini
sollte, dann war der Error-Dump so groß, dass der Prozess
zu lange lief, um ihn anzuhängen.

lg

marc
'
);




