<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2017 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html
  
 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or 
 plugin-exception.txt in the root folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/


//used to calculate the base url from the request
$http=ZfExtended_Factory::get('Zend_Controller_Request_Http');
/* @var $http Zend_Controller_Request_Http */

$portal =(isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://" . $_SERVER['HTTP_HOST'] .$http->getBaseUrl().'/';

$salutation=$this->translate->_('Sehr geehrte(r)');
if($this->receiver->gender == 'f'){
    $salutation=$this->translate->_('Sehr geehrte Frau');
}else if($this->receiver->gender == 'm'){
    $salutation=$this->translate->_('Sehr geehrter Herr');
}

//fill data with generally needed variables
$data = [
    'portalUrl' => $portal,
    'portalLink' => '<a href="'.$portal.'">'.$portal.'</a>',
    'companyName' => $this->config->runtimeOptions->companyName,
    'salutation' => $salutation,
    'surName' => $this->receiver->gender=='n' ? ($this->receiver->surName.' '.$this->receiver->firstName) : $this->receiver->surName,
];

//prepare the htmlOnly disclaimer
$this->htmlOnly = $this->translate->_('- Die Daten sind nur in der HTML-Ansicht der E-Mail verfügbar! -');

//prepare the default taskFragment if a task is provided
if(!empty($this->pm)) {
    $data['pm'] = $this->pm->getDataObject();
}
if(!empty($this->task)) {
    $taskData = $this->workflowNotifyMail()->getTaskLanguages($this->task);
    $taskData['task'] = $this->task->getDataObject();
    $taskData['targetDeliveryDate'] = $this->workflowNotifyMail()->dateFormat($this->task->getTargetDeliveryDate());
    $taskData['wordCount'] = $this->task->getWordCount() > 0 ? $this->task->getWordCount() : '-';
    
    $customer=ZfExtended_Factory::get('editor_Models_Customer');
    /* @var $customer editor_Models_Customer */
    $customer->load($this->task->getCustomerId());
    //if the customer domain is set, use this domain as portal url and link
    if(!empty($customer->getDomain())){
        $data['portalUrl']=$customer->getDomain();
        $data['portalLink']='<a href="'.$customer->getDomain().'">'.$customer->getDomain().'</a>';
    }
    
    $data['taskFragment'] = $this->templateApply('<b>Aufgabe:</b> {task.taskName}<br />
    <b>Quellsprache:</b> {sourceLanguageTranslated}<br />
    <b>Zielsprache:</b> {targetLanguageTranslated}<br />
    {relaisLanguageFragment}<b>Lieferdatum Lektoren:</b> {targetDeliveryDate}<br />
    <b>Wortanzahl:</b> {wordCount}<br />', $taskData);
}

//prepare the header
$this->header = $this->templateApply('{salutation} {surName},<br/>
<br/>', $data);

//prepare the footer
$this->footer = $this->templateApply('<br/>
<br/>Vielen Dank und viele Grüße,
<br/>Ihr Projektmanagement Team
<br/>{companyName}
<br/>
<br/>Diese Email wurde automatisch generiert. Bitte antworten Sie nicht auf diese E-Mail!', $data);

//set the variables so they can be used when this template is rendered in other views
$this->data=$data;
$this->taskData=isset($taskData) ? $taskData : null;
