<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2021 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html
  
 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or 
 plugin-exception.txt in the root folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/* @var Zend_View $this */

$this->render('zfGeneral.phtml');

//check if there is customer domain defined for the user
//and use it as portal link in the mail
//otherwise use the defined domain in the zf config as portal link
$currentDomain = $_SERVER['HTTP_HOST'].APPLICATION_RUNDIR.'/';
$user = ZfExtended_Factory::get('ZfExtended_Models_User');
/* @var ZfExtended_Models_User $user */
$costomerId = $user->isValidCustomerDomain($this->receiver->userGuid, $currentDomain);

if(!$costomerId){
    $currentDomain=$this->config->runtimeOptions->server->name.APPLICATION_RUNDIR;
}

$portal = $this->config->runtimeOptions->server->protocol.$currentDomain;

$salutation=$this->translate->_('Sehr geehrte(r)');
if($this->receiver->gender == 'f'){
    $salutation=$this->translate->_('Sehr geehrte Frau');
}else if($this->receiver->gender == 'm'){
    $salutation=$this->translate->_('Sehr geehrter Herr');
}

//fill data with generally needed variables
$data = [
    'portalUrl' => $portal,
    'portalLink' => '<a href="'.$portal.'">'.$portal.'</a>',
    'companyName' => htmlspecialchars($this->config->runtimeOptions->companyName),
    'appName' => $this->config->runtimeOptions->appName,
    'salutation' => $salutation,
    'surName' => $this->receiver->gender=='n' ? ($this->receiver->firstName.' '.$this->receiver->surName) : $this->receiver->surName,
];

//prepare the htmlOnly disclaimer
$this->htmlOnly = $this->translate->_('- Die Daten sind nur in der HTML-Ansicht der E-Mail verfügbar! -');

//prepare the header
$this->header = $this->templateApply('{salutation} {surName},<br/>
<br/>', $data);

//prepare the footer
$this->footer = $this->templateApply('<br/>
<br/>Vielen Dank und viele Grüße,
<br/>Ihr Projektmanagement Team
<br/>{companyName}
<br/>
<br/>Diese Email wurde automatisch generiert. Bitte antworten Sie nicht auf diese E-Mail!', $data);

//set the variables so they can be used when this template is rendered in other views
$this->data = $data;
