<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5

 Copyright (c) 2013 - 2021 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt
 included in the packaging of this file.  Please review the following information
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html

 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or
 plugin-exception.txt in the root folder of translate5.

 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
             http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

$translate = ZfExtended_Zendoverwrites_Translate::getInstance();

?>
<style>
    body {
        background-color: #f2f2f2;
        font-family: Arial, sans-serif;
    }

    .container {
        max-width: 650px;
        margin: 0 auto;
        padding: 40px;
        background-color: #fff;
        border-radius: 10px;
        box-shadow: 0 2px 5px rgba(0,0,0,0.1);
    }

    .header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 20px;
    }

    .logo {
        max-width: 150px;
        height: auto;
    }

    h1 {
        font-size: 32px;
        font-weight: bold;
        margin-top: 0;
        margin-bottom: 20px;
    }

    p {
        font-size: 18px;
        margin-top: 0;
        margin-bottom: 40px;
    }

    .loading {
        display: flex;
        align-items: center;
        justify-content: center;
        height: 100px;
        background-image: url('/modules/editor/images/loading_ico.gif');
        background-size: 25px;
        background-repeat: no-repeat;
        background-position: center;
    }

    .hidden {
        display: none;
    }

    .error {
        color: red;
        font-weight: bold;
    }
</style>

<div class="container">
    <div class="header">
        <img class="logo" src="/images/translate5.png" alt="translate5">
        <h1><?php echo $translate->_('Export Visual as PDF'); ?></h1>
    </div>
    <p class="export-running-message"><?php echo $translate->_('Export is running. Please wait...'); ?></p>
    <div class="loading"></div>
    <div class="result hidden">
        <p><?php echo $translate->_('The PDF is now available for download!'); ?></p>
        <a href="#" class="btn download hidden"><?php echo $translate->_('Download'); ?></a>
    </div>
    <div class="error hidden"></div>

    <div><h4 style="color: #ff004b"><?php echo $translate->_('<u>Hint:</u><br />All pages and files of the Visual will be merged to a single PDF. In case of Website downloads or HTML imports, it can happen that pages can not be printed due to technical deficiencies of the page. In these cases, a blank page is generated instead.'); ?></h4></div>
</div>

<script>

    var apiUrl = '/editor/plugins_visualreview_export/status' +
        '?taskId=<?php echo $this->taskId; ?>&workerId=<?php echo $this->workerId; ?>';

    function checkFileAvailability() {
        fetch(apiUrl, {
            headers: {
                'Csrftoken': '<?php echo $this->csrfToken; ?>'
            }
        })
            .then(response => response.ok ? response.json() : Promise.reject(response))
            .then(data => {
                if (data.hasError) {
                    showExportError();

                    return;
                }
                if (! data.isAvailable) {
                    setTimeout(checkFileAvailability, 3000);

                    return;
                }

                window.location.href = data.downloadLink;
                setTimeout(function(){ window.close(); }, 300);
            })
            .catch(error => {
                showExportError();
            });
    }

    function showExportError() {
        document.querySelector('.loading').classList.add('hidden');
        document.querySelector('.export-running-message').classList.add('hidden');
        document.querySelector('.error').textContent = '<?= $translate->_('An error occurred!') . ' '; ?>';
        document.querySelector('.error').textContent += '<?= $translate->_('For more info, check the result log.'); ?>';
        document.querySelector('.error').classList.remove('hidden');
    }

    checkFileAvailability();

</script>
