<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2021 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html
  
 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or 
 plugin-exception.txt in the root folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/
/** @var editor_Models_Languages $langs */
$langs = ZfExtended_Factory::get('editor_Models_Languages');
$available = array_keys($langs->loadAllKeyCustom('rfc5646','rfc5646'));

$locale = filter_var($_REQUEST['lang'], FILTER_SANITIZE_SPECIAL_CHARS);

if(!in_array($locale, $available, true)){
    $locale = 'en';
}

?>

<iframe width="100%" height="100%" src="/documentation/Translate5 Guide <?php echo strtoupper($locale);?>.pdf" </iframe>
