<?php
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2021 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html
  
 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or 
 plugin-exception.txt in the root folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

$translate = ZfExtended_Zendoverwrites_Translate::getInstance();
$preferencesYoutubeVideoGuideUrl = $translate->_("{PreferencesYoutubeVideoGuideUrl}");
$cliYoutubeVideoGuideUrl = $translate->_("{CliYoutubeVideoGuideUrl}");
//{PreferencesYoutubeVideoGuideUrl} and {PreferencesYoutubeVideoGuideDescriptionContent} are used as static source text for producing translatable content
//in de/en .xliff files.
//The content can be found in the de.xliff and en.xliff locales files for the default module.
?>
<div style="width:49%; height: 100%; display:inline-block;">
    <iframe name="youtubevideoframe" src="<?php echo $preferencesYoutubeVideoGuideUrl; ?>"
    frameborder="0"
    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
    allowfullscreen
    style="width: 100%; height: 70%;"
    >
    </iframe>
<?php echo $translate->_("{PreferencesYoutubeVideoGuideDescriptionContent}"); ?>
</div>
<div style="width:49%; height: 70%; display:inline-block;">
    <iframe name="youtubevideoframeCli" src="<?php echo $cliYoutubeVideoGuideUrl; ?>"
            frameborder="0"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
            allowfullscreen
            style="width: 100%; height: 100%;"
        >
    </iframe>
    <?php echo $translate->_("{CliYoutubeVideoGuideDescriptionContent}"); ?>
</div>