/*
 START LICENSE AND COPYRIGHT
 
 This file is part of Translate5 Editor Javascript GUI and build on ExtJs 4 lib
 
 Copyright (c) 2013 Marc Mittag; MittagQI - Quality Informatics; All rights reserved.
 
 Contact:  http://www.MittagQI.com/  /  service (ÄTT) MittagQI.com
 
 This file may be used under the terms of the GNU General Public License version 3.0
 as published by the Free Software Foundation and appearing in the file gpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU General Public License version 3.0 requirements will be met:
 http://www.gnu.org/copyleft/gpl.html.

 For this file you are allowed to make use of the same FLOSS exceptions to the GNU 
 General Public License version 3.0 as specified by Sencha for Ext Js. 
 Please be aware, that Marc Mittag / MittagQI take no warranty
 for any legal issue, that may arise, if you use these FLOSS exceptions and recommend
 to stick to GPL 3. For further information regarding this topic please see the attached 
 license.txt of this software package.
 
 MittagQI would be open to release translate5 under EPL or LGPL also, if this could be
 brought in accordance with the ExtJs license scheme. You are welcome to support us
 with legal support, if you are interested in this.
 
 
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU General Public License version 3.0 http://www.gnu.org/copyleft/gpl.html
             with FLOSS exceptions (see floss-exception.txt and ux-exception.txt at the root level)
 
 END LICENSE AND COPYRIGHT 
 */

/**#@++
 * @author Marc Mittag
 * @package editor
 * @version 1.0
 *
 */
/*
 * File: app/view/ui/changealike/Grid.js
 *
 * This file was generated by Ext Designer version 1.2.3.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Editor.view.ui.changealike.Grid', {
  extend: 'Ext.grid.Panel',

  item_segmentNrInTaskColumn: 'Nr.', 
  item_sourceColumn: 'Quelle', 
  item_targetColumn: 'Ziel', 
  item_filterColumn: 'In aktueller Filterung enthalten', 
  item_sourceMatchColumn: 'Quell-Treffer', 
  item_targetMatchColumn: 'Ziel-Treffer', 
  
  initComponent: function() {
    var me = this;

    Ext.applyIf(me, {
      columns: [
        {
          dataIndex: 'segmentNrInTask',
          text: me.item_segmentNrInTaskColumn,
          width: 50
        },
        {
          xtype: 'gridcolumn',
          dataIndex: 'source',
          tdCls: 'alike-source-field segment-tag-column',
          width: 250, 
          renderer: function(value, metaData, record) {
            if(record.get('sourceMatch')) {
              metaData.style = 'font-style: italic;';
            }
            return value;
          },
          text: me.item_sourceColumn
        },
        {
          xtype: 'gridcolumn',
          dataIndex: 'target',
          tdCls: 'alike-target-field segment-tag-column',
          width: 250,
          renderer: function(value, metaData, record) {
            if(record.get('targetMatch')) {
              metaData.style = 'font-style: italic;';
            }
            return value;
          },
          text: me.item_targetColumn
        },
        {
          xtype: 'booleancolumn',
          dataIndex: 'infilter',
          width: 180,
          text: me.item_filterColumn
        },
        {
          xtype: 'booleancolumn',
          dataIndex: 'sourceMatch',
          width: 90, 
          text: me.item_sourceMatchColumn
        },
        {
          xtype: 'booleancolumn',
          dataIndex: 'targetMatch',
          width: 80, 
          text: me.item_targetMatchColumn
        }
      ],
      viewConfig: {
        //loadMask: false
      },
      selModel: Ext.create('Ext.selection.CheckboxModel', {
        injectCheckbox: 3
      })
    });

    me.callParent(arguments);
  }
});