<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>translate5 - Open Source translation system</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="css/translate5.css?v=2" media="screen" rel="stylesheet" type="text/css" />
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon"/>
   <style>
        body { text-align: center; padding: 150px; }
        h1 { font-size: 50px; padding-top:10px;}
        p { margin-bottom:10px; }
        body { font: 20px Helvetica, sans-serif; color: #333; }
        article { display: block; text-align: left; width: 650px; margin: 0 auto; }
        #header {float:left;margin-right:30px;}
    </style>
</head>
<body>

<article>

    <div id="header">
        <img src="images/translate5.png?v=1" alt="translate5">
    </div>
    <h1>We&rsquo;ll be back <br>soon!</h1>
    <div style="clear:both;">
        <p>Fatal: Could not connect to the database! <br><b>If you get this message in the Browser: try to reload the application.</b> <br>See error log for details.</p>
    </div>
</article>
</body>
</html>
<!--
If this file could be loaded, we just start a comment to hide the text printed by the die command at the calling place!