
/*
START LICENSE AND COPYRIGHT

 This file is part of translate5
 
 Copyright (c) 2013 - 2017 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ATT) MittagQI.com

 This file may be used under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE version 3
 as published by the Free Software Foundation and appearing in the file agpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU AFFERO GENERAL PUBLIC LICENSE version 3 requirements will be met:
 http://www.gnu.org/licenses/agpl.html
  
 There is a plugin exception available for use with this release of translate5 for
 translate5: Please see http://www.translate5.net/plugin-exception.txt or 
 plugin-exception.txt in the root folder of translate5.
  
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU AFFERO GENERAL PUBLIC LICENSE version 3 with plugin-execption
			 http://www.gnu.org/licenses/agpl.html http://www.translate5.net/plugin-exception.txt

END LICENSE AND COPYRIGHT
*/

/**#@++
 * @author Marc Mittag
 * @package editor
 * @version 1.0
 *
 */
/*
 * File: app/view/ui/changealike/Window.js
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Editor.view.ui.changealike.Window', {
  extend: 'Ext.window.Window',
  requires: [
    'Editor.view.changealike.Grid'
  ],

  title: 'Aktuelles Segment für die folgenden Segmente übernehmen?',
  height: 570,
  itemId: 'changealikeWindow',
  width: 955,
  layout: {
    align: 'stretch',
    type: 'vbox'
  },
  closeAction: 'hide',
  modal: true,

  item_cancelBtn: 'Keine Änderungen durchführen',
  item_saveBtn: 'Änderungen übernehmen',

  initConfig: function(instanceConfig) {
    var me = this,
    config;

    config = {
        title: me.title, //see EXT6UPD-9
      items: [
        {
          xtype: 'container',
          padding:10,
          height:100,
          autoScroll: true,
          cls: 'segment-tag-container',
          tpl: this.items_segmentData, 
          itemId: 'infoText'
        },
        {
          xtype: 'changealikeGrid',
          flex: 1
        }
      ],
      dockedItems: [
        {
          xtype: 'toolbar',
          ui: 'footer',
          flex: 1,
          dock: 'bottom',
          layout: {
            pack: 'end',
            type: 'hbox'
          },
          items: [
            {
              xtype: 'button',
              itemId: 'cancelBtn',
              text: me.item_cancelBtn
            },
            {
              xtype: 'button',
              itemId: 'saveBtn',
              text: me.item_saveBtn
            }
          ]
        }
      ]
    };

    if (instanceConfig) {
        me.self.getConfigurator().merge(me, config, instanceConfig);
    }
    return me.callParent([config]);
  }
});