<?php
 /*
 START LICENSE AND COPYRIGHT
 
 This file is part of Translate5 Editor PHP Serverside and build on Zend Framework
 
 Copyright (c) 2013 Marc Mittag; MittagQI - Quality Informatics;  All rights reserved.

 Contact:  http://www.MittagQI.com/  /  service (ÄTT) MittagQI.com

 This file may be used under the terms of the GNU General Public License version 3.0
 as published by the Free Software Foundation and appearing in the file gpl3-license.txt 
 included in the packaging of this file.  Please review the following information 
 to ensure the GNU General Public License version 3.0 requirements will be met:
 http://www.gnu.org/copyleft/gpl.html.

 For this file you are allowed to make use of the same FLOSS exceptions to the GNU 
 General Public License version 3.0 as specified by Sencha for Ext Js. 
 Please be aware, that Marc Mittag / MittagQI take no warranty  for any legal issue, 
 that may arise, if you use these FLOSS exceptions and recommend  to stick to GPL 3. 
 For further information regarding this topic please see the attached license.txt
 of this software package.
 
 MittagQI would be open to release translate5 under EPL or LGPL also, if this could be
 brought in accordance with the ExtJs license scheme. You are welcome to support us
 with legal support, if you are interested in this.
 
 
 @copyright  Marc Mittag, MittagQI - Quality Informatics
 @author     MittagQI - Quality Informatics
 @license    GNU General Public License version 3.0 http://www.gnu.org/copyleft/gpl.html
             with FLOSS exceptions (see floss-exception.txt and ux-exception.txt at the root level)
 
 END LICENSE AND COPYRIGHT 
 */

/**#@+ 
 * @author Marc Mittag
 * @package editor
 * @version 1.0
 * 
 */
/**
 * Imports the reference file data structure
 * 
 * Note to several unset($node->id) calls used in this class:
 *  In Working Files the ID ist afterwards generated by the sync to the files table.
 *  For the reference no id must be set, so that auto ids are generated on client side
 */
class editor_Models_Import_DirectoryParser_ReferenceFiles extends editor_Models_Import_DirectoryParser_WorkingFiles {
    /**
     * empty array disables file extension filter
     * @var array
     */
    protected $_importExtensionList = array();
    
    /**
     * Adds reference file specific infos to the tree node 
     * @param string $filename
     * @return stdClass
     */
    protected function getFileNode($filename) {
        $node = parent::getFileNode($filename);
    	if($node->isFile) {
    	    $node->href = $node->path.$node->filename;
    	    $node->hrefTarget = '_blank';
    	}
    	unset($node->id); //@see class head comment
    	return $node;
    }
    
    /**
     * (non-PHPdoc)
     * @see editor_Models_Import_DirectoryParser_WorkingFiles::getDirectoryNode()
     */
    protected function getDirectoryNode($directory){
        $node = parent::getDirectoryNode($directory);
        unset($node->id); //@see class head comment
        return $node;        
    }
    
    /**
     * (non-PHPdoc)
     * @see editor_Models_Import_DirectoryParser_WorkingFiles::getInitialRootNode()
     */
    protected function getInitialRootNode() {
        $node = parent::getInitialRootNode();
        $node->path = APPLICATION_RUNDIR.'/editor/referencefile';
        unset($node->id); //@see class head comment
        return $node;
    }
}